vdaas/vald

- .gitignore
I added .gitignore settings for ignoring binary files in `cmd/` and `hack/`.
> Ignoring binaries in cmd/ and hack/

- Makefile
- hack/e2e/benchmark/agent/ngt/ngt_bench_test.go
implement e2e sequential operation benchmark test
```
% make bench-agent       
rm -rf /tmp/ngt/
rm -rf pprof/agent/ngt
mkdir -p /tmp/ngt
mkdir -p pprof/agent/ngt
go test -count=1 \
-timeout=1h \
-bench=gRPCStream \
-benchmem \
-o pprof/agent/ngt/agent.bin \
-cpuprofile pprof/agent/ngt/cpu-stream.out \
-memprofile pprof/agent/ngt/mem-stream.out \
./hack/e2e/benchmark/agent/ngt/ngt_bench_test.go
2019-10-23 14:39:51     [INFO]: server agent-grpc executing preStartFunc
2019-10-23 14:39:51     [INFO]: gRPC server agent-grpc starting on 127.0.0.1:8082
2019-10-23 14:39:51     [INFO]: REST server agent-rest starting on 127.0.0.1:8081
goos: darwin
goarch: amd64
BenchmarkAgentNGTgRPCStream/fashion-mnist-784-euclidean/StreamInsert_60000_objects-4                   1        9618903559 ns/op …
```
> add sequential operation benchmark

- internal/db/nosql/cassandra/cassandra.go
- pkg/meta/cassandra/handler/grpc/handler.go
I modified the behavior of GetMetas and GetMetasInverse methods.
They returns found values whenever passed argument contains invalid keys (and empty string values are returned).
This is a fix of #105 issue.
> :bug: Fix response structure of GetMetas(Inverse) #105

- Makefile.d/functions.mk
macOS echo cannot use color format.
printf can use colored, so I changed printf from echo.
replace echo with printf and fix format.
nothing
- Kubernetes Version: 1.17.0
> use printf instead of echo

- internal/version/version_test.go
I added test case for `internal/versions`.
> addd test case for `internal/versions`

- internal/config/config.go
enables file read config.
for example
```yaml
password: "file:///etc/password"
```
> feature add read from file config functionallity

- internal/config/server.go
- pkg/agent/ngt/handler/grpc/option.go
- pkg/agent/ngt/usecase/agentd.go
- pkg/gateway/vald/handler/grpc/option.go
- pkg/gateway/vald/usecase/vald.go
- pkg/manager/index/handler/grpc/option.go
- pkg/manager/replication/handler/grpc/option.go
- vald/values.yaml
make bidirectional stream concurrency configurable by bidirectional_stream_concurrency field in gRPC server config.
NOTE: the handlers of index manager and replication manager are not modified.
> [patch] Make bidirectional stream concurrency configurable

- internal/client/discoverer/discover.go
internal/client/discoverer/discovery.go.discover uses alot of goroutine, but it's not necessary, so I removed them and replaced to searial logic.
we don't need such a speed for discovery
> [patch] discovery logic changed

- pkg/manager/compressor/usecase/compressord.go
I forgot to add nil check for r.observability on compressor daemon PreStart.
Nothing.
Nothing.
> Add nil check on compressor daemon PreStart

- vald/templates/agent/deployment.yaml
- vald/templates/agent/statefulset.yaml
gateway rebalances insert indices however, agents deployed less than average on some nodes will have more memory and more graph index.
It will make huge problem for massive scale data. I added Pod antiaffinity rule to resolve this problem
> [patch] add agent anti affinity

- charts/vald/templates/manager/compressor/configmap.yaml
- charts/vald/values.yaml
- go.mod
- go.sum
- internal/client/compressor/option.go
- internal/config/compress.go
- internal/errors/compressor.go
- internal/errors/worker.go
- internal/observability/metrics/manager/compressor/compressor.go
- internal/worker/queue.go
- internal/worker/queue_option.go
- internal/worker/worker.go
- internal/worker/worker_option.go
- k8s/operator/helm/valdrelease.yaml
- pkg/manager/compressor/config/config.go
- pkg/manager/compressor/handler/grpc/handler.go
- pkg/manager/compressor/handler/grpc/option.go
- pkg/manager/compressor/service/compress.go
- pkg/manager/compressor/service/compress_option.go
- pkg/manager/compressor/service/registerer.go
- pkg/manager/compressor/service/registerer_option.go
- pkg/manager/compressor/usecase/compressord.go
Refactoring manager-compressor.
- extract worker loop
- add `Registerer` service that processes requested meta vector and registers it asynchronously
- in the PreStop phase, the terminated compressor sends meta_vectors in its queue to other compressor.
Nothing.
local KinD.
> ♻️ Refactoring compressor

- go.mod
- go.sum
- internal/observability/metrics/manager/compressor/compressor.go
- internal/observability/metrics/mem/mem.go
- internal/observability/metrics/runtime/cgo/cgo.go
- internal/worker/queue.go
- internal/worker/worker.go
- k8s/agent/statefulset.yaml
- k8s/discoverer/deployment.yaml
- k8s/gateway/vald/deployment.yaml
- k8s/operator/helm/valdrelease.yaml
Resolve worker busy loop.
And fixed metrics definitions.
compressor uses CPU too much, i've profiled using pprof.
it shows `worker.queue.pop` occupies the large amount of CPU.
On my k8s cluster.
> ♻️ Resolve busy-loop on worker

- charts/vald/values.yaml
- pkg/manager/compressor/service/registerer.go
- pkg/manager/compressor/usecase/compressord.go
Currently, vectors in registerer queue are send to other compressor during PreStop function in shutdown process.
However, it may be an issue that vectors in queue lost with terminating pods.
In this PR, backup processes will be run during PostStop function in shutdown process.
Nothing.
my K8s cluster.
> ♻️ Compressor: backup vectors in queue using PostStop function

- Makefile
- Makefile.d/ml.mk
- hack/ml/.gitignore
- internal/core/converter/tensorflow/option.go
- internal/core/converter/tensorflow/tensorflow.go
- internal/errors/tensorflow.go
Signed-off-by: datelier <57349093+datelier@users.noreply.github.com>
> fix tensorflow.go, option.go

- .github/workflows/coverage.yml
- .github/workflows/update_pull_request_template.yml
- README.md
Revised calculation settings of coverages.
Nothing.
Nothing.
> 💚 Revise CI: coverage settings

- .github/workflows/update-protobuf.yml
I just added build dispatch workflow for vald-client-node.
https://github.com/vdaas/vald-client-node
> 💚 Add vald-client-node to protobuf dispatches list

- internal/log/log_test.go
- internal/log/option_test.go
I fixed faling tests of `internal/log` package.
And I modified to match the test template.
The following packages are directly under `internal / log`. 
I am planning to fix these packages in another PR without including them in this PR.
>  Fix failing tests of `internal/log` and modified to match the test template 

- go.mod
- go.sum
- internal/log/logger/type_test.go
I fixed `internal/log/logger` to match the test template.
> Fix `internal/log/logger` to match the test template

- internal/log/format/format_test.go
I fixed `internal/log/foramt` to match the test template.
> Fix`internal/log/format` to match the test template

- .github/workflows/helm-lint.yml
- charts/vald/values.yaml
I accidentally embed a bug in #376.
This PR is fix patch for it. 
And also i added a CI workflow for running helm-lint on PRs.
nothing.
nothing.
> 🐛 Fix missing value on compressor health servers

- charts/vald/templates/agent/daemonset.yaml
- charts/vald/templates/agent/deployment.yaml
- charts/vald/templates/agent/statefulset.yaml
- charts/vald/templates/discoverer/daemonset.yaml
- charts/vald/templates/discoverer/deployment.yaml
- charts/vald/templates/gateway/vald/daemonset.yaml
- charts/vald/templates/gateway/vald/deployment.yaml
- charts/vald/templates/manager/backup/daemonset.yaml
- charts/vald/templates/manager/backup/deployment.yaml
- charts/vald/templates/manager/compressor/daemonset.yaml
- charts/vald/templates/manager/compressor/deployment.yaml
- charts/vald/templates/manager/index/daemonset.yaml
- charts/vald/templates/manager/index/deployment.yaml
- charts/vald/templates/meta/daemonset.yaml
- charts/vald/templates/meta/deployment.yaml
- charts/vald/values.yaml
- docs/guides/configurations.md
- go.mod
- go.sum
- Added topologySpreadConstraints for pods in each deployment/daemonset/statefulset template
- Added missing affinity fields in each daemonset template
- Added notes about topologySpreadConstraints in docs/configurations.md
nothing
nothing
- NGT Version: 1.11.4
> ✨ Add topology spread constraints

- internal/config/blob.go
- internal/db/storage/blob/blob.go
- internal/db/storage/blob/blob_test.go
- internal/db/storage/blob/option.go
- internal/db/storage/blob/s3/option.go
- internal/db/storage/blob/s3/s3.go
- Added internal/db/storage/blob & internal/db/storage/blob/s3 packages
- already tested using blob_test.go
Nothing.
Running blob_test.go
> ✨ Add internal/db/storage/blob

- .github/chatops_permissions.yaml
- .github/workflows/chatops.yml
- Makefile
- Makefile.d/functions.mk
- Makefile.d/test.mk
- go.mod
- go.sum
- added ChatOps `/gen-test` command to run gotests.
- revise Makefile gotests/gen task
- improve `make` startup time
nothing.
nothing.
> ✨ Add gen-test command for chatops

- charts/vald/values.yaml
- go.mod
- go.sum
- internal/config/ngt.go
- internal/observability/metrics/agent/ngt/ngt.go
- pkg/agent/ngt/handler/grpc/handler.go
- pkg/agent/ngt/service/ngt.go
- pkg/agent/ngt/service/ngt_test.go
- pkg/manager/index/service/indexer.go
- add trace spans for several functions that called by daemons
- add metrics about create index execution (agent)
- add `initial_delay_max_duration` that affects to start auto-index daemon after random duration within it.
#343
nothing.
> ✨ add trace spans and metrics for agent-ngt and index-manager

- .github/workflows/chatops.yml
> Revise ChatOps not to add go.mod & go.sum when /format runs

- .all-contributorsrc
- internal/db/storage/blob/s3/s3_test.go
- internal/net/grpc/interceptor.go
- internal/net/grpc/stream.go
- internal/safety/safety.go
- internal/servers/server/option.go
- pkg/agent/core/ngt/usecase/agentd.go
- pkg/agent/sidecar/handler/grpc/handler_test.go
- pkg/agent/sidecar/usecase/initcontainer/initcontainer.go
- pkg/agent/sidecar/usecase/initcontainer/initcontainer_test.go
- pkg/agent/sidecar/usecase/sidecar/sidecar.go
- pkg/agent/sidecar/usecase/sidecar/sidecar_test.go
- pkg/discoverer/k8s/usecase/discovered.go
- pkg/gateway/vald/usecase/vald.go
- pkg/manager/backup/cassandra/usecase/backupd.go
- pkg/manager/backup/mysql/usecase/backupd.go
- pkg/manager/compressor/usecase/compressord.go
- pkg/manager/index/usecase/indexer.go
- pkg/manager/replication/agent/usecase/backupd.go
- pkg/manager/replication/controller/usecase/discovered.go
- pkg/meta/cassandra/usecase/meta.go
- pkg/meta/redis/usecase/meta.go
- Added gRPC interceptor to recover panic in handlers
- Refactor BidirectionalStream func.
- https://github.com/grpc/grpc-go/blob/fff75ae40fde3e38ad4dc57695d639c8a99cb1ba/stream.go#L1305-L1307
Nothing.
Local.
> 🐛  Add gRPC interceptor to recover panic in handlers

- .github/chatops_permissions.yaml
- .github/workflows/chatops.yml
- .github/workflows/semver.yml
- CHANGELOG.md
- Makefile
- example/helm/values-standalone-agent-ngt.yaml
- hack/CHANGELOG.template.md
- Updated CHANGELOG since v0.0.30.
- Added ChatOps feature `/changelog`.
- Updated semver workflow.
Nothing.
Not yet. the first release after this PR merged may fail..
> Add changelog command (ChatOps)

- k8s/tools/cli/loadtest/cronjob.yaml
- k8s/tools/cli/loadtest/job.yaml
I've found several mistakes in k8s manifests of loadtest jobs while i'm trying to apply them.
fixed them.
Nothing.
nothing.
> Fix k8s manifests for loadtest jobs

- pkg/tools/cli/loadtest/usecase/load.go
I found that the `method` variable is not passed to loadtest service. without it, the loadtest app does not work correctly.
fixed it.
nothing.
nothing.
> Add WithOperation func to loadtest usecase

- internal/log/level/level_test.go
I fixed `internal/log/level` pacakge based on generated test code.
this code's coverage is 100%.
> Fix internal/log/level pacakge test

- docs/overview/architecture.md
This document add a concept section to the architecture document to give an overall concept of Vald before deep diving into details.
> [patch] Documentation: add concept section to the architecture document

- internal/log/retry/option_test.go
- internal/log/retry/retry.go
- internal/log/retry/retry_test.go
I fixed `internal/log/retry` package based on the generated test code.
this code's coverage is 100%.
> Fix `internal/log/retry` pacakge

- .github/workflows/chatops.yml
Fix /format command
nothing.
nothing
> Fix /format command

- internal/backoff/backoff_test.go
I fixed failing the test of `internal/backoff`.
> Fix failing the test of `internal/backoff`

- internal/net/http/middleware/timeout_test.go
I fixed failing the test of `internal/net/middleware`.
> Fix failing the test of `internal/net/middleware`

- docs/contributing/coding-style.md
I fixed some links which occur as dead links at the official website:
- change absURL about source code path (not another document link)
- change godoc domain
> fix invalid link

- .github/workflows/dockers-agent-sidecar-image.yml
- charts/vald/values.yaml
- internal/config/sidecar.go
- internal/config/sidecar_test.go
- internal/config/transport.go
- internal/db/storage/blob/s3/reader/option.go
- internal/db/storage/blob/s3/reader/option_test.go
- internal/db/storage/blob/s3/reader/reader.go
- internal/db/storage/blob/s3/reader/reader_test.go
- internal/db/storage/blob/s3/s3.go
- internal/db/storage/blob/s3/session/option.go
- internal/db/storage/blob/s3/session/session.go
- internal/errors/blob.go
- internal/errors/blob_test.go
- internal/net/http/client/client.go
- internal/net/http/client/client_test.go
- internal/net/http/client/option.go
- internal/net/http/client/option_test.go
- pkg/agent/sidecar/service/restorer/option.go
- pkg/agent/sidecar/service/restorer/option_test.go
- pkg/agent/sidecar/service/restorer/restorer.go
- pkg/agent/sidecar/usecase/initcontainer/initcontainer.go
- pkg/agent/sidecar/usecase/sidecar/sidecar.go
- pkg/tools/cli/loadtest/usecase/load_test.go
- use io.Pipe for reading S3 bucket data
- add backoff logic for restorer
nothing.
nothing
> [patch] Refactor agent-sidecar: fix S3 reader & add backoff logic

- .github/workflows/dockers-agent-sidecar-image.yml
- internal/db/storage/blob/s3/writer/writer.go
- internal/db/storage/blob/s3/writer/writer_test.go
- removed ctx from struct because of anti-pattern.
nothing.
nothing.
> internal/db/storage/blob/s3: remove ctx from struct

- docs/contributing/coding-style.md
- internal/safety/safety_test.go
This PR fix the failed test case in internal/safety package.
> Fix failed test case of internal/safety package

- internal/db/storage/blob/s3/session/session.go
AWS region is a required parameter even if it is an empty string.
https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config
In this PR, it can be specified with empty string.
nothing.
nothing.
> AWS region can be specified with empty string

- docs/contributing/coding-style.md
- internal/params/option.go
- internal/params/option_test.go
- internal/params/params.go
- internal/params/params_test.go
I added `internal/params` pacakge test.
this test' coverage is 100%.
> Add `internal/params` pacakge test

- .github/workflows/codeql-analysis.yml
- Makefile
- Add CodeQL workflow from GitHub.com
- After this PR is merged, please remove LGTM.com integration.
- in the LGTM analysis, libhdf5 cannot be installed by configuring lgtm.yml.
- it is easier to configure the runner environment by using CodeQL workflow (GitHub Actions).
Nothing.
Nothing.
> Add CodeQL workflow instead of LGTM.com

- go.sum
- internal/errgroup/group_test.go
I added a test case for internal/errorgroup.
> Added test case for `internal/errorgroup` 

- charts/vald/values.yaml
- internal/config/blob.go
- internal/config/sidecar.go
- internal/db/storage/blob/s3/option.go
- internal/db/storage/blob/s3/reader/option.go
- internal/db/storage/blob/s3/reader/reader.go
- internal/db/storage/blob/s3/s3.go
- internal/db/storage/blob/s3/writer/option.go
- internal/db/storage/blob/s3/writer/writer.go
- internal/errors/io.go
- internal/io/io.go
- pkg/agent/sidecar/service/observer/observer.go
- pkg/agent/sidecar/service/restorer/option.go
- pkg/agent/sidecar/service/restorer/restorer.go
- pkg/agent/sidecar/usecase/initcontainer/initcontainer.go
- pkg/agent/sidecar/usecase/sidecar/sidecar.go
- Add `max_chunk_size` option
- Add backoff option to S3 reader
- Add internal/io package
Nothing.
On GKE.
> [patch] Revise S3 reader/writer: compatible with IBM Cloud Object Storage

- internal/runner/option_test.go
- internal/runner/runner.go
- internal/runner/runner_mock_test.go
- internal/runner/runner_test.go
I added test code for `internal/runner` pacakge.
> Add `internal/runner` test

- .github/codeql/codeql-config.yaml
- internal/config/log.go
- internal/config/log_test.go
I added test of `internal/config/log.go`
> added internal/config/log test

- charts/vald/values.yaml
- pkg/agent/sidecar/service/observer/observer.go
- pkg/agent/sidecar/service/observer/option.go
Added cancel hook for file watcher.
agent-sidecar does not stop correctly when it receives SIGTERM without it.
made the default post_stop_timeout longer.
nothing.
nothing.
> [agent-sidecar] Add cancel hook for file watcher

- internal/config/tls.go
- internal/config/tls_test.go
- internal/tls/option.go
- internal/tls/tls.go
I added test of `internal/config/tls`.
And also, I refactored `internal/tls` for testing
> add internal/config/tls test

- internal/runner/runner.go
- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/sidecar/usecase/sidecar/sidecar.go
use Len() and InsertVCacheLen() method for IndexInfo because the current implementation of IndexInfo does not returns correct values (maybe UUIDs method cannot count too many index).
add mutex for CreateIndex & SaveIndex.
nothing.
nothing.
> [agent-ngt] use Len and InsertVCacheLen method for IndexInfo / add mutex for (Create|Save)Index

- .github/chatops_commands.md
- .github/workflows/chatops-help.yml
- .github/workflows/chatops.yml
- .github/workflows/test.yml
- Makefile.d/test.mk
Run tests only for cmd, internal, pkg packages when PR check.
Add chatops help.
nothing.
nothing.
> [CI tests] exclude hack codes

- internal/log/mock/logger.go
- internal/log/mock/logger_test.go
I added test of `internal/log/mock/logger` and updated its godoc
> add log/mock/logger test

- internal/file/watch/option_test.go
I added test case for `internal/file/watch/option_test.go`.
> Added test case for `internal/file/watch/option_test.go`

- internal/singleflight/singleflight.go
- internal/singleflight/singleflight_test.go
I fix the bug of singleflight pacakge test.
this code's coverage is 100%.
> Bug singleflight test

- internal/log/mock/retry.go
- internal/log/mock/retry_test.go
I added `internal/log/mock/retry` test.
> add internal/log/mock/retry test

- docs/usecase/usage-example.md
Author review required?
This PR create the use case document to describe the general use case of Vald.
> Add use case document

- internal/singleflight/singleflight.go
- internal/singleflight/singleflight_test.go
I added the test of `internal/singleflight` and updated its godoc
> add internal/singleflight test

- internal/file/file.go
- internal/file/file_test.go
I added test case for `internal/file`.
> Add test case for `internal/file`

- internal/cache/gache/gache.go
- internal/cache/gache/option.go
This PR fixed the global cache bug in internal package. 
Since the defaultOps is a global instance and created only once, the instance will be shared among all the instance using `gache` or `cache` package.
This bug was discovered in https://github.com/vdaas/vald/pull/501. 
This PR does not include the test code.
> [bug fix] Fix global cache in internal/cache/gache package

- go.sum
- internal/log/glg/glg_test.go
- internal/servers/server/option_test.go
I fixed below tests which are failed.
- `internal/log/glg/glg_test`
- `internal/servers/server/option_tset`
> fix failed test

- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_test.go
- pkg/agent/core/ngt/service/option.go
- pkg/agent/core/ngt/usecase/agentd.go
SSIA
further refactoring will be done with branch #556.
nothing.
nothing
> [agent-NGT] refactor pkg/agent/core/service using FOP

- internal/config/mysql.go
- internal/config/mysql_test.go
I added test case for `internal/config/mysql.go`.
> Add test for `internal/config/mysql.go`

- internal/file/watch/option_test.go
- internal/file/watch/watch.go
- internal/file/watch/watch_test.go
I added test case for `internal/file/watch`
> Add test for `internal/file/watch`

- internal/tls/tls_test.go
I fixed fails test of `tls` pacakge.
> Fix fails test of `internal/tls` pacakge

- internal/cache/gache/option.go
- internal/cache/gache/option_test.go
I added `internal/cache/gache/option` test and updated comment for each function.
> add internal/cache/gache/option test

- internal/cache/cache.go
- internal/cache/cache_test.go
- internal/cache/option.go
This PR implements internal/cache test case.
> add cache test

- internal/cache/gache/gache.go
- internal/cache/gache/gache_test.go
- internal/cache/gache/option_test.go
I added test of `internal/cache/gache/gache.go` and updated function comment about `internal/cache/gache/gache.go`.
Also, a bit fix in `internal/cache/gache/option_test.go`.
> add internal/cache/gache test

- internal/net/http/transport/option.go
- internal/net/http/transport/option_test.go
I updated `internal/net/http/transport/option` test with new template and added comment each external function and vals.
> add internal/net/http/transport/option test

- pkg/agent/core/ngt/service/option.go
from v0.0.47, when `agent.ngt.index_path` is empty, agent-ngt returns ` [FATAL]:	remove .: invalid argument` error and exit immediately.
the cause of this problem is the forgotten empty string check codes.
so i added a empty string check to WithIndexPath function.
nothing
nothing
> [bugfix] fix behavior when index path is empty

- pkg/agent/sidecar/service/observer/observer.go
- pkg/agent/sidecar/service/observer/observer_test.go
Current version v0.0.48, when agent-sidecar detects the changes in index files, it terminates itself immediately because the implementation is wrong.
In this PR, i've fixed it.
nothing.
nothing.
> [bugfix] fix agent sidecar behavior when index files are updated

- pkg/tools/cli/loadtest/assets/dataset.go
This PR implements generating random vector from gaussian distribution.
And this PR includes a little refactor of logging.
Nothing
Nothing
> Add gaussian random vector generation

- pkg/agent/internal/metadata/metadata.go
- pkg/agent/sidecar/service/observer/observer.go
Currently, this PR is just for debugging.
Do not merge.
Nothing.
Nothing.
> [patch] Add warn logging messages to agent-sidecar &  ignore io.EOF error when reading metadata.json

- internal/net/http/transport/roundtrip.go
- internal/net/http/transport/roundtrip_test.go
Author review required?
This PR implements the roundtrip test case.
This PR also fix the bug that it did not return `errors.ErrTransportRetryable` when the roundtrip success and the request is retryable.
Also this PR update the roundtrip logic that making the request terminated if the request is not retryable.
> Add internal roundtrip test code

- internal/worker/queue.go
- internal/worker/queue_test.go
There are 2 changes:
- create test of `internal/worker/queue`.
- update comments for each function of `internal/worker/queue`
And 1 bug fix:
- add `close(ech)` in `func(q) Starts() (<-chan error, error)`
> create internal/worker/queue test

- internal/db/kvs/redis/option.go
- internal/db/kvs/redis/option_test.go
I added test case for `internal/kvs/redis/option.go`.
> Add test case for `internal/kvs/redis/option.go`

- cmd/tools/cli/loadtest/sample.yaml
- pkg/tools/cli/loadtest/assets/loader.go
- pkg/tools/cli/loadtest/config/config.go
- pkg/tools/cli/loadtest/config/config_test.go
- pkg/tools/cli/loadtest/service/insert.go
- pkg/tools/cli/loadtest/service/insert_test.go
- pkg/tools/cli/loadtest/service/loader.go
- pkg/tools/cli/loadtest/service/loader_option.go
- pkg/tools/cli/loadtest/service/loader_option_test.go
- pkg/tools/cli/loadtest/service/loader_test.go
- pkg/tools/cli/loadtest/service/search.go
- pkg/tools/cli/loadtest/service/search_test.go
- pkg/tools/cli/loadtest/usecase/load.go
Refactor load test.
Nothing.
Nothing.
- Go Version: 1.14.2
- NGT Version: 1.11.4
> refactor load test

- Makefile
- internal/test/comparator/standard.go
- internal/worker/queue_mock_test.go
- internal/worker/worker.go
- internal/worker/worker_test.go
Author review required.
This PR includes the following changes:
- implements internal/worker test code
- create test/comparator package and implement go-cmp comparator
- missing `close(ech)` in `startJobLoop()`
> Add internal/worker/worker test

- internal/worker/queue_option.go
- internal/worker/queue_option_test.go
I added the test of `internal/worker/queue_option` and comments for each external var/func in `internal/queue_option`
> Add test of internal/worker/queue_option

- internal/worker/worker_test.go
This PR fix the internal/worker package testing fail due to the same var named in the same package.
> Fix internal/worker testing fail

- internal/compress/lz4_option.go
- internal/compress/lz4_option_test.go
- Add test for `internal/compress/lz4_option`
- Update comments for each external func/method/var in `internal/compress/lz4_option`
- Note: I could not cover the error pattern test in `WithLZ4Gob`, because `gobCompressor` is an empty struct and has no `options`.
> add internal/compress/lz4_option test

- docs/contributing/coding-style.md
This PR add a error checking section to the coding guideline.
> Coding guideline: Add error checking section

- internal/compress/zstd_option.go
- internal/compress/zstd_option_test.go
This PR implement internal/compress/zstd_option test
> Add internal/compress/zstd_option test

- docs/usecase/usage-example.md
I changed showing image path method in document.
if we use `[!xxx](../../image.png)`, converting image path for deploy public document will failed.
So, we have to use html based coding like `<img src="../../image.png" />`.
Note: you can check convert script at [here](https://github.com/vdaas/web/blob/master/Makefile) (convert section are `fix-image-path` and `fix-document-path`)
> change showing image method

- internal/compress/gzip_option.go
- internal/compress/gzip_option_test.go
I added test for `gzip_option.go`.
> Add test for `gzip_option`

- internal/errors/net.go
- internal/net/net.go
- internal/net/net_test.go
Author review required.
This PR implements test case for internal/net/net.go. 
This PR also include the following changes:
Bug fix:
- In ScanPorts(), when `start > end`, unexpected ports will be scanned
Fix: https://github.com/vdaas/vald/pull/615/files#diff-111853981bfa0f81d6c8945300daf97bR122-R124
- In ScanPorts(), when `end` is 65535, the `ScanPorts()` will never return due to golang bug or behavior
Fix: https://github.com/vdaas/vald/pull/615/files#diff-111853981bfa0f81d6c8945300daf97bR134
Ref: https://github.com/vdaas/vald/pull/615#discussion_r469117449
- In ScanPorts(), scanning ports in range, with some ports are failed but some success, the error will be returned instead of returning succeed ports 
Fix: https://github.com/vdaas/vald/pull/615/files#diff-111853981bfa0f81d6c8945300daf97 …
> Add internal/net test

- internal/db/rdb/mysql/option.go
- internal/db/rdb/mysql/option_test.go
- create test for `internal/db/rdb/mysql/option`
- update comment for each function in `internal/db/rdb/mysql/option`
> add internal/db/rdb/mysql/option test

- .github/workflows/dockers-image-scan.yml
Because Trivy doesn't escape "\X" in the description of [CVE-2019-20454](https://nvd.nist.gov/vuln/detail/CVE-2019-20454), the output SARIF file could not correctly be parsed.
CVE-2019-20454 is MEDIUM severity, so in this PR, just modifying the severity level of uploading SARIF file.
We can still find the lower severity vulnerabilities from Actions tab.
> Fix failing container scanning workflow: restrict the severities to upload

- internal/db/rdb/mysql/model.go
- internal/db/rdb/mysql/model_test.go
- create test for `internal/db/rdb/mysql/model.go`
- add comment each function/exported variables for `internal/db/rdb/mysql/model.go`
> add internal/db/rdb/mysql/model test

- internal/config/mysql.go
- internal/config/redis.go
- internal/db/kvs/redis/hook.go
- internal/db/kvs/redis/option.go
- internal/db/kvs/redis/option_test.go
- internal/db/kvs/redis/redis.go
- internal/db/kvs/redis/redis_mock_test.go
- internal/db/kvs/redis/redis_test.go
- internal/db/rdb/mysql/mysql.go
- internal/db/rdb/mysql/mysql_test.go
- internal/db/rdb/mysql/option.go
- internal/db/rdb/mysql/option_test.go
- internal/db/rdb/mysql/receiver.go
- internal/observability/metrics/db/kvs/redis/redis.go
- internal/observability/metrics/db/rdb/mysql/mysql.go
- internal/observability/trace/trace.go
- pkg/manager/backup/mysql/service/mysql.go
- pkg/manager/backup/mysql/service/mysql_test.go
- pkg/manager/backup/mysql/service/option.go
- pkg/manager/backup/mysql/usecase/backupd.go
- pkg/meta/redis/handler/grpc/handler.go
- pkg/meta/redis/handler/grpc/handler_test.go
- pkg/meta/redis/service/option.go
- pkg/meta/redis/service/redis.go
- pkg/meta/redis/service/redis_test.go
- pkg/meta/redis/usecase/meta.go
- Added DB metrics & traces
- Redis
- completed query total
- query latency
- completed pipeline total
- pipeline latency
- traces for query & pipeline
- MySQL
- completed query total
- query latency
- traces for query
- refactored service layer of meta-redis & manager-backup-mysql
because #626 contains tests for mysql/option.go, this PR should be updated after #626 merged into master branch.
#343 
in our k8s cluster.
> Add DB metrics & traces: Redis, MySQL

- internal/db/storage/blob/s3/reader/option.go
- internal/db/storage/blob/s3/reader/option_test.go
- add test for `internal/db/storage/blob/s3/reader/option`.
- add comment for each exported var/function for `internal/db/storage/blob/s3/reader/option`.
- refactor set option logic at `WithBackoffOpts`
> add internal/s3/reader/option test

- internal/db/storage/blob/s3/option.go
- internal/db/storage/blob/s3/option_test.go
I added test cases and refactored the `WithReaderBackoffOpts ` of option.go.
Refactor Content
- when opts equals nil, I fixed not to set nil. [related](https://github.com/vdaas/vald/pull/640/files#diff-f4591692602ee1377fff771677cdcf0fR104-R118)
- Add empty checking of FOP
=> ***author review required***
Related Ticket:
- https://github.com/vdaas/vald/projects/3#card-43770009
> Add test case for `s3/option.go`

- internal/compress/lz4.go
- internal/compress/lz4_test.go
- Test
- create test for `internal/compress/lz4`
- add comment for each exportable var/function for `internal/compress/lz4`
- Refactor
- change to use named return at `CompressVector()` because to get an `error` which will be cause at defer function.
> add internal/compress/lz4 test

- docs/contributing/coding-style.md
This PR update the coding guideline and create 2 new section to cover the following things:
- add example of implementation for functional option
- grouping type declaration 
- order of declaration
Please refer to this task ticket for this PR:
https://github.com/vdaas/vald/projects/3#card-44245759
> [Coding guideline] Add implementation and grouping section

- internal/net/tcp/dialer_test.go
- internal/worker/queue_option_test.go
> Fix failing test

- docs/contributing/coding-style.md
- internal/db/storage/blob/s3/writer/option.go
- internal/db/storage/blob/s3/writer/option_test.go
- internal/db/storage/blob/s3/writer/writer.go
- internal/errors/option.go
I added test cases for option.go and refactored option.go.
Refactor Contents
=> if we do not notice that the invalid value is set at startup and an error occurs based on `UploadWithContext ` after startup, we will lose our backup data.
```
str != "" 
↓
len(str) != 0
```
Related issue
- https://github.com/vdaas/vald/issues/585
**author review required**
> Add test case for `storage/blob/s3/writer/option`

- internal/db/rdb/mysql/mysql.go
- internal/errors/blob.go
- internal/errors/cassandra.go
- internal/errors/mysql.go
- internal/errors/redis.go
- pkg/meta/cassandra/service/cassandra.go
- pkg/meta/redis/service/redis.go
> [patch] bugfix error assertion

- Makefile
- dockers/agent/core/ngt/Dockerfile
passing CXXFLAGS to CGO_CXXFLAGS.
This is just for workaround for SIGILL on initialize phase of Agent-NGT
nothing
nothing
> pass CFLAGS, CXXFLAGS to NGT build command

- cmd/tools/cli/loadtest/sample.yaml
- pkg/tools/cli/loadtest/config/config.go
- pkg/tools/cli/loadtest/service/insert_test.go
- pkg/tools/cli/loadtest/service/loader.go
- pkg/tools/cli/loadtest/service/loader_test.go
- pkg/tools/cli/loadtest/service/search_test.go
- pkg/tools/cli/loadtest/usecase/load.go
fix load test using internal client and add option about resolve DNS 
#557 
Nothing.
> use internal client

- internal/compress/zstd.go
- internal/compress/zstd/zstd.go
- internal/compress/zstd_test.go
This PR includes the implementation of `compress/zstd.go` test cases.
It also include the changes to use the aliased object instead of the `zstd` package one, for example:
```
NewWriter(w io.Writer, opts ...zstd.EOption) (Encoder, error)
|
v
NewWriter(w io.Writer, opts ...EOption) (Encoder, error)
```
> Implement zstd test

- README.md
Add "AVX2 instructions" to Requirements section.
#685 
nothing
> add AVX2 to Requirements

- .devcontainer/devcontainer.json
- .github/workflows/dockers-dev-container-image.yml
- Makefile
- Makefile.d/docker.mk
- dockers/dev/Dockerfile
To enable GitHub Codespaces, I added .devcontainer/devcontainer.json & dockers/dev/Dockerfile.
Nothing.
Nothing.
> Add devcontainer

- charts/vald/templates/agent/daemonset.yaml
- charts/vald/templates/agent/deployment.yaml
- charts/vald/templates/agent/sidecar-configmap.yaml
- charts/vald/templates/agent/statefulset.yaml
This PR enables agent-sidecar on initContainer mode without enabling sidecar mode.
This is for a user who want not to overwrite backup files on S3 but want to load them onto the agents.
nothing
nothing
> Chart: agent-sidecar on initContainer mode can be deployed without enabling sidecar mode

- pkg/gateway/vald/handler/grpc/handler.go
> [patch] fix duplicated search result

- internal/db/storage/blob/s3/session/option.go
- internal/db/storage/blob/s3/session/session.go
- internal/db/storage/blob/s3/session/session_test.go
- internal/test/comparator/standard.go
This PR implements internal s3/session.go test.
It includes the refactoring on FOP base on the coding guideline
> Create s3/session test

- internal/db/storage/blob/s3/session/option.go
- internal/db/storage/blob/s3/session/option_test.go
I added test for `internal/db/storage/blob/s3/session/option.go`
> Add test for s3 session option

- internal/db/nosql/cassandra/option.go
- internal/db/nosql/cassandra/option_test.go
This PR implements cassandra option test.
It also includes the refactoring of FOP written in guideline.
> Cassandra option test (part 2)

- internal/backoff/backoff.go
- internal/backoff/backoff_test.go
- internal/net/grpc/client.go
- internal/net/grpc/pool/pool.go
- internal/net/http/transport/roundtrip.go
this PR include 2 feature for backoff
1. add context argument for backoff function, It will reduce cancel duration when backoff is timed out
2. add trace span for backoff
> add context argument for backoff & add trace span for backoff

- internal/db/rdb/mysql/mysql_test.go
I fixed the test case.
WHY
- https://github.com/vdaas/vald/projects/3#card-46712390
> Fix mysql test failure

- internal/core/ngt/ngt.go
> Add more effective Close function for internal/core

- pkg/gateway/vald/handler/grpc/handler.go
replace sync.Mutex lock map using sync.Map CAS operation
> [patch] change gateway vald's mutex lock

- pkg/gateway/vald/handler/grpc/handler.go
i fixed sorting codes for search results.
nothing
nothing
> fix search result sorting codes

- charts/vald/values.yaml
- docs/tutorial/agent-on-docker.md
- internal/core/ngt/ngt.go
- internal/core/ngt/option.go
add 3 new distance type support
- NormalizedAngle
- NormalizedCosine
- Jaccard
> [patch] add 3 new distance type support for agent-ngt

- assets/test/templates/common/function.tmpl
This PR fixes the testing template to include the writer handling.
> Fix testing template missing writer handling

- internal/db/nosql/cassandra/option.go
- internal/db/nosql/cassandra/option_test.go
This PR implements the test case for cassandra_option.
> Add cassandra option test (part 3)

- .github/conflint.yaml
- .github/kubelinter.yaml
- .github/workflows/reviewdog-k8s.yml
- Add kubeval-conflint to detect invalid type field in k8s manifests.
- Add kubelinter (without reviewdog)
nothing
nothing
> CI: Add reviewdog-k8s

- .github/workflows/reviewdog-markdown.yml
- docs/contributing/coding-style.md
I fixed coding style for mock and GitHub action.
WHY
- In Vald, There are a lot of dependencies between libraries.
As a result, the complexity of the test has increased, and it has become more difficult to determine whether or not to mock dependent objects and how to create mock.
- if there are a lot of review dog comment, we can not see pr page.  (review dog output warning because document has alot of example code. but we want to ignore it)
WHAT 
- Add  document for mock
- Add `TYPOGRAPY` to [action yaml](https://github.com/vdaas/vald/blob/master/.github/workflows/reviewdog-markdown.yml)
> Fix coding style for mock

- .github/conflint.yaml
- internal/db/nosql/cassandra/cassandra_mock.go
- internal/net/http/client/client.go
- internal/net/http/client/client_test.go
- internal/net/http/client/option.go
- internal/net/http/client/option_test.go
This PR implements http client option test. 
This PR also includes the following changes:
- [Test related] add the comparator implementation of `transport` to the `client_test.go` 
- [Refactor] Refactor the error returned from the option and handle it in `New()` 
> Create internal/net/http/client option test

- internal/db/storage/blob/s3/option.go
- internal/db/storage/blob/s3/s3.go
- internal/db/storage/blob/s3/s3_test.go
> Revise internal/db/storage/s3 tests in #837

- internal/net/http/json/json.go
- internal/net/http/json/json_test.go
This PR implements json pacakge test.
https://github.com/vdaas/vald/projects/3#card-48143027
> Add test case for json package

- internal/net/http/client/client.go
- internal/net/http/client/client_test.go
- internal/test/comparator/standard.go
This PR implements http client test.
> Add internal/net/http/client test

- dockers/operator/helm/Dockerfile
During deploy tests of #519, it is founded that helm-operator image is not built with helm schemas.
In this PR, I modified Dockerfile of helm-operator image to build schemas.
nothing
nothing.
> Build Helm schemas when building helm-operator image

- internal/net/grpc/client.go
- pkg/agent/core/ngt/service/ngt.go
this bug fix PR resolves 2 problems.
1. agent component blocking when duplicated data updates execution.
2. gateway nil pointer dereference, due to the persistent client connection lost.
> [patch] bugfix agent duplicated data update execution & gateway nil pointer depends on lost connectivity

- internal/errors/compressor.go
- internal/errors/compressor_test.go
I added test case for `internal/errors/compressor.go`.
And I refactored `internal/errors/compressor.go`.
- WHY
Whenever Errorf has no arguments other than a message, nil is returned.
https://github.com/vdaas/vald/blob/master/internal/errors/compressor.go#L40
https://github.com/vdaas/vald/blob/master/internal/errors/compressor.go#L44
- WHAT
Change from `Errorf` to `New`
***grammar check passed***
> Add test for internal/errors/compressor.go

- internal/errors/discoverer.go
- internal/errors/discoverer_test.go
I added the test cases for `internal/errors/discoverer.go` and comments.
***grammar check passed***
> Add test case for internal/errors/discoverer.go

- internal/errors/blob.go
- internal/errors/blob_test.go
This PR implements internal/errors/blob test
> Implement internal/errors/blob test

- charts/vald-helm-operator/crds/valdhelmoperatorrelease.yaml
- charts/vald-helm-operator/crds/valdrelease.yaml
There was a bug on updating ValdRelease & ValdHelmOperatorRelease resources by vald-helm-operator.
The cause is that there were no `status` field in the CRDs.
In this PR, I added `status` fields in the CRDs.
nothing
nothing
> Fix bug on updating status of VR & VHOR resources

- charts/vald/templates/agent/daemonset.yaml
- charts/vald/templates/agent/deployment.yaml
- charts/vald/templates/agent/priorityclass.yaml
- charts/vald/templates/agent/statefulset.yaml
- charts/vald/templates/discoverer/daemonset.yaml
- charts/vald/templates/discoverer/deployment.yaml
- charts/vald/templates/discoverer/priorityclass.yaml
- charts/vald/templates/gateway/vald/daemonset.yaml
- charts/vald/templates/gateway/vald/deployment.yaml
- charts/vald/templates/gateway/vald/priorityclass.yaml
- charts/vald/templates/manager/backup/daemonset.yaml
- charts/vald/templates/manager/backup/deployment.yaml
- charts/vald/templates/manager/backup/priorityclass.yaml
- charts/vald/templates/manager/compressor/daemonset.yaml
- charts/vald/templates/manager/compressor/deployment.yaml
- charts/vald/templates/manager/compressor/priorityclass.yaml
- charts/vald/templates/manager/index/daemonset.yaml
- charts/vald/templates/manager/index/deployment.yaml
- charts/vald/templates/manager/index/priorityclass.yaml
- charts/vald/templates/meta/daemonset.yaml
- charts/vald/templates/meta/deployment.yaml
- charts/vald/templates/meta/priorityclass.yaml
> [patch] Rename PriorityClass objects to contain namespace

- internal/errors/file.go
- internal/errors/file_test.go
I added the test cases for internal/errors/file.go and comments.
***passed grammar check***
> Add test case for internal/errors/file.go

- hack/license/gen/main.go
- internal/errors/grpc.go
- internal/errors/grpc_test.go
I added the test cases for internal/errors/grpc.go and comments.
And I modified the function name based on kevin-san's comment.
- https://github.com/vdaas/vald/pull/903#discussion_r551683532
***grammar check passed***
> Add test case for internal/errors/grpc.go

- internal/core/ngt/ngt.go
- internal/errors/meta.go
- internal/file/file.go
- internal/file/file_test.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/internal/metadata/metadata.go
This PR fix a bug when the agent sidecar try to open the `metadata.json` file and  if the file is not exists, the empty file will be created and causing agent failed to start.
> [patch] bugfix: do not create metadata file when create/append flag is not set for the agent/agent-sidecar

- internal/net/grpc/addrs.go
- internal/net/grpc/client.go
- internal/net/grpc/pool/pool.go
- pkg/gateway/lb/usecase/vald.go
add nill checking for grpc connection pool object
> bugfix add nil check for grpc connection pool objects in grpc/client.go

- internal/errors/http.go
- internal/errors/http_test.go
I added the test cases for internal/errors/http.go and comments.
grammar check passed
> Add test case for internal/errors/http.go

- docs/contributing/coding-style.md
- docs/contributing/unit-test-guideline.md
I created unit test guideline.
This guideline show the unit test strategies, and Vald unit test strategy.
And, I update coding guideline about unit test naming and input values which will be used fro unit test.
Grammar check is already done.
> create unit test guideline

- go.mod
- go.sum
- internal/net/grpc/interceptor/server/recover/recover_test.go
- internal/net/grpc/interceptor/server/trace/payload.go
- internal/net/grpc/interceptor/server/trace/payload_test.go
- k8s/metrics/profefe/clusterrole.yaml
- k8s/metrics/profefe/clusterrolebinding.yaml
- k8s/metrics/prometheus/clusterrole.yaml
- k8s/metrics/prometheus/clusterrolebinding.yaml
update rbac.authorization.k8s.io v1beta1 to v1
> update rbac.authorization.k8s.io v1beta1 to v1

- example/client/agent/main.go
- example/client/main.go
I fixed the invalid data loading code in example/main.go.
I've already mentioned about it a month ago, but it's not fixed yet.
https://github.com/vdaas/vald/projects/4#card-51586276
HDF5 formatted data of fashion-mnist has its data as float32 values. So it should be loaded as float32.
nothing
nothing
> Fix invalid data loading code in example

- internal/errors/mysql.go
- internal/errors/mysql_test.go
I added the test cases for internal/errors/mysql.go and comments.
And I fixed the test error for parallel testing and existing code to support parallel testing.
goroutine detecting error occurs when we use `t.Parallel` and `goleak.Verity(tt)` in the sub-test.
the goroutine generated by t.Parallel will also be detected by goleak.
So I Changed to use `goleak.IgnoreCurrent` method and ignore goroutines other than the function under test
**grammar check passed**
> Add test case for internal/errors/mysql.go

- .github/actions/docker-build/action.yaml
- .github/workflows/dockers-agent-ngt-image.yml
- .github/workflows/dockers-agent-sidecar-image.yml
- .github/workflows/dockers-backup-manager-cassandra-image.yml
- .github/workflows/dockers-backup-manager-mysql-image.yml
- .github/workflows/dockers-base-image.yml
- .github/workflows/dockers-ci-container-image.yml
- .github/workflows/dockers-dev-container-image.yml
- .github/workflows/dockers-discoverer-k8s-image.yml
- .github/workflows/dockers-gateway-backup-image.yml
- .github/workflows/dockers-gateway-filter-image.yml
- .github/workflows/dockers-gateway-lb-image.yml
- .github/workflows/dockers-gateway-meta-image.yml
- .github/workflows/dockers-gateway-vald-image.yml
- .github/workflows/dockers-helm-operator-image.yml
- .github/workflows/dockers-loadtest-image.yml
- .github/workflows/dockers-manager-compressor-image.yml
- .github/workflows/dockers-manager-index-image.yml
- .github/workflows/dockers-meta-cassandra-image.yml
- .github/workflows/dockers-meta-redis-image.yml
- Removed cache docker layers step from docker build workflows because it doesn't make builds so faster.
For agent-ngt builds,
| layer cache        | platforms       | duration      | log  |
|--------------------|-----------------|---------------|------|
| without            | amd64           | 4m38s         | https://github.com/vdaas/vald/actions/runs/513797778 |
| without            | amd64, arm64    | 24m0s         | https://github.com/vdaas/vald/actions/runs/513821869 |
| with (first time)  | amd64           | 7m2s          | https://github.com/vdaas/vald/actions/runs/513884200 |
| with (first time)  | amd64, arm64    | 23m55s        | https://github.com/vdaas/vald/actions/runs/513922698 |
| with (second time) | amd64 …
> Remove actions/cache to improve workflow speed / Refactoring docker-build workflows

- .github/actions/docker-build/action.yaml
- internal/errors/vald.go
- internal/errors/vald_test.go
I created the test for `internal/errors/vald.go` and also added comments for `internl/errors/vald.go`.
grammar check has passed.
> add test for internal/errors/vald

- internal/errors/option.go
- internal/errors/option_test.go
- k8s/external/cassandra/cassandracluster.yaml
I created  the new test for `internal/errors/option.go`.
Also, this PR includes below changes.
1. add comment each function or something external property.
2. refactor each `Error()` method due to panic.
grammar check is completed.
> create new test and refactor for errors/option

- internal/errors/ngt.go
- internal/errors/ngt_test.go
I added the test cases for internal/errors/ngt.go and comments and refactored implementation code.
- WHY
The output of following code is `ngt object uuid not found%!(EXTRA uint32=0)` .
https://github.com/vdaas/vald/blob/master/internal/errors/ngt.go#L85
- WHAT
I changed from `Errorf` to `New`
And I searched for code that uses this implementation. 
According to the results of the investigation, this fix had no effect.
https://github.com/vdaas/vald/search?q=ErrUUIDNotFound
The following is a handler that uses `insert` and` delete` in the above result, but it is not affected by the wording correction.
handler of `Insert`
- https://github.com/vdaas/vald/blob/5c914a2fa02fd0b128fbf24933523dd79d1a31ee/pkg/agent/core/ngt/handler/grpc/handler …
> Add test case for internal/errors/ngt.go

- internal/errors/net.go
- internal/errors/net_test.go
I added the test cases for internal/errors/net.go and comment.
And fixed code comments more clearly.
**grammar check passed**
> Add test case for internal/errors/net.go

- internal/errors/errors.go
- internal/errors/errors_test.go
I created the unit test for `internal/errors/errors.go`.
And refactored the functions of `internal/errors/errors.go` which are `ErrOptionFailed`, `ErrLoggingRetry`, and `ErrLoggingFailed`.
also, grammar check by grammarly is completed.
> create test for internal/errors/errors.go

- internal/errors/worker.go
- internal/errors/worker_test.go
This PR implements internal/errors/worker error.
Grammar check passed
> Implement internal/errors/worker test

- .github/chatops_permissions.yaml
This PR updates the chatops permission for @kevindiu to be able to use `/approve` chatops command
> Update chatops permission

- internal/errors/unit.go
- internal/errors/unit_test.go
I added the test for `internal/errors/unit.go`
grammar check has padded
> add test for internal/errors/unit

- internal/errors/tensorflow.go
- internal/errors/tensorflow_test.go
Wait for reply from @datelier
Added the test for `internal/errors/tensorflow.go` and the comment for each function.
grammar check has passed.
> add test for internal/errors/tensorflow

- internal/errors/runtime.go
- internal/errors/runtime_test.go
I added the test for `internal/errors/runtime.go` and add comment for each function.
> add test for internal/errors/runtime

- internal/errors/observability.go
- internal/errors/observability_test.go
I added the test cases for internal/errors/net.go and comment.
***grammar check passed***
> Add test case for internal/errors/observability.go

- .github/chatops_commands.md
- .github/workflows/chatops.yml
- .github/workflows/semver.yml
- CHANGELOG.md
- Makefile
- README.md
- hack/CHANGELOG.template.md
- Fix CHANGELOG.md
- Fix bug on Makefile that introduced in #826
- Update CHANGELOG template
- Update workflow & chatops for updating CHANGELOGs
- workflow ... just using PR body for changelog details when publishing a release
- chatops ... using `/changelog` command, the PR body will be replaced by the changelog detail template.
nothing
nothing
- Go Version: 1.15.8
> Fix invalid changelogs / update changelog workflows

- internal/errors/redis.go
- internal/errors/redis_test.go
This PR includes the following changes:
- add unit test for `internal/errors/redis`
- add comment for each function of `internal/errros/redis.go`
**Grammar check has passed.**
> add internal/errors/redis test

- internal/net/grpc/client.go
- internal/net/grpc/pool/pool.go
@datelier reports this bug in the commit c1addd22b6ff514161fc3df9915f5948ce145443  
when no target connection found gRPC client continue to discover and connect to target,
but there is no target Connect method returns Error and nil connection which makes nil-pointer panic for logging.
```
2021-03-02 15:00:37     [WARN]: recovered: %+v                                                                                                                                                               
stacktrace:                                                                                                                                                                                                  
%s runtime error: invalid memory address or nil pointer …
```
> bugfix nil pointer no target discovered

- internal/client/v1/client/discoverer/discover.go
- internal/net/grpc/client.go
> refactor discoverer client

- docs/tutorial/get-started.md
- example/client/agent/main.go
- example/client/main.go
- example/helm/values-scylla.yaml
Since #1050 , I added the removing index section for sample codes.
also, updated the `doc/tutorial/get-started.md` along with above changes.
I already confirmed these sample codes run well in my local environment (docker and k3d).
I appreciate it if you try `Get-Started` too.
#1050 
> add remove sample code for tutorial

- pkg/meta/cassandra/handler/grpc/handler.go
- pkg/meta/redis/handler/grpc/handler.go
- Added gRPC error details in meta Redis/Cassandra.
Reference:
- https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto
Nothing
Nothing
> Revise gRPC error statuses and details in meta (Redis/Cassandra)

- internal/db/rdb/mysql/mysql.go
- pkg/gateway/lb/handler/grpc/handler.go
- I've just found a typo in the code. -> fixed
- also, I've found an ambiguous function name in internal/db -> renamed.
nothing
nothing
> Fix error handling of SearchByID API in lb gateway

- internal/core/algorithm/ngt/util_test.go
I added test for `internal/core/algorithm/ngt/util.go`.
And I did not write godoc comment because the test target is not an unexported function.
thank you always.
> Add internal/core/algorithm/ngt/util.go test

- internal/backoff/backoff.go
- internal/backoff/backoff_test.go
I created the test for `internal/backoff`
> add internal backoff test

- internal/backoff/backoff_test.go
I updated the parameter due to sometimes failing tests about `internal/backoff` pkg.
> change params for passing test of internal/backoff

- internal/config/discoverer.go
- internal/config/discoverer_test.go
I added test for `internal/config/discoverer` and godoc comment.
**gramer check passed**
> Add internal/config/discoverer test

- pkg/gateway/backup/handler/grpc/handler.go
- pkg/gateway/lb/handler/grpc/handler.go
- pkg/gateway/meta/handler/grpc/handler.go
I found a bug when the load test was running.
the following are the bug details.
- nil pointer bug occurs when the config object is nil.
So I added validation logic to get config.
> Bug nil pointer error when config object is nil

- charts/vald-helm-operator/crds/valdrelease.yaml
- charts/vald/values.yaml
Fixed CRD schema. There're many typos in the values.yaml.
To prevent a problem like this, a check workflow for CRD schema & values.yaml will be introduced in #1107.
Nothing
Nothing
> Fix typo & missed schema definition

- internal/timeutil/time_bench_test.go
I added a benchmark for `timeutil/time.go` with table-driven.
```
goos: linux
goarch: amd64
pkg: github.com/vdaas/vald/internal/timeutil
cpu: Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
BenchmarkParse/t_1ns-7        	123051638	         9.610 ns/op	       0 B/op	       0 allocs/op
BenchmarkParse/t_1µs-7        	100000000	        10.14 ns/op	       0 B/op	       0 allocs/op
BenchmarkParse/t_1ms-7        	94272541	        12.00 ns/op	       0 B/op	       0 allocs/op
BenchmarkParse/t_1s-7         	100000000	        10.12 ns/op	       0 B/op	       0 allocs/op
BenchmarkParse/t_1m-7         	100000000	        11.35 ns/op	       0 B/op	       0 allocs/op
BenchmarkParse/t_1h-7         	95456136	        12.64 ns/op	       0 B/op	       0 …
```
> Add benchmark for internal/timeutil/time.go

- internal/config/redis.go
- internal/config/redis_test.go
I created the test for `internal/config/redis.go`.
grammar check has passed.
In `internal/config/redis.go`, I found `WithReadOnlyFlag()` is not used in `Opts()` method.
I'm not sure it is ok, please tell me how should I handle it ( @kpango or @rinx )
> create internal/config/redis test

- internal/safety/safety_bench_test.go
- internal/safety/safety_test.go
This PR implements safety benchmark test.
Here is the benchmark result.
```
goos: darwin
goarch: amd64
pkg: github.com/vdaas/vald/internal/safety
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkRecoverFunc/fn_return_error_func-12         	134723181	         9.512 ns/op	      24 B/op	       1 allocs/op
BenchmarkRecoverWithoutPanicFunc/fn_return_error_func-12         	55744567	        19.84 ns/op	      40 B/op	       2 allocs/op
BenchmarkRecoverWithoutPanicFunc/fn_panic_runtime_error_func-12  	   38184	     30841 ns/op	   18041 B/op	     206 allocs/op
BenchmarkRecoverWithoutPanicFunc/fn_panic_string_func-12         	   38880	     31979 ns/op	   16919 B/op	     191 allocs/op
BenchmarkRecoverWithoutPanicFunc/fn_panic_error_func-12 …
```
> Implement safety bench code

- internal/errors/errors.go
- internal/errors/errors_test.go
This PR fixes the nil pointer panic in errors.go Is function.
I also updated the test code for it.
> Fix nil pointer panic in errors.go Is()

- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/agent/core/ngt/handler/grpc/handler_test.go
- pkg/agent/core/ngt/handler/grpc/option.go
- pkg/agent/core/ngt/handler/grpc/option_test.go
- pkg/agent/core/ngt/usecase/agentd.go
This PR implements pkg/agent/core/ngt/handler/grpc/option test.
This PR also refactor the implement of the option to return error base on the guideline here.
https://github.com/vdaas/vald/blob/master/docs/contributing/coding-style.md#functional-option
> Implement pkg/agent/core/ngt/handler/grpc/option test

- internal/net/net.go
CodeQL detects these alerts.
- Redundant check for negative value
This PR fixes them.
Nothing
Nothing
> Fix CodeQL alerts: redundant check

- internal/errors/blob_test.go
- internal/errors/cassandra_test.go
- internal/errors/errors.go
- internal/errors/filter_test.go
- internal/errors/info_test.go
- internal/errors/net_test.go
- internal/errors/ngt_test.go
- internal/errors/option.go
- internal/errors/option_test.go
- internal/errors/redis.go
- internal/errors/redis_test.go
This PR includes:
- Remove nil check in `Error()` method in each `internal/errors` files.
- Add test for improve `internal/errors`'s test coverage
> remove nil check in Error() method in internal/errors

- Makefile.d/helm.mk
- dockers/ci/base/Dockerfile
This is a fix patch for the failed workflow.
https://github.com/vdaas/vald/runs/2619883011
After merging this, create release v1.1.0 again.
nothing
nothing
> Fix path to the yq binary

- pkg/agent/core/ngt/service/kvs/kvs.go
- pkg/agent/core/ngt/service/kvs/kvs_test.go
Signed-off-by: hlts2 hiroto.funakoshi.hiroto@gmail.com
I added test for `pkg/agent/core/ngt/service/kvs/test`.
and I added comment
**gramer check passed**
> Add config agent core ngt service kvs test

- pkg/agent/core/ngt/handler/grpc/option_test.go
- pkg/agent/core/ngt/service/vqueue/option.go
- pkg/agent/core/ngt/service/vqueue/option_test.go
- pkg/agent/core/ngt/service/vqueue/queue.go
- pkg/agent/core/ngt/service/vqueue/queue_test.go
I added test code for `pkg/agent/core/ngt/serice/vqueue/option.go` and godoc comment.
And I refactored based on a document of option error handling and fixed [ci fails error](https://github.com/vdaas/vald/runs/2596843952).
**gramer check passed**
> Add test for pkg/agent/core/ngt/service/vqueue/option

- internal/errors/lb.go
- internal/net/grpc/client.go
- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/agent/core/ngt/service/kvs/kvs_test.go
- pkg/gateway/lb/handler/grpc/handler.go
- pkg/gateway/lb/service/gateway.go
- pkg/gateway/meta/handler/grpc/handler.go
bugfix remove unneccessary error return
add grpc status code handling for backoff
> bugfix remove unneccessary error return & add grpc status code handling for backoff

- internal/client/v1/client/agent/core/client.go
- internal/client/v1/client/vald/vald.go
- internal/net/grpc/client.go
add single connection client for agent & vald
> add single connection client for agent & vald

- internal/db/kvs/redis/redis.go
In the current code, on Redis cluster client initialization,
https://github.com/vdaas/vald/blob/53de600129c3718c8412700974bdbf2d4b2cbfe2/internal/db/kvs/redis/redis.go#L231-L239
the `opt` argument of the `NewClient` option is ignored when `rc.newClient(ctx)` returns no error. However, it is important to use `opt` for client initialization because `opt.Addr` is passed when a new clusterNode instance is created.
https://github.com/go-redis/redis/blob/f83600d1a5ac092f27dc672b9dda7cf7adde8bc1/cluster.go#L176-L189
So here, remove the invalid initialization code to fix the problem that occurs when Redis cluster is used.
Nothing
Local cluster.
> Redis: Fix invalid cluster client initialization option

- go.mod
- go.sum
- internal/net/grpc/pool/pool.go
- internal/runner/runner.go
- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/discoverer/k8s/handler/grpc/handler.go
- pkg/discoverer/k8s/handler/grpc/option.go
- pkg/gateway/lb/handler/grpc/handler.go
- pkg/gateway/lb/handler/grpc/option.go
- pkg/gateway/meta/handler/grpc/handler.go
- pkg/gateway/meta/handler/grpc/option.go
add resource type infos to grpc error response
> add resource type infos to grpc error response

- charts/vald-helm-operator/crds/valdrelease.yaml
- charts/vald/templates/rebalancer/jobconfigmap.yaml
- charts/vald/values.yaml
- internal/config/rebalancer.go
- internal/config/sidecar.go
- internal/k8s/replicaset/replicaset.go
- pkg/agent/sidecar/service/observer/observer.go
- pkg/agent/sidecar/service/observer/option.go
- pkg/agent/sidecar/service/storage/storage.go
- pkg/agent/sidecar/usecase/sidecar/sidecar.go
- pkg/rebalancer/storage/controller/service/rebalancer.go
- pkg/rebalancer/storage/controller/service/rebalancer_option.go
- pkg/rebalancer/storage/controller/usecase/rebalanced.go
This PR change the recovery job create logic.
Instead of creating job instantly when detecting the statefulset decreased, 
we need to create the job when the decreased agent is completely finished and removed by k8s.
> [WIP] Refactor rebalancer controller: change recovery job logic

- cmd/filter/ingress/tensorflow/main_test.go
- go.mod
- go.sum
- hack/helm/schema/crd/main_test.go
- internal/client/v1/client/agent/core/client_test.go
- internal/client/v1/client/vald/vald_test.go
- internal/compress/mock_test.go
- internal/db/storage/blob/cloudstorage/cloudstorage_test.go
- internal/db/storage/blob/cloudstorage/option_test.go
- internal/db/storage/blob/cloudstorage/urlopener/option_test.go
- internal/db/storage/blob/cloudstorage/urlopener/urlopener_test.go
- internal/errors/errors_test.go
- internal/io/copy_test.go
- internal/net/grpc/status/status_test.go
- internal/observability/trace/status_test.go
- internal/servers/server/option_test.go
- internal/servers/server/server_test.go
- pkg/agent/core/ngt/service/ngt_test.go
- pkg/agent/core/ngt/service/vqueue/queue.go
- pkg/agent/core/ngt/service/vqueue/queue_test.go
- pkg/agent/core/ngt/service/vqueue/undeleted_index_map.go
- pkg/agent/core/ngt/service/vqueue/undeleted_index_map_test.go
- pkg/agent/core/ngt/service/vqueue/uninserted_index_map.go
- pkg/agent/core/ngt/service/vqueue/uninserted_index_map_test.go
- pkg/agent/sidecar/service/storage/option_test.go
- pkg/agent/sidecar/service/storage/storage_test.go
- pkg/gateway/meta/handler/grpc/option_test.go
> [bugfix] append timing of vqueue existing map

- cmd/filter/ingress/tensorflow/main_test.go
- hack/helm/schema/crd/main_test.go
- internal/client/v1/client/agent/core/client_test.go
- internal/client/v1/client/vald/vald_test.go
- internal/compress/mock_test.go
- internal/db/storage/blob/cloudstorage/cloudstorage_test.go
- internal/db/storage/blob/cloudstorage/urlopener/urlopener_test.go
- internal/io/copy_test.go
- internal/net/grpc/status/status_test.go
- internal/observability/trace/status_test.go
- internal/servers/server/server_test.go
- pkg/agent/core/ngt/service/ngt_test.go
- pkg/agent/core/ngt/service/vqueue/queue_test.go
- pkg/agent/core/ngt/service/vqueue/undeleted_index_map_test.go
- pkg/agent/core/ngt/service/vqueue/uninserted_index_map_test.go
- pkg/agent/sidecar/service/restorer/restorer_test.go
- pkg/agent/sidecar/service/storage/storage_test.go
- pkg/meta/cassandra/handler/grpc/handler_test.go
> format code

- internal/io/copy_test.go
> Fix CI error of copy test

- .github/workflows/chatops.yml
- Makefile
- docs/contributing/coding-style.md
- hack/git/hooks/pre-commit
Use [gofumpt](https://github.com/mvdan/gofumpt) as a default formatter.
Because **this change may cause many conflicts in the opened PRs**, please take care about merging it into master. Requesting reviews by all committer to make agreement about it
Nothing
Nothing
> Use gofumpt as a default formatter

- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/vqueue/queue.go
- pkg/gateway/lb/handler/grpc/handler.go
- WHY
In gateway, when the Update request is sent, the same time is used for Remove and Insert.
https://github.com/vdaas/vald/blob/master/pkg/gateway/lb/handler/grpc/handler.go#L1185
When checking IVExists of Vqueue, the existence is confirmed by the condition of [`vi < vec.date`](https://github.com/vdaas/vald/blob/929f29fd8a822c1167223416c96bb694662302a8/pkg/agent/core/ngt/service/vqueue/queue.go#L263), However, for a pod whose UUID has been removed, it will always be false when an insert is performed on that pod.
- WHAT
1. Fix to `vi <= vec.date` condition of GetVector, IVExits method agent/vqueue
2.  increment now of InsertMultiplue, DeleteMultiple (agent/ngt) 
2. increment now when lb gateway send Update request to agent
- Go …
> Fix time condition of agent & lb gateway

- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/vqueue/queue.go
- pkg/agent/core/ngt/service/vqueue/queue_test.go
In this PR, we fixed the following problems in vald agent:
1. When `saveIndex()` runs, the kvs index count and metadata.json index count may be different due to the timing of executing the `kvs.Len()`. We fixed to reference the kvs len variable to the same variable.
2. When creating index runs, the timing of removing from the kvs and the internal vqueue is different, which may cause the inconsistency problem of kvs&vqueue. We changed by passing the callback function to the vqueue to remove the kvs&vqueue data at the same time to avoid the above problem.
3. If the vector is updated during delete phase of createIndex operation, the vector will be inserted in insert phase of createIndex operation and the vector will be removed in the next createIndex operation.
- Docker …
> Bugfix index count problem of ngt

- pkg/agent/core/ngt/service/kvs/kvs_test.go
I fixed the fails test in rance condition.
when we test with `-race` flag, the error occurs in `agent/core/ngt/service/kvs/kvs_test.go`.
[x] added `sync.Mutex` in test code to prevent race condition.
> Fix fails test in race condition

- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/discoverer/k8s/handler/grpc/handler.go
- pkg/gateway/lb/handler/grpc/handler.go
This PR includes 2 chanees.
1. In Vald, when the gRPC Handler returns an error, we add a ResourceInfo so that the user can detect which resource had the error.
However, due to feedback that the Owner and Description in the ResourceInfo are redundant and do not make much sense, this PR removes the Owner and Description.
2. Removed unnecessary exists checking in MultiUpsert operation.
> remove owner and description info from resource info rich error for each grpc handler

- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/agent/core/ngt/service/ngt.go
Agent handler now uses timestamp configuration from API request users can control indexing order for each object.
In this PR, Multiple API is not supported for bypassing Timestamp. Because we have to make big internal API changes to support Multiple API.
>  add timestamp handler for agent timestamp controlled update

- pkg/agent/core/ngt/service/ngt.go
Problem: agent.GetObject API returns old indiced vector data when there is vector data with the same uuid in both kvsdb and vqueue.
Solution: In the Vald, vqueue is designed to hold the newest data rather than kvsdb, so I changed the implementation to verify the existence of vector data on GetObject API priority from vqueue and refer to kvsdb only if it does not exist in vqueue.
> [bugfix] agent.GetObject API returns old indexed vector problem instead of vqueue's new data

- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/gateway/lb/handler/grpc/handler.go
In some cases, the MultiUpserAPI only executes either MultiUpdate or MultiInsert depending on the index status, and in those cases, the Location is nil, causing panic.
In this PullRequest, in addition to fixing the above issues, the following issues are also mentioned and fixed.
New issue: In MultiUpsert, if only MultiUpdate or MultiInsert is used, it is better to execute without dispatching goroutine to avoid the possibility of panic and to be more efficient in terms of CPU resources. This is clear.
In this PR I have modified the following based on the problems mentioned above.
In the case of MultiUpsert on Gateway and Agent, the number of executions of MultiInsert and MultiUpdate should be checked, and if one of them is less than 0, only the …
> [bugfix] nil pointer panic in agent's MultiUpsert operation

- charts/vald/templates/agent/statefulset.yaml
The `mountPath` parameters of Agent StatefulSet templates were invalid.
This PR fixes the problem by using Helm template's `dir` function.
(It was forgotten to add PVC volume mount for init containers. This fixes it too.)
nothing
nothing
> Fix mount paths of Agent statefulset when using PVC template

- internal/core/algorithm/ngt/ngt.go
Changed agent core ngt to exclude the target directory itself from the directory cleanup process at the time of initialization so that only its contents are removed.
> change initial-index-directory removal logic

- tests/e2e/operation/multi.go
The MultiUpdate&MultiUpsert API internally checks the identity of the vectors to be updated by the LB Gateway, so it is important to remember that the number of responses is not always the same as the number of requested data.
The response includes an ID, so the client can check the order of the data based on the requested ID.
In this PR removed the length comparison test with seed data from the e2e multi-upsert/update.
and replace it to check size is not zero.
> fix e2e multi apis test code

- pkg/agent/core/ngt/service/kvs/kvs.go
- pkg/agent/core/ngt/service/kvs/option.go
- pkg/agent/core/ngt/service/ngt.go
This bug was found and reported by @rinx.
In PR #1384, it was reported that the Agent NGT Service does not start (blocking) only when KVSDB.Concurrency is set to 0.
It is not recommended to use your own errgroup in kvsdb from cancellation point of view.
However, since the number of goroutines to be invoked remains the same, we believe that using our own errgroup is not a problem from a performance point of view.
Therefore, in this PR, KVSDB will keep its own errgroup and use it for concurrent map search.
If the concurrency is less than or equal to 0, goroutines will be created without any limitation, and if the concurrency is greater than or equal to 1, the search will be performed using the number of goroutines. …
> remove global errgroup from kvsdb goroutine limitation

- internal/file/watch/watch_test.go
This PR fixes the failed test because of fsnotify v1.5 update.
This PR merge into non-master branch.
> Fix watcher test for fsnotify v1.5 update

- .github/workflows/format.yml
- Makefile
- hack/git/hooks/pre-commit
- internal/errgroup/group.go
- pkg/agent/core/ngt/service/ngt.go
The agent service closed kvsdb twice and performed duplicate close operations on the errgroup limitaiton channel, resulting in a runtime panic `close on closed channel` error.
This PR fixes these issues.
> [bugfix] resolve errgroup limitation channel close panic

- .github/workflows/e2e-chaos.yaml
- .github/workflows/e2e-deploy.yml
- .github/workflows/e2e-profiling.yml
- .github/workflows/helm-lint.yml
- .golangci.yml
- Makefile.d/functions.mk
- internal/core/algorithm/ngt/ngt.go
- internal/core/algorithm/ngt/ngt_test.go
- internal/errgroup/group.go
- internal/errors/lb.go
- internal/errors/ngt.go
- internal/errors/ngt_test.go
- internal/net/grpc/status/status.go
- internal/net/grpc/status/status_test.go
- pkg/agent/core/ngt/handler/grpc/handler.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_stateful_test.go
- pkg/gateway/lb/handler/grpc/handler.go
In this PR, I have fixed the problem of unexpected Unknown state when searching in Vald.
There were multiple problems that occurred in unison with this problem.
1. The Agent was returning a nil response or an Internal error response instead of an Empty response when returning zero search results (cases where there was no approximate vector in radius or during CreateIndex).
2. The pkg agent only checks for error status during CreateIndex, so it now correctly handles EmptySearch errors as well
3. The Code in internal/core/algorithm/ngt.Search does not decide whether a response is Empty or not, and only handles CGO Error as an error, so it is necessary to return Empty Error for Empty Response.
4. Merge Error in internal/errgroup had a problem. The …
> [bugfix] fix unknown status problems in search operation

- pkg/agent/core/ngt/handler/grpc/handler_test.go
Signed-off-by: Kosuke Morimoto <ksk@vdaas.org>
SSIA
> implement pkg handler exists test cases

- internal/core/algorithm/ngt/ngt.go
- internal/core/algorithm/ngt/ngt_test.go
- internal/core/algorithm/ngt/option.go
- internal/core/algorithm/ngt/option_test.go
- internal/net/control/control_darwin.go
- internal/net/control/control_other.go
- internal/net/control/control_unix.go
- internal/net/control/control_windows.go
- internal/runner/runner_race_test.go
- internal/singleflight/singleflight_test.go
- internal/timeutil/location/set_test.go
- tests/e2e/crud/crud_test.go
- tests/e2e/hdf5/hdf5.go
- tests/e2e/kubernetes/client/client.go
- tests/e2e/kubernetes/portforward/portforward.go
- tests/e2e/multiapis/multiapis_test.go
- tests/e2e/operation/doc.go
- tests/e2e/operation/multi.go
- tests/e2e/operation/operation.go
- tests/e2e/operation/stream.go
- tests/e2e/sidecar/sidecar_test.go
- tests/performance/max_vector_dim_test.go
I implemented the test for investigating the max dimension limit of `vald-agent-ngt` in any environment.
NGT can handle up to the `1 << 32 -1` dimension, but the real max dimension may not be the same depending on the environment.
This test can get the real max dimension for any environment.
For the time being, I set the limit of remaining free memory as 500MB to avoid such OOM kill or memory leak.
When the remaining free memory becomes 500MB or less, the test will finish and we can get the max bit in the environment.
In my environment (32GB Mem and free memory at the beginning is about 24GB), both results (max bit) are`29` bit.
> create investigation test of max dim for NGT

- pkg/agent/core/ngt/handler/grpc/handler_test.go
This PR implements pkg agent ngt multi insert test case (part 2).
I will create another PR to implement the remaining test cases.
> Implement multi insert test case for pkg agent handler - part 2

- pkg/agent/core/ngt/service/ngt.go
Signed-off-by: Kosuke Morimoto <ksk@vdaas.org>
SSIA
> fix update bug

- pkg/agent/core/ngt/handler/grpc/handler_test.go
This PR implements MultiInsert test for pkg agent handler.
Part 1: https://github.com/vdaas/vald/pull/1630 merged
Part 2:https://github.com/vdaas/vald/pull/1645 merged
Part 3: https://github.com/vdaas/vald/pull/1646 merged
Part 4: https://github.com/vdaas/vald/pull/1651 merged
- Go Version: 1.18
> Implement multi insert test case for pkg agent handler

- pkg/agent/core/ngt/service/ngt.go
The delete index function runs in the `multiUpdate`, but it does not return `NotFound` error when the index does not exist in `pkg/agent/core/ngt` layer.
It affects when vald agent standalone.
This PR changes the flag validation as true to return `NotFound` error.
In addition, I have fixed the `readyForUpdate` method.
When the error occurs in `GetObject()`, which `readyForUpdate` calls, `readyForUpdate` returns error.
- NGT Version: 1.14.5
> [bugfix] return NotFound error when delete fails in multiUpdate

- pkg/agent/core/ngt/handler/grpc/object.go
I fixed GetObject RPC and Exists RPC to return the same type of ID. (uuid)
The different ID type are returned when the user called GetObject RPC and Exists RPC.
> Different id returned when GetObject RPC and Exists RPC

- internal/test/data/request/object.go
- internal/test/data/request/object_test.go
- internal/test/mock/doc.go
- internal/test/mock/server_stream.go
- pkg/agent/core/ngt/handler/grpc/insert_test.go
This PR implements stream insert test for pkg/agent/ngt/handler.
It also implements server stream mock for testing.
- NGT Version: 1.14.5
> Implement stream insert test case

- internal/client/v1/client/discoverer/discover.go
- internal/client/v1/client/discoverer/option.go
- internal/net/grpc/client.go
I fixed code to get only backoff metrics of discover RPC.
There was a lot of backoff metrics in discover RPC before.
The current implementation included a backoff metrics that is not directly related to the RPC call.
https://github.com/vdaas/vald/blob/master/internal/client/v1/client/discoverer/discover.go#L221
> Fix to get only backoff metrics of discover RPC

- pkg/agent/core/ngt/handler/grpc/insert_test.go
> Remove unnecessary import path on pkg test

- pkg/agent/core/ngt/handler/grpc/object_test.go
> Implement agent handler getObject test case

- .github/workflows/e2e-chaos.yaml
- Makefile.d/tools.mk
SSIA
- https://github.com/chaos-mesh/chaos-mesh/releases/tag/v2.3.0
> fix chaos test

- docs/user-guides/upgrade-cluster.md
> add upgrade document

- internal/net/dialer_test.go
> Fix dialer test error

- .github/workflows/test-hack.yml
- .github/workflows/test.yml
- Makefile
- Makefile.d/test.mk
- dockers/ci/base/Dockerfile
> use gotestfmt instead of tparse

- internal/net/grpc/interceptor/server/metric/metric.go
v1.6.0 includes rpc status metrics bug, when RPC call succeeds metrics expose the state as Unknown it should be OK Status, so I changed it.
> [BUG] fix metrics bug

- internal/net/grpc/interceptor/server/metric/metric.go
- internal/net/grpc/interceptor/server/metric/metric_test.go
> Add test for attributesFromError method

- internal/circuitbreaker/breaker.go
- internal/circuitbreaker/breaker_test.go
- internal/circuitbreaker/counter.go
- internal/errors/circuitbreaker.go
As titled
The rate is not being used properly because the state is being changed immediately on success at half-open. Also, there is no function to limit the flow rate at half-open, so this should be added.
> bugfix success handling in the half-open and add flow control

- internal/client/v1/client/discoverer/discover.go
- internal/net/grpc/errdetails/errdetails.go
> fix string concat buffer overflow

- CHANGELOG.md
- docs/api/build_proto.md
> Fix document format

- Makefile
> install make dependencies before format command

- hack/license/gen/main.go
- internal/info/info.go
- internal/net/grpc/logger/logger.go
I have fixed the `RVV-A0003` reported by deepsource.
> Fix deepsource: RVV-A0003 exit inside non-main function

- hack/benchmark/src/singleflight/singleflight_bench_test.go
> fix deepsource: Unsafe defer of os.Close

- internal/servers/server/server_test.go
> fix deepsource: Potential slowloris attack

- internal/net/grpc/pool/pool_bench_test.go
- internal/net/grpc/server.go
- internal/net/grpc/server_test.go
> fix deepsource: Audit required: Insecure gRPC server

- dockers/agent/core/ngt/Dockerfile
- dockers/agent/sidecar/Dockerfile
- dockers/ci/base/Dockerfile
- dockers/dev/Dockerfile
- dockers/discoverer/k8s/Dockerfile
- dockers/gateway/filter/Dockerfile
- dockers/gateway/lb/Dockerfile
- dockers/manager/index/Dockerfile
- dockers/operator/helm/Dockerfile
- dockers/tools/cli/loadtest/Dockerfile
refactored Dockerfile 
There ware a lot of deepsource warning
> Fix deepsource: dockerfile warning

- .github/workflows/e2e-deploy.yml
As titled
e2e operator workflow has failed due to an invalid character.
> Bugfix: e2e operator workflow

- dockers/operator/helm/Dockerfile
- dockers/tools/cli/loadtest/Dockerfile
> Fix deepsource: DOK-SC2002, DOK-W1001  Useless cat and Multiple consecutive RUN

- hack/benchmark/assets/x1b/loader.go
- internal/conv/conv.go
- internal/net/grpc/grpcconns.go
- internal/strings/strings_benchmark_test.go
- pkg/agent/core/ngt/service/kvs/ou.go
- pkg/agent/core/ngt/service/kvs/uo.go
- pkg/agent/core/ngt/service/vqueue/undeleted_index_map.go
- pkg/agent/core/ngt/service/vqueue/uninserted_index_map.go
- pkg/discoverer/k8s/service/nodemap.go
- pkg/discoverer/k8s/service/nodemetricsmap.go
- pkg/discoverer/k8s/service/podmetricsmap.go
- pkg/discoverer/k8s/service/podsmap.go
- pkg/manager/index/service/indexinfos.go
> Fix deepsource: GSC-G103 Function call made to an unsafe package

- internal/cache/cache.go
- internal/cache/cache_test.go
- internal/cache/cacher/cacher.go
- internal/cache/gache/gache.go
- internal/cache/gache/gache_test.go
- internal/config/compress.go
- internal/config/compress_test.go
- internal/log/zap/zap.go
- internal/log/zap/zap_test.go
- internal/net/dialer.go
- internal/net/dialer_test.go
- internal/net/option.go
- internal/net/option_test.go
- internal/params/params.go
- internal/params/params_test.go
- pkg/agent/sidecar/service/storage/storage.go
I have fixed the `RVV-B0011`.
Fixing the issue, required changing the test code at the `internal/cache` package.
I have changed the `checkFunc` to ensure comparing `struct` which satisfies the `Cache` interface instead of using `go-cmp`.
The code is like:
```go
checkFunc := func(want, got Cache) error {
cw := reflect.ValueOf(want.(*cache))
cg := reflect.ValueOf(got.(*cache))
for i := 0 ; i < reflect.Indirect(cg).NumFiled(); i++ {
// compare
}
return nil
}
```
> Fix deepsource: RVV-B0011 exported function returning value of unexported type 

- internal/cache/cache.go
- internal/cache/cacher/cacher.go
> Fix deepsource: CRT-A0014 switch single case can be rewritten if or if-else

- tests/performance/max_vector_dim_test.go
I have fixed the using a defined variable instead of an undefined variable in `MaxDimensionTest`.
It means I use `the algorithm.MaximumVectorDimensionSize` instead of `ngt.VecotrDimensionSizeLimit`.
> Fix unsing undefined varibale at maxDimensionTest

- internal/backoff/backoff_test.go
- internal/circuitbreaker/manager_test.go
- internal/db/nosql/cassandra/cassandra_test.go
As titled.
the following are refactor targets.
- internal/backoff
- internal/circuitbreaker
- internal/db
> Fix deepsource: VET-V0008 Lock erroneously passed by value  internal/db, backoff, circuitbreaker

- internal/client/v1/client/filter/egress/client_test.go
- internal/client/v1/client/filter/ingress/client_test.go
> Fix deepsource: VET-V0008 Lock erroneously passed by value internal/client

- internal/info/info.go
> Fix deepsource: VET-V0008 lock erroneously passed by value info

- internal/observability/metrics/agent/sidecar/sidecar_test.go
- internal/singleflight/singleflight_test.go
- internal/test/comparator/comparators.go
> Fix deepsource: VET-V0008 Lock erroneously passed by value (internal/test, singleflight, observability)

- pkg/discoverer/k8s/service/discover_test.go
- pkg/discoverer/k8s/service/nodemap_test.go
- pkg/discoverer/k8s/service/nodemetricsmap_test.go
- pkg/discoverer/k8s/service/podmetricsmap_test.go
- pkg/discoverer/k8s/service/podsmap_test.go
I have fixed `VET-V0008` under the `pkg/discoverer` directory.
> Fix deepsource: VET-V0008 lock erroneously passed by value pkg/discoverer

- internal/test/data/request/insert_test.go
- pkg/gateway/lb/handler/grpc/handler.go
- pkg/gateway/lb/usecase/vald.go
- pkg/manager/index/usecase/indexer.go
> fix deepsource: [CRT-D0001] append possibly assigns to a wrong variable

- internal/net/dialer_test.go
- internal/net/grpc/addrs_test.go
- internal/net/grpc/client_test.go
- internal/net/grpc/grpcconns_test.go
- internal/net/http/client/client_test.go
I have fixed `VET-V0008` under the `internal/net` package.
> :recycle: Fix deepsource: VET-V0008 lock erroneously passed by value (internal/net)

- dockers/operator/helm/Dockerfile
I have fixed the new `DOK-W1001` warning.
> Fix deepsource: DOK-W1001 found consecutive run command

- internal/info/info_test.go
- internal/info/option_test.go
> Fix deepsource: VET-V0008 lock erroneously passed by value (internal/info test)

- hack/benchmark/assets/x1b/loader.go
- hack/benchmark/assets/x1b/loader_test.go
- internal/db/rdb/mysql/mysql.go
- internal/db/rdb/mysql/mysql_test.go
- internal/file/file.go
- internal/file/file_test.go
- internal/info/info.go
- internal/net/grpc/client.go
- internal/net/grpc/client_test.go
- internal/net/grpc/pool/pool.go
- internal/net/grpc/pool/pool_test.go
- internal/net/http/transport/roundtrip.go
- internal/net/http/transport/roundtrip_test.go
- internal/safety/safety.go
- internal/safety/safety_test.go
- internal/test/data/vector/gen.go
- internal/test/data/vector/gen_test.go
- internal/worker/queue.go
- internal/worker/queue_test.go
- pkg/gateway/lb/handler/grpc/handler.go
- pkg/gateway/lb/handler/grpc/handler_test.go
This PR includes the following changes.
- Rename unexported function if exported function with the same name exists 
- e.g. `search()` -> `doSearch()`, `open()` -> `doOpen()`
- Files are:
- hack/benchmark/assets/x1b/loader.go
- internal/file/file.go
- internal/net/grpc/client.go
- internal/net/grpc/pool/pool.go
- internal/net/http/transport/roundtrip.go
- internal/safety/safety.go
- internal/test/data/vector/gen.go
- pkg/gateway/lb/handler/grpc/handler.go
- Merge unexported function to the exported implementation (may contains logical changes)
- Files are:
- internal/db/rdb/mysql/mysql.go
- internal/worker/queue.go
- Fix/refactor test implementation 
- Some test case is merged from the unexported func test
- Fix golangci warning
- Fix `internal/net/http/transport/roundtrip.go` and test to …
> Fix deepsource: RVV-B0001 confusing naming of struct fields or methods

- internal/net/grpc/client_test.go
> Fix deepsource: VET-V0008 lock erroneously passed by value (internal/net/test)

- internal/net/grpc/option.go
> Remove deprecated functional option (internal/net/grpc)

- hack/benchmark/assets/x1b/loader.go
- hack/benchmark/assets/x1b/loader_test.go
- internal/file/file.go
- internal/file/file_test.go
- internal/net/grpc/client.go
- internal/net/grpc/client_test.go
- internal/net/grpc/pool/pool.go
- internal/net/grpc/pool/pool_test.go
- internal/test/data/vector/gen.go
- internal/test/data/vector/gen_test.go
This PR rename doXXX() worked in these 2 PRs.
- https://github.com/vdaas/vald/pull/1875/files
- https://github.com/vdaas/vald/pull/1844/files
Here is the summary of this PR:
- hack/benchmark/assets/x1b/loader.go  
- `doOpen()` -> `openFile()`
- internal/file/file.go
-  `doExists()` merged to `ExistsWithDetail()`
- `doWriteFile()` -> `writeFileSync()`
- `doJoin()` -> `joinFilePaths()`
- internal/net/grpc/client.go
- `doConnect()` -> `connectWithBackoff()`
- internal/net/grpc/pool/pool.go
- `doConnect()` -> `reconnectUnhealthy()`
- `doGet()` -> `getHelthyConn()`
- internal/test/data/vector/gen.go
- `doGenFloat32Vec()` -> `genF32Slice()`
- `doGenUint8Vec()` -> `genUint8Slice()`
- doXXX() not refactored:
- internal/file/file.go `doMove()`
- internal/net/http/transport/roundtrip.go …
> Refactor: rename doXXX()

- .github/workflows/reviewdog-markdown.yml
I have updated the workflow to check markdown files by language tools.
It is because the required checkpoint differs between document files and auto-generated markdown files.
I have changed the following:
- `md` files under the `apis/` and `chats/`: add ignore rules `CASING`
- except: No change
> Separate markdown check by reviewdog

- internal/net/grpc/pool/pool.go
When a connection status becomes IDLE, create a new connection and discard the old one.
If for some reason the component dropped (scale down ...etc.), the connection remains in an IDLE state at the origin (for a few minutes or so).
Due to the above, attempts to issue a request to a connection in the IDLE state will fail.
> Bugfix grpc status handling for idle connection

- docs/api/filter-gateway.md
- docs/api/insert.md
- docs/api/object.md
- docs/api/remove.md
- docs/api/search.md
- docs/api/status.md
- docs/api/update.md
- docs/api/upsert.md
This PR updates the output gRPC status code of API doc.
It also updates the status table to describe the newly added status code: CANCELLED on `docs/api/status.md`.
- Go Version: 1.20
> Update gRPC status code for API docs

- assets/test/templates/common/fill.tmpl
- assets/test/templates/common/function.tmpl
This PR update the gotests test template to exclude the type on the generated test file.
These types are warned in deepsource before, including the following type:
- sync.Map
- sync.Mutex
- sync.RWMutex
- sync.Once
- sync.Map
- sync.WaitGroup
- sync.Pool
- sync.Cond
- (other custom type contains lock)
Custom type exclusion will not be included in this PR.
You can verify this changes by using `make gotests/gen` command to generate the missing test impl and verify the changes using `git diff [file]`.
e.g. `git diff internal/circuitbreaker/manager_test.go`
```go
func Test_breakerManager_Do(t *testing.T) {
type args struct {
ctx context.Context
key string
fn  func(ctx context.Context) (interface{}, error)
}
type fields struct {
opts []BreakerOption
}
type want struct {
wantVal interface{}
err …
```
> Update test template to exclude deepsource warning

- docs/api/filter-gateway.md
- docs/api/update.md
- docs/api/upsert.md
I fixed documentaion typo disabled_balanced_update -> disable_balanced_update, an option name added in v1.7.3
Vald v1.7.3
> Fix documentaion typo disable_balanced_update

- .github/workflows/test-hack.yml
- Makefile.d/test.mk
- apis/grpc/v1/payload/interface.go
- hack/gorules/rules_test.go
- hack/gorules/testdata/tests.go
Fix gorule test and CI path.
I noticed that @rinx had 👎  reaction in PR #1790, so I've fixed it.
#1790 
> enable gorules

- internal/net/grpc/client.go
- internal/net/grpc/context.go
I have fixed the concurrency branch rule at the `internal/net/grpc/client.go`.
Thanks to #1953  , the backoff problem is resolved.
However, the concurrency branch rule affects the lb service.
Ref: https://github.com/vdaas/vald/blob/main/pkg/gateway/lb/service/gateway.go#L72-L86
So, I have fixed it with @hlts2 and @kpango .
> Bug fix: fix range concurrency branch rule

- .gitignore
@kevindiu added nvimlog file
It's unnecessary file for vald.
So I deleted it and add nvimlog to gitignore
> remove nvimlog

- .github/workflows/chatops.yml
This PR fixes the ChatOpts command `/gen-test` CI error.
Error log:
https://github.com/vdaas/vald/actions/runs/4592104780/jobs/8108855745
Since the Github action always triggered base on the main branch due to security reason, the changes of this PR will not be affected until this PR is merged.
After this PR is reviewed and merged, I will create another PR to test the ChatOpts command `/gen-test`.
> Fix ChatOpts /gen-test command error

- .github/workflows/chatops.yml
- Makefile.d/functions.mk
This PR include the following changes:
- Output error to chatops comment if `/gen-test` command failed
- Fix `/gen-test` chatops  command failure
I have tested the command on my local PC but for the CI to pass the error message to another step, I am not sure if it works or not since the changes will not be effective before this PR is merged.
> Output error log to ChatOpts comment

- internal/info/info.go
- internal/info/info_test.go
I have updated the `internal/info` test cuz `internal/info` has been updated by #2002
> Update internal/info test and add new case for coverage

- pkg/agent/core/ngt/service/kvs/kvs.go
- pkg/agent/core/ngt/service/kvs/kvs_test.go
- pkg/agent/core/ngt/service/kvs/ou.go
- pkg/agent/core/ngt/service/kvs/uo.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/vqueue/queue.go
- pkg/agent/core/ngt/service/vqueue/stateful_test.go
Add "index with timestamp" feature.
> Implement index with timestamp

- .github/workflows/chatops.yml
I have fixed the format (chatops) workflow.
`make license` should be run before `make format/go` to format all files, but the current workflow runs `make license` after `make format/go`.
So, I have fixed this issue in this PR.
> Fix CI chatops format workflow

- internal/net/grpc/stream_test.go
- internal/slices/slices_test.go
- internal/test/mock/server_stream.go
This PR implemented the generic function tests removed in this commit.
https://github.com/vdaas/vald/pull/2005/commits/baf038d8b8f8dce9f24122ded40369f19e7e8624
> Implement generic function tests

- .github/workflows/chatops.yml
This PR update the ChatOps `/format` command to output `**[FORMAT]** Nothing to format.` message if nothing is updated, to let user know the command is finished with success.
We cannot test this changes on PR unless we merged this PR. (Github action always use main branch to trigger CI)
> Chatops command /format output message if nothing updated

- .github/actions/e2e-deploy-vald-helm-operator/action.yaml
- .github/actions/e2e-deploy-vald/action.yaml
- .github/workflows/e2e-chaos.yaml
- .github/workflows/e2e-deploy.yml
- .github/workflows/e2e-max-dim.yml
- .github/workflows/e2e-profiling.yml
- Makefile.d/k8s.mk
To test helm templates changes, this PR changes E2E actions to use local charts on PR triggers.
This needs to be tested on `main` branch.
> Change E2E actions to use local charts on PR

- .github/actions/e2e-deploy-vald/action.yaml
- .github/workflows/e2e-chaos.yaml
- .github/workflows/e2e-deploy.yml
- .github/workflows/e2e-max-dim.yml
- .github/workflows/e2e-profiling.yml
- Makefile.d/k8s.mk
This PR partially fixes the regression of https://github.com/vdaas/vald/pull/2024 that all the e2e actions fail. With this PR, e2e actions work correctly except for `actions/e2e-max-dim`.
Fixed three things,
1. Wrong usage of `outputs`
2. Output accurate `POD_NAME`
3. Allow empty resources when executing `kubectl apply`
There will be another PR for `actions/e2e-max-dim`.
> Fix E2E actions on PR

- dockers/agent/core/ngt/README.md
- dockers/agent/sidecar/README.md
- dockers/ci/base/README.md
- dockers/dev/README.md
- dockers/discoverer/k8s/README.md
- dockers/gateway/filter/README.md
- dockers/gateway/lb/README.md
- dockers/manager/index/README.md
- dockers/operator/helm/README.md
- dockers/template.md
- dockers/tools/cli/loadtest/README.md
I have created README for each Docker image.
The purpose is to copy these documents to the `hub.docker` and makes a more user-friendly page for each Docker image.
All files have the `requirement` section for using each image.
However, I'm not sure about everything, please check out more carefully and review :pray:
> Create README for each docker image

- internal/net/http/transport/roundtrip.go
- internal/net/http/transport/roundtrip_test.go
I have updated the round trip retry condition, which removed MovePermanently from the retry condition.
Because it repeats the round trip with the original URL even though the redirect occurs.
We don't need to do a round trip if a redirect occurs because it will lead to the redirect destination.
None
> Update RoundTrip retry condition

- .deepsource.toml
> disable deepsource TestCoverage due to the Deepsource Coverage collect server timeout is too short for Vald testing

- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_test.go
As a preparation for https://github.com/vdaas/vald/pull/2034, extracted the process of initializing the backup folder and added some tests.
> refactor and add test for service/ngt.go

- CONTRIBUTING.md
- DEVELOPMENT.md
- Makefile
- docs/contributing/development.md
With https://github.com/vdaas/vald/pull/2032, our development experience with `devcontainer` has improved. This PR updates the documentation to reflect those changes.
> Add documentation for devcontiner

- pkg/agent/core/ngt/service/ngt.go
I have added the log for the save index operation.
https://github.com/vdaas/vald/issues/2039
> Add save index operation log

- internal/errors/agent.go
- internal/errors/errors.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_test.go
This PR fixes the regression that introduced  in https://github.com/vdaas/vald/pull/2034.
When `index_path` does not exist, it used to create the directory and https://github.com/vdaas/vald/pull/2034 made it an error. This PR reverts it.
> Fix to create index_path when it does not exists

- example/client/mirror/main.go
- example/helm/values.yaml
I have added the example code for Mirror Gateway because it will be needed in the tutorial documentation.
The following Example code is used as a reference for implementation.
- https://github.com/vdaas/vald/blob/feature/mirror-gateway-example/example/client/main.go
> Add mirror gateway example

- .prh.yaml
- CONTRIBUTING.md
> Fix typo of contribution guide

- docs/user-guides/observability-configuration.md
I have the following new section to the observability document
- simple command deploy
- cleanup
> Update observability document

- hack/tools/kvsdb/main.go
add decode kvsdb tool.
run example:
```
go run main.go --format XXX --path XXX --file XXX --timestamp-file XXX
```
> add decode kvsdb tool

- charts/vald/values/dev-broken-index-backup.yaml
- example/client/agent/main.go
- internal/observability/metrics/agent/core/ngt/ngt.go
- k8s/metrics/grafana/dashboards/01-vald-agent.yaml
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_test.go
This PR makes it possible to get the number of broken indexes as a metric. 
To check it's working, deployed vald to the local k3d with the settings of `dev-broken-index-backup.yaml`, and confirmed that the corresponding metric is correctly displayed on Grafana with the settings of `01-vald-agent.yaml`.
> Add broken index count metrics

- Makefile.d/k8s.mk
When running `make k8s/metrics/jaeger/deploy`, in my environment, executing `kubectl apply -f k8s/metrics/jaeger/jaeger.yaml` fails with errors below.
```
Error from server (InternalError): error when creating "k8s/metrics/jaeger/jaeger.yaml": Internal error occurred: failed calling webhook "mjaeger.kb.io": Post "https://jaeger-operator-webhook-service.default.svc:443/mutate-jaegertracing-io-v1-jaeger?timeout=10s": dial tcp 10.43.187.78:443: connect: connection refused
```
I watched logs, but I could not find the related error.
So it is my opinion, even if it checks the condition using `kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=jaeger-operator --timeout=60s`, the endpoint will not be ready depending on the performance of the computer.
Finally, in my environment, it …
> fix make k8s/metrics/jaeger/deploy failure

- docs/overview/component/README.md
- docs/overview/component/agent.md
- docs/user-guides/configuration.md
Add faiss agent documents.
- Faiss Version: 1.7.3
> Add Faiss Agent Docs

- internal/errors/agent.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_test.go
With this PR, the primary index will be backed up immediately when the agent fails to load it with CoW enabled. Before, it was backed up only when it fails to load both primary and old index.
> Add backup origin when CoW enabled and failed to load primary

- docs/user-guides/backup-configuration.md
> Add broken index backup document

- Makefile.d/k8s.mk
when I deployed the Jaeger component using `make k8s/external/cert-manager/deploy k8s/monitoring/deploy`, the deploy error occurred. 
```
until kubectl run busybox --restart=Never --image=busybox --rm -it -- wget -q -S --spider "https://jaeger-operator-webhook-service.default.svc:443/mutate-jaegertracing-io-v1-jaeger"; do sleep 1; done
If you don't see a command prompt, try pressing enter.
pod "busybox" deleted
pod default/busybox terminated (Error)
wget: note: TLS certificate validation not implemented
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer
pod "busybox" deleted
pod default/busybox terminated (Error)
If you don't see a command prompt, try pressing enter.
warning: couldn't attach to pod/busybox, falling back to …
```
> Fix jaeger operator wait logic

- .github/workflows/reviewdog.yml
- .golangci.yml
- Removed `gocritic` from golangci-lint because it was taking more than 30mins. Now it's just a few mins.
- Fix `depgurd` settings
- NGT Version: 2.0.13
> remove some linters to make ci faster

- Makefile.d/build.mk
- internal/core/algorithm/faiss/Capi.cpp
- internal/core/algorithm/faiss/Capi.h
> add faiss debug option

- internal/core/algorithm/ngt/ngt.go
- internal/core/algorithm/ngt/ngt_test.go
- pkg/agent/core/ngt/handler/grpc/search.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_stateful_test.go
When Search operation is taking a long time, it cannot be interrupted because the Context is not propagated,
I fixed to propagate context to Search operation.
- NGT Version: 2.0.13
>  Propagate context to Search operation.

- hack/benchmark/core/benchmark/strategy/search.go
- hack/benchmark/internal/core/algorithm/algorithm.go
- hack/benchmark/internal/core/algorithm/ngt/ngt.go
> Fix hack/benchmark search interface change

- internal/core/algorithm/ngt/ngt_test.go
I fixed index path of test case
The test failed because it was the same index path as the other test cases.
https://github.com/vdaas/vald/blob/main/internal/core/algorithm/ngt/ngt_test.go#L1807-L1832
> Fix ngt index path of test case

- .golangci.yml
- internal/cache/gache/option_test.go
- internal/core/algorithm/ngt/ngt_test.go
- internal/db/kvs/redis/redis_test.go
- internal/db/storage/blob/s3/option_test.go
- internal/db/storage/blob/s3/reader/option_test.go
- internal/net/dialer_test.go
- internal/test/data/request/insert_test.go
- internal/test/data/request/object_test.go
- internal/worker/queue_test.go
Use internal comparator interface instead of directly using go-cmp library.
> Use internal comparator instead of go-cmp

- .github/workflows/coverage.yml
- tests/performance/max_vector_dim_test.go
This PR fixes coverage CI test error.
- Add short flag skip for performance test
- Stop sending coverage to deepsource since we're not using it right now
> Fix coverage CI error

- .github/actions/setup-e2e/action.yaml
- .github/actions/setup-k3d/action.yaml
- .github/helm/values/values-chaos.yaml
- .github/workflows/e2e-chaos.yaml
- .github/workflows/e2e-code-bench-agent.yaml
- .github/workflows/e2e-deploy.yml
- .github/workflows/e2e-profiling.yml
This PR contains the following changes
- Execute chaos test via k8s ingress
- Enable Persistent volume to prevent index data loss
- Reduce the number of insert vector ( 10000 -> 5000)
- Improve gRPC client configurations for pod kill chaos scenario
> [CI]: Improve Chaos E2E test

- pkg/agent/core/ngt/handler/grpc/object.go
This PR removes error details from agent `GetObject` and `Exists` rpc error. This is required because the following performance issue was discovered while developing the `index correction` feature.
The issues is that when the client issues a large number of `GetObject` to the agent, the process of the http2 client huffman decoding the error detail from the header becomes a bottleneck in CPU processing, resulting in a decrease of QPS. Same goes to `Exists`.
Even if this error detail is removed, its impact is considered to be minor. This is because it only affects the use case of the agent standalone, which is limited. Also, even in that case, the client side can manage the error without details because it must be a unary request, not stream, to the agent.
- Docker …
> Refactor agent GetObject error not to wrap with details for performance issue

- Makefile.d/e2e.mk
I fixed a duplicate make command declaration.
- Go Version: 1.21.0
- Kubernetes Version: v1.28.1
> Fix duplicate make command

- internal/io/copy.go
- internal/io/copy_bench_test.go
Add CopyBuffer to copy.go
SSIA
- Go Version: 1.21.0
- Kubernetes Version: v1.28.1
> Add CopyBuffer to copy.go

- charts/vald/templates/gateway/mirror/configmap.yaml
- charts/vald/values.yaml
- internal/config/mirror.go
- pkg/gateway/mirror/handler/grpc/handler.go
- pkg/gateway/mirror/service/mirror.go
- pkg/gateway/mirror/service/mirror_option.go
- pkg/gateway/mirror/usecase/vald.go
I have integrated the `Advertise` logic into the `RegisterAPI`. With that, I have removed unnecessary parameters.
- Go Version: 1.21.1
> Returns all connection information in the registration rpc

- internal/errors/grpc.go
- pkg/gateway/lb/handler/grpc/handler.go
- pkg/gateway/lb/service/gateway.go
- tests/e2e/crud/crud_test.go
- tests/e2e/operation/operation.go
- tests/e2e/operation/stream.go
This PR implements `StreamListObject` to LB. No unit test added because its in the handler layer. E2E test added.
- Go Version: 1.21.1
> Add StreamListObject to LB

- pkg/gateway/mirror/handler/grpc/handler.go
- pkg/gateway/mirror/handler/grpc/handler_test.go
- pkg/gateway/mirror/handler/grpc/mock_test.go
I have changed the rollback implementation for the following RPCs. 
- Insert
- Update
- Upsert
- Remove
- RemoveByTimestamp
The previous implementation was to return to the previous cluster state, but now processing continues with the user's query as positive.
- Go Version: 1.21.1
> Add handler logic to continue processing

- .github/workflows/format.yml
- Makefile.d/helm.mk
This PR contains the following changes
- Add a job to check format differences in order to notice if formatting is forgotten before the merge.
- Fix helm-docs installation URL because ci-container builds fail
> Add job to check format difference

- .github/workflows/update-pull-request-and-issue-template.yml
- Makefile
- Makefile.d/dependencies.mk
This PR contains the following changes.
- Add update/template command to update pull_require_template and issue_template
- Use the above command in the actions workflow
- Update template when updated dependencies.
> Add make command to update template

- docs/user-guides/index-correction.md
> Add index correction document

- .github/workflows/format.yml
Format check job was successful, even if there were format differences.
> Enabled CI to fail in case of format differences.

- .github/workflows/dockers-index-creation.yml
- Makefile
- Makefile.d/build.mk
- Makefile.d/docker.mk
- cmd/index/job/creation/main.go
- cmd/index/job/creation/sample.yaml
- dockers/index/job/creation/Dockerfile
- internal/config/index_creation.go
- internal/config/index_creation_test.go
- internal/config/index_creator.go
- pkg/index/job/creation/config/config.go
- pkg/index/job/creation/config/config_test.go
- pkg/index/job/creation/service/indexer.go
- pkg/index/job/creation/service/indexer_test.go
- pkg/index/job/creation/service/mock_test.go
- pkg/index/job/creation/service/options.go
- pkg/index/job/creation/service/options_test.go
- pkg/index/job/creation/usecase/creation.go
- pkg/index/job/creation/usecase/creation_test.go
I added a component to execute the `createIndex` requests to agents.
This component will run as a k8s job in the future.
> Add implementation for create index job

- .github/workflows/dockers-dev-container-image.yml
- Makefile
- Makefile.d/minikube.mk
- Makefile.d/proto.mk
- dockers/dev/Dockerfile
To develop features related to volume cloning and snapshot, we need a local support of it. Unfortunately k3d does not support it but minikube does. So this PR adds minikube environment in makefile and devcontainer.
> Add minikube to create volume snapshot development environment locally

- charts/vald-helm-operator/crds/valdrelease.yaml
- charts/vald/values.schema.json
- charts/vald/values.yaml
The following error occurred when deploying using [dev-observability.yaml](https://github.com/vdaas/vald/blob/main/charts/vald/values/dev-observability.yaml).
```
coalesce.go:220: warning: cannot overwrite table with non table for vald.defaults.networkPolicy.custom.egress (map[])
coalesce.go:220: warning: cannot overwrite table with non table for vald.defaults.networkPolicy.custom.ingress (map[])
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
vald:
- defaults.networkPolicy.custom.egress: Invalid type. Expected: object, given: array
- defaults.networkPolicy.custom.ingress: Invalid type. Expected: object, given: array
```
This is due to a wrong schema in `networkPolicy`. ([schema …
> Fix invalid networkPolicy schema

- docs/api/mirror-gateway.md
- docs/overview/component/mirror-gateway.md
- docs/troubleshooting/mirror-gateway.md
- docs/user-guides/mirroring-configuration.md
This PR contains the following changes
- Add overview documentation of the continuous process
- Add troubleshooting document for mirror gateway status
- Delete `Advertise` RPC document
- Go Version: 1.21.1
> Update Mirror Gateway document

- internal/errors/corrector.go
- internal/errors/errors.go
- internal/errors/errors_test.go
- internal/net/grpc/stream.go
- pkg/index/job/correction/service/corrector.go
- pkg/index/job/correction/usecase/corrector.go
This PR updates `index correction` in two ways,
1. To report error to the usecase layer from service.Start, update error handling in the `correct` function. Also made changes in some cases not to continue processing but just stop processing and report errors.
2. Changed to call discoverer.Start outside of the correction goroutine to handle error chan.
> Add job error to report index correction error status

- .golangci.yml
A struct does not always have to have all of its fields initialized, and either way, I think we are ignoring this linter, so let's disable it.
> Disable exhaustruct

- .github/actions/docker-build/action.yaml
- Makefile
- Makefile.d/docker.mk
- dockers/agent/core/ngt/Dockerfile
- dockers/agent/sidecar/Dockerfile
- dockers/ci/base/Dockerfile
- dockers/dev/Dockerfile
- dockers/discoverer/k8s/Dockerfile
- dockers/gateway/filter/Dockerfile
- dockers/gateway/lb/Dockerfile
- dockers/index/job/correction/Dockerfile
- dockers/index/job/creation/Dockerfile
- dockers/index/job/save/Dockerfile
- dockers/manager/index/Dockerfile
- dockers/operator/helm/Dockerfile
- dockers/tools/cli/loadtest/Dockerfile
- hack/license/gen/main.go
I've added Docker buildkit registry cache for vald docker image builds.
and compress each docker image with zstd for more efficient start up performance.
>  Add docker buildx cache

- charts/vald-helm-operator/crds/valdrelease.yaml
- charts/vald/values.schema.json
> Update schema for readreplica

- apis/docs/v1/docs.md
- apis/grpc/v1/agent/core/agent_vtproto.pb.go
- apis/grpc/v1/discoverer/discoverer_vtproto.pb.go
- apis/grpc/v1/filter/egress/egress_filter_vtproto.pb.go
- apis/grpc/v1/filter/ingress/ingress_filter_vtproto.pb.go
- apis/grpc/v1/manager/index/index_manager_vtproto.pb.go
- apis/grpc/v1/payload/payload.pb.go
- apis/grpc/v1/payload/payload_vtproto.pb.go
- apis/grpc/v1/rpc/errdetails/error_details.pb.go
- apis/grpc/v1/rpc/errdetails/error_details_vtproto.pb.go
- apis/grpc/v1/vald/filter_vtproto.pb.go
- apis/grpc/v1/vald/insert_vtproto.pb.go
- apis/grpc/v1/vald/object_vtproto.pb.go
- apis/grpc/v1/vald/remove_vtproto.pb.go
- apis/grpc/v1/vald/search_vtproto.pb.go
- apis/grpc/v1/vald/update_vtproto.pb.go
- apis/grpc/v1/vald/upsert_vtproto.pb.go
> Apply make proto/all

- .github/workflows/_docker-image-scan.yaml
- .github/workflows/_docker-image.yaml
- .github/workflows/build-binaries.yml
- .github/workflows/build-protobuf.yml
- .github/workflows/chatops-help.yml
- .github/workflows/chatops.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/coverage.yml
- .github/workflows/detect-internal-config-changes.yml
- .github/workflows/dockers-image-scan.yml
- .github/workflows/e2e-chaos.yaml
- .github/workflows/e2e-code-bench-agent.yaml
- .github/workflows/e2e-max-dim.yml
- .github/workflows/e2e-profiling.yml
- .github/workflows/e2e.yml
- .github/workflows/format.yml
- .github/workflows/fossa.yml
- .github/workflows/helm-lint.yml
- .github/workflows/helm.yml
- .github/workflows/labeler.yml
- .github/workflows/reviewdog-hadolint.yml
- .github/workflows/reviewdog-k8s.yml
- .github/workflows/reviewdog-markdown.yml
- .github/workflows/reviewdog.yml
- .github/workflows/semver.yml
- .github/workflows/test-hack.yml
- .github/workflows/unit-test.yaml
- .github/workflows/update-protobuf.yaml
- .github/workflows/update-pull-request-and-issue-template.yml
I've updated buildkit version for vald docker image build.
And bump actions/checkout@v3 to v4.
> Update actions deps to fix cache issue

- .github/workflows/_docker-image-scan.yaml
- .github/workflows/dockers-image-scan.yml
- Makefile.d/docker.mk
> fix docker build for scanning

- docs/tutorial/get-started.md
- docs/user-guides/deployment.md
> Add caution sentence for deploy multi Vald clusters

- charts/vald/templates/agent/networkpolicy.yaml
- charts/vald/templates/agent/readreplica/networkpolicy.yaml
- charts/vald/templates/discoverer/clusterrole.yaml
- charts/vald/templates/discoverer/networkpolicy.yaml
- charts/vald/templates/gateway/filter/networkpolicy.yaml
- charts/vald/templates/gateway/lb/networkpolicy.yaml
- charts/vald/templates/manager/index/networkpolicy.yaml
- k8s/discoverer/configmap.yaml
- k8s/discoverer/deployment.yaml
- k8s/operator/helm/crds/valdrelease.yaml
> [bugfix] resolve duplicated cluster wide resources name problem

- internal/net/grpc/client.go
- internal/net/grpc/pool/pool.go
> [bugfix] gRPC pool connection health check for DNS Addr may fail during VIP member disconnection

- pkg/index/job/readreplica/rotate/service/rotator.go
> Add detailed log for readreplica rotator

- internal/observability/metrics/mem/mem.go
- k8s/metrics/grafana/dashboards/99-vald-agent-memory.yaml
- k8s/metrics/grafana/deployment.yaml
This PR includes the visualization for the metrics about agent memory implemented by #2161 and tiny bug fix for the metrics.
- #2161
> Add new grafana dashboard for agent memory metrics

- hack/license/gen/main.go
- hack/license/gen/main_test.go
This PR adds a logic to license/gen to skip symlink. This is required to avoid symlink files like `values.yaml` in vald-readreplica to become normal file on `make format`.
> Change license/gen to skip symlink

- docs/user-guides/capacity-planning.md
> Update capacity planning doc

- charts/vald-benchmark-operator/crds/valdbenchmarkjob.yaml
- charts/vald-benchmark-operator/schemas/job-values.yaml
- internal/config/benchmark.go
- pkg/tools/benchmark/job/service/object.go
In the following PR, we made a change to pass a query to `FilterConfig`. 
This caused a build error of the Continuous Benchmark Job, but I fixed it in this PR.
> Add Filter query configuration to Continuous Benchmark Job

- .github/workflows/dockers-release-branch-image.yaml
- charts/vald/values/multi-vald/dev-vald-with-mirror.yaml
Added rule to create docker images for the release branches of bench and mirror.
> Add release branch build for bench and mirror

- dockers/agent/core/ngt/Dockerfile
- dockers/agent/sidecar/Dockerfile
- dockers/ci/base/Dockerfile
- dockers/dev/Dockerfile
- dockers/discoverer/k8s/Dockerfile
- dockers/gateway/filter/Dockerfile
- dockers/gateway/lb/Dockerfile
- dockers/gateway/mirror/Dockerfile
- dockers/index/job/correction/Dockerfile
- dockers/index/job/creation/Dockerfile
- dockers/index/job/readreplica/rotate/Dockerfile
- dockers/index/job/save/Dockerfile
- dockers/manager/index/Dockerfile
- dockers/tools/benchmark/job/Dockerfile
- dockers/tools/benchmark/operator/Dockerfile
- dockers/tools/cli/loadtest/Dockerfile
The ENV ARCH was unnecessary, and the definition of unnecessary environment variables can have side effects, so removed them. Additionally, added the --platform option to Dockerfiles that were missing it.
> Stop using ENV ARCH and add --platform in Dockerfile

- .devcontainer/devcontainer.json
- .devcontainer/postAttachCommand.sh
SSIA
Also modified logic not to write zsh options twice in `.zshrc`.
> Refactor postAttachCommand

- .devcontainer/postAttachCommand.sh
- .github/workflows/issue-metrics.yaml
- hack/license/gen/main.go
> Change lincense/gen/main.go to skip shebang

- internal/net/grpc/pool/pool.go
> bugfix grpc ip direct connection status check

- dockers/dev/Dockerfile
> Add stern and telepresence

- .github/workflows/e2e-max-dim.yml
- .github/workflows/e2e.yml
- Makefile.d/k8s.mk
- tests/e2e/crud/crud_test.go
https://github.com/vdaas/vald/pull/2303 changed agent name from `vald-agent-ngt` to `vald-agent`, and it broke the e2e tests. This PR fixes it.
- Go Version: 1.21.6
> Fix e2e regressions

- .github/workflows/_docker-image.yaml
- hack/license/gen/main.go
> Refactor ignore rule

- Makefile.d/tools.mk
- dockers/dev/Dockerfile
Current nightly devcontainer cannot be opened with vscode devcontainer extension. This PR fixes the issue.
I don't know why it's trying to import buildcahe and fail when there is no buildcache because it's the first try. But should be fine in the main branch. Also it should not be a big problem since it succeeds to publish image anyway.
https://github.com/vdaas/vald/actions/runs/7826490855/job/21368714853?pr=2335#step:9:5209
> Revert dev Dockerfile to use official devcontainer image

- dockers/agent/core/faiss/Dockerfile
- dockers/agent/core/ngt/Dockerfile
- dockers/agent/sidecar/Dockerfile
- dockers/ci/base/Dockerfile
- dockers/dev/Dockerfile
- dockers/discoverer/k8s/Dockerfile
- dockers/gateway/filter/Dockerfile
- dockers/gateway/lb/Dockerfile
- dockers/gateway/mirror/Dockerfile
- dockers/index/job/correction/Dockerfile
- dockers/index/job/creation/Dockerfile
- dockers/index/job/readreplica/rotate/Dockerfile
- dockers/index/job/save/Dockerfile
- dockers/manager/index/Dockerfile
- dockers/operator/helm/Dockerfile
- dockers/tools/benchmark/job/Dockerfile
- dockers/tools/benchmark/operator/Dockerfile
- dockers/tools/cli/loadtest/Dockerfile
> Investigate component build error

- .golangci.yml
- internal/config/blob.go
- internal/config/circuitbreaker.go
- internal/config/faiss.go
- internal/config/index.go
- internal/config/net.go
- internal/config/ngt.go
- internal/config/server.go
- internal/config/sidecar.go
- internal/config/tls.go
- internal/config/transport.go
- internal/k8s/vald/benchmark/api/v1/job_types.go
- pkg/tools/cli/loadtest/config/config.go
- Fixed `.golangci-lint.yaml` for updated style.
- Apply `tagalign` to fix all the warnings
- Go Version: 1.21.6
> Fix golangci-lint config and apply tagalign

- .github/actions/setup-helm/action.yaml
As titled
v4.0.0 has been released, but a shortcut version like v4 has not yet been released yet.
> Fix setup-helm version

- .github/actions/scan-docker-image/action.yaml
> Change docker scan timeout longer

- .github/workflows/backport.yml
> improve Backport Pull Request Title & Description Quality

- .github/workflows/backport.yml
> [bugfix] fix backport github value bypass failure

- .github/workflows/update-protobuf.yaml
Because the client does not support two version deploy, only the manual dispatch method will be enabled.
> Enable only manual dispatch for protobuf update

- internal/k8s/client/client.go
- internal/test/mock/k8s/client.go
- pkg/agent/core/ngt/service/export_test.go
- pkg/agent/core/ngt/service/ngt.go
- pkg/agent/core/ngt/service/ngt_test.go
- pkg/agent/core/ngt/service/option.go
- pkg/agent/core/ngt/usecase/agentd.go
> Add tests for index information export

- .github/actions/determine-docker-image-tag/action.yaml
- .github/actions/docker-build/action.yaml
- Makefile.d/docker.mk
It was overlooked in the verification environment that the `nightly` image was not created at the time of the merge to `main`, so I fixed this 🙏 🙏 
https://github.com/vdaas/vald/pull/2410
> Update build rule for nightly image

- .github/actions/docker-build/action.yaml
When testing with other PR, I noticed a problem with the vald version, so I fixed it
The following is the area where there is a problem.
> Fixed issue with updating vald version information at build time

- charts/vald/templates/index/job/creation/configmap.yaml
- charts/vald/templates/index/job/save/configmap.yaml
- pkg/index/job/creation/service/indexer.go
- pkg/index/job/creation/service/indexer_test.go
- pkg/index/job/save/service/indexer.go
- pkg/index/job/save/service/indexer_test.go
In the previous implementation, it was possible to set a DNS A record to a job.
However, since only IP was enabled internally, even if a DNS A record was set, it could not be properly connected.
Therefore, I will modify the logic so that when a user specifies a target address (`A record:port` or `ip:port`), it will be preferentially selected.
> Fix index job logic to pass DNS A record

- Makefile.d/docker.mk
The `EXTRA_ARGS` is passed on the CI side, but the passed `EXTRA_ARGS` is disabled because it is internally overwritten.
> Bugfix docker build command for ci-container

- charts/vald-benchmark-operator/crds/valdbenchmarkjob.yaml
- charts/vald-benchmark-operator/crds/valdbenchmarkscenario.yaml
- k8s/tools/benchmark/operator/crds/valdbenchmarkjob.yaml
- k8s/tools/benchmark/operator/crds/valdbenchmarkscenario.yaml
- pkg/tools/benchmark/operator/service/operator.go
- pkg/tools/benchmark/operator/service/operator_test.go
I have fixed the `benchmark-operator` recreates `BenchmarkJobResource`  following `BenchmarkScenarioResource(VBJR)` even though the applied VBJR status is `Completed` when an operator reboots.
I have changed the default CR status to `Available` and fixed the operator's reconciliation logic to resolve this issue.
The operator will create child resources only if CRD status is `Available`.
```mermaid
stateDiagram-v2
[*] --> Available: Apply Scenario
Available --> Healthy: Create Benchmark Job Resource
Healthy --> Completed: If ALL benchmarkJobResource are completed
Completed --> [*]
```
> Bugfix recreate benchmark job when operator reboot

- Makefile
- dockers/agent/core/ngt/Dockerfile
Fix arm build failure. It is first aid and it is necessary to resolve its core problem on NGT.
> add extra flags for NGT build phase

- .github/workflows/backport.yml
The workflow status for backport PR creation was `Pending`, although we have approved the Forked PR.
It may be due to the approve being removed at the moment the PR is closed, so I fix the workflow trigger.
- Change workflow trigger from `closed` event to `push` event
> Fix workflow trigger for backport pr creation

- .github/workflows/_release-pr.yml
The `actions/backport/main` label should be added to the [release PR](https://github.com/vdaas/vald/pull/2360) created by the vdaas-ci bot. 
But since there is a possibility of forgetting to add it, I will fix it to automatically add the `actions/backport/main` label.
> Automatically add backport main label for release-pr

- .github/workflows/dockers-example-client-image.yaml
- Makefile.d/docker.mk
SSIA
- Vald Version: v1.7.13
- Go Version: v1.23.2
- Rust Version: v1.81.0
- Docker Version: v27.3.1
- Kubernetes Version: v1.31.1
- Helm Version: v3.16.2
- NGT Version: v2.2.4
- Faiss Version: v1.9.0
> Fix bind DOCKER_OPTS option

- tests/e2e/crud/crud_test.go
- tests/e2e/operation/operation.go
SSIA
- Vald Version: v1.7.13
- Go Version: v1.23.2
- Rust Version: v1.81.0
- Docker Version: v27.3.1
- Kubernetes Version: v1.31.1
- Helm Version: v3.16.2
- NGT Version: v2.2.4
- Faiss Version: v1.9.0
> fix delete target agent pod at index correction

- internal/config/corrector.go
- internal/config/index_creation.go
- internal/config/index_deleter.go
- internal/config/lb.go
- Reverts the part of #2938 
- nil and default object are different settings
- we need to investigate the diff later
- Vald Version: v1.7.16
- Go Version: v1.24.4
- Rust Version: v1.87.0
- Docker Version: v28.2.2
- Kubernetes Version: v1.33.1
- Helm Version: v3.18.2
- NGT Version: v2.4.2
- Faiss Version: v1.11.0
> [Bugfix] Do not bind when object is nil
