vdaas/vald

Makefile

I fixed some irregular patterns in Makefile.

:rotating_light: Fix lint.

---

.github/workflows/reviewdog.yml

@kpango Could you add a "github-token" to secrets of this repository? ( I couldn't access to that page.)
ref: https://github.com/reviewdog/action-misspell

:construction_worker: Add golangci-lint

---

.github/workflows/reviewdog.yml

add the disable option to golangci-lint.

:green_heart: Disable gochecknoglobals linter

---

.github/workflows/e2e-bench-agent-stream.yml

:green_heart: Add e2e bench action (agent-stream)

---

Makefile.d/bench.mk
hack/e2e/benchmark/gateway/vald/vald_bench_test.go
hack/e2e/benchmark/internal/dataset/dataset.go
hack/e2e/benchmark/internal/starter.go

stream benchmark does not move.

implement gateway benchmark

---

.github/workflows/dockers-meta-cassandra-image.yml
Makefile
Makefile.d/docker.mk
README.md
assets/ddl/meta/cassandra/ddl.cql
cmd/meta/cassandra/main.go
cmd/meta/cassandra/sample.yaml
dockers/meta/cassandra/Dockerfile
internal/config/cassandra.go
internal/db/nosql/cassandra/cassandra.go
internal/db/nosql/cassandra/delete.go
internal/db/nosql/cassandra/get.go
internal/db/nosql/cassandra/list.go
internal/db/nosql/cassandra/option.go
internal/db/nosql/cassandra/set.go
internal/errors/cassandra.go
pkg/meta/cassandra/config/config.go
pkg/meta/cassandra/service/cassandra.go
pkg/meta/cassandra/usecase/meta.go

Co-authored-by: autopp <autopp.inc@gmail.com>

:sparkles: Add meta-cassandra

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/security_issue_report.md

:pencil: Revise issue template

---

.github/workflows/labeler.yml

I added code sizez label.
eg) size/XL, size/XXL, size/XXXL
Source size is based on the following link
https://github.com/apps/pull-request-size

fix code size

---

go.mod
go.sum
internal/net/grpc/client.go
pkg/gateway/vald/service/gateway.go

Vald's grpc persistent uses Disconnect & Connect method for each health check.
I added reconnect method for internal usage, client will be check by Monitor routines and when client execute Do, Range, RangeConcurrent, each process will be check their connection health
none
none

change grpc persistent client re-connection logic

---

internal/net/grpc/client.go

I found below error, so I fixed this error.
```
untime: goroutine stack exceeds 1000000000-byte limit
fatal error: stack overflow
runtime stack:
runtime.throw(0xcc9a8d, 0xe)
runtime/panic.go:774 +0x72
runtime.newstack()
runtime/stack.go:1046 +0x6e9
runtime.morestack()
runtime/asm_amd64.s:449 +0x8f
goroutine 1 [running]:
google.golang.org/grpc.(*connectivityStateManager).getState(0xc0001880e0, 0x0)
google.golang.org/grpc@v1.26.0/clientconn.go:431 +0xaf fp=0xc0205a4360 sp=0xc0205a4358 pc=0xa09b9f
google.golang.org/grpc.(*ClientConn).GetState(...)
google.golang.org/grpc@v1.26.0/clientconn.go:506
github.com/vdaas/vald/internal/net/grpc.(*gRPCClient).isHealthy(0xc0000b4be0, 0xc000428e00, 0xa09b70)
github.com/vdaas/vald@/internal/net/grpc/client.go:310 +0x68 fp=0xc0205a4380 sp=0xc0205a4360 …
```

[bugfix] fix recursion error

---

.github/workflows/coverage.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/e2e-bench-agent-stream.yml
.github/workflows/reviewdog.yml
Makefile
Makefile.d/bench.mk
Makefile.d/docker.mk
dockers/ci/base/Dockerfile

In this PR, I introduce a Docker image for CI builds / tests.
It contains pre-build NGT, libhdf5, and graphviz. Currently, they are required by benchmark codes.
Nothing.
Nothing.
Plesase see the check details below.

:whale: Add CI-container image

---

.github/workflows/dockers-ci-container-image.yml

:green_heart: Fix docker push commands

---

pkg/gateway/vald/handler/grpc/handler.go

Fix ranking bug

---

pkg/gateway/vald/handler/grpc/handler.go

fix ranking

---

.github/workflows/chatops.yml

I added bot comment step to ChatOps workflow.
It will be like this:
Nothing.
In my private sandbox repository.

Add bot comment to ChatOps workflow

---

internal/safety/safety_test.go

I fix to conform to guidelines.

fix case for `internal/safety` 

---

internal/net/http/routing/middleware_mock_test.go
internal/net/http/routing/option_test.go
internal/net/http/routing/router_test.go

I added test case for `internal/net/http/routing`
I have confirmed that go test is passed.

added test case for `internal/net/http/routing`

---

internal/compress/gob_option.go
internal/compress/gob_test.go
internal/compress/gzip.go
internal/compress/gzip_option.go
internal/compress/gzip_test.go
internal/compress/lz4.go
internal/compress/lz4_option.go
internal/compress/lz4_test.go
internal/compress/zstd.go
internal/compress/zstd_option.go
internal/compress/zstd_test.go
internal/config/compress.go
pkg/manager/compressor/service/compress.go
pkg/manager/compressor/service/compress_option.go
pkg/manager/compressor/usecase/compressord.go

I added compression level option.
Nothing.
Nothing.

Add compression_level option

---

.golangci.yml
go.mod
go.sum
internal/config/cassandra.go
internal/db/nosql/cassandra/cassandra.go
internal/db/nosql/cassandra/option.go
internal/servers/option_test.go
internal/servers/servers_mock_test.go
internal/servers/servers_test.go
pkg/manager/backup/cassandra/service/cassandra.go
pkg/meta/cassandra/service/cassandra.go

add cassandra pool config

---

pkg/manager/compressor/service/compress.go
pkg/manager/compressor/usecase/compressord.go

I forgot to pass the config parameter. :bow:
Nothing.
In my local KinD.

Fix compression level config

---

internal/net/http/transport/option_test.go
internal/net/http/transport/roundtrip_mock_test.go
internal/net/http/transport/roundtrip_test.go

I added test case for internal/net/http/transport
I have confirmed that go test is passed.

test case for `internal/http/transport`

---

.github/CHATOPS_OWNERS
.github/workflows/chatops.yml

I added `/approve` command of ChatOps.
I added `/add-contributors` command of ChatOps.
I added `/label` command of ChatOps.
Nothing.
Nothing.

Add /approve, /add-contributors, and /label command

---

internal/backoff/backoff_test.go
internal/backoff/option.go
internal/backoff/option_test.go

I added test code of internal/backoff.
I have confirmed that go test is passed.

test case for `internal/backoff`

---

internal/errors/errors.go
internal/log/glg/glg.go
internal/log/glg/glg_test.go
internal/log/log.go
internal/log/retry/retry.go

Loggin error handling

---

hack/benchmark/core/ngt/gongt_bench_test.go
hack/benchmark/internal/assets/dataset.go
hack/benchmark/internal/assets/loader.go

change type from float64 to float32
in #180 changed type float64 to float32, so this PR has fix type benchmark codes.
#180 
fix only benchmarks

fix change type float64 to float32

---

vald/templates/_helpers.tpl
vald/templates/gateway/vald/ing.yaml
vald/values.yaml

- I've just added `servicePort` field to server config.
- Revise ingress apiVersion.
Nothing.
executed `helm template` in my local environment.

Add servicePort config to Helm charts

---

internal/rand/rand_test.go

I added test case for `internal/rand`.

test case for `internal/rand`

---

hack/benchmark/e2e/external/ngtd/ngtd_bench_test.go

change log.Fatal to log.Error
i got advice that in these case log.Error is better than log.Fatal, so i changed log level
these changes are only in benchmark.

fix log level

---

pkg/agent/ngt/handler/grpc/handler.go
pkg/manager/backup/cassandra/handler/grpc/handler.go
pkg/manager/backup/mysql/handler/grpc/handler.go
pkg/manager/compressor/handler/grpc/handler.go
pkg/meta/cassandra/handler/grpc/handler.go
pkg/meta/redis/handler/grpc/handler.go

I added error loggings.
Nothing.
Nothing.

Add error logs

---

go.mod
go.sum
hack/go.mod.default
internal/compress/gzip.go
internal/compress/lz4.go
internal/compress/zstd.go
internal/compress/zstd_option.go
pkg/manager/backup/cassandra/handler/grpc/handler.go

I've just removed the hex encoding process in manager-backup-casssandra.
Nothing.
In my local kind cluster.

Remove hex encoding in manager-backup-cassandra

---

dockers/agent/ngt/Dockerfile

I added CFLAGS and CXXFLAGS to agent NGT Dockerfile. 
This is just a workaround.
Nothing.
Running the image built by this PR.

Add CFLAGS/CXXFLAGS to disable AVX512

---

internal/timeutil/location/loc_test.go
internal/timeutil/time_test.go

test case for internal/timeutil package

Test case for `internal/timeutil`

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml
.github/workflows/semver.yml

I added automated release flow to .github directory.
Nothing.
not tested yet.

Automated release flow

---

pkg/agent/ngt/service/ngt.go

when we use Update API of ngt-agent they have a vector cache and flow is below
req -> add delete vector cache (then check there is older same uuid's insert vecter cache? then delete)
-> add insert vector cache (then check there is older same uuid's delete vecter cache? then delete)
that is why there is no delete vector cache, exactly kvs is stable but we have to delete edge vector from anng.
so I changed about it.

vector cache logic changed

---

.github/chatops_permissions.yaml
.github/workflows/chatops.yml
README.md

I added /format command for chatops.
Nothing.
Not tested yet.

Add /format command for ChatOps

---

.golangci.yml
go.mod
go.sum
internal/config/cassandra.go
internal/db/nosql/cassandra/cassandra.go
internal/db/nosql/cassandra/option.go
internal/net/tcp/dialer.go
internal/timeutil/location/loc_test.go
internal/timeutil/time_test.go
pkg/manager/backup/cassandra/service/cassandra.go
vald/values.yaml

add custom dialer functionality for cassandra
also I added tcp dialer configuration for each cassandra configuration, 

add custom dialer

---

Makefile.d/k8s.mk
k8s/external/scylla/statefulset.yaml
k8s/external/scylla/svc.yaml
vald/values.yaml

I added ScyllaDB deployments.
Nothing.
in my local KinD.

Add scylla deployments

---

go.mod
go.sum

update depenedencies
this update includes go-redis library update v7.0.0.beta.5 to v7.0.0.beta.6 (includes Pipeline logic change)

update go module dependencies

---

Makefile.d/k8s.mk
vald/values.yaml

I added tasks to deploy Vald with either Scylla or Cassandra.
Nothing.
Nothing.

add deploy tasks (with either Scylla or Cassandra) to Makefile

---

vald/templates/_helpers.tpl
vald/templates/agent/daemonset.yaml
vald/templates/agent/deployment.yaml
vald/templates/agent/statefulset.yaml
vald/templates/discoverer/daemonset.yaml
vald/templates/discoverer/deployment.yaml
vald/templates/gateway/vald/daemonset.yaml
vald/templates/gateway/vald/deployment.yaml
vald/templates/manager/backup/daemonset.yaml
vald/templates/manager/backup/deployment.yaml
vald/templates/manager/compressor/daemonset.yaml
vald/templates/manager/compressor/deployment.yaml
vald/templates/meta/daemonset.yaml
vald/templates/meta/deployment.yaml

I added capability to allow users to add their own custom volumes, volumeMounts, and initContainers.
Nothing.
In my local environment.

[Helm] add volumes volumeMounts / add custom initContainers

---

.github/workflows/chatops.yml

Fix chatops permission check flow.

:green_heart: Fix chatops: yq v3

---

vald/templates/agent/daemonset.yaml
vald/templates/agent/deployment.yaml
vald/templates/agent/statefulset.yaml
vald/templates/discoverer/daemonset.yaml
vald/templates/discoverer/deployment.yaml
vald/templates/gateway/vald/daemonset.yaml
vald/templates/gateway/vald/deployment.yaml
vald/templates/manager/backup/daemonset.yaml
vald/templates/manager/backup/deployment.yaml
vald/templates/manager/compressor/daemonset.yaml
vald/templates/manager/compressor/deployment.yaml
vald/templates/meta/daemonset.yaml
vald/templates/meta/deployment.yaml

Add capability to set nodeName and nodeSelector to each deployements.
Nothing.
Just running `helm template`

Add nodeName and nodeSelector field to Helm template

---

k8s/debug/kind/config.yaml
pkg/gateway/vald/service/gateway.go
vald/templates/discoverer/clusterrole.yaml

bugfix of gateway daemon start logic

[patch] bugfix in discovered agent client panic problem

---

.github/workflows/dockers-manager-index-image.yml
Makefile
Makefile.d/docker.mk
Makefile.d/k8s.mk
README.md
dockers/manager/index/Dockerfile
internal/config/gateway.go
internal/config/index.go
pkg/gateway/vald/service/gateway_option.go
pkg/gateway/vald/usecase/vald.go
pkg/manager/index/service/option.go
pkg/manager/index/usecase/vald.go
vald/templates/gateway/vald/configmap.yaml
vald/templates/manager/index/configmap.yaml
vald/templates/manager/index/daemonset.yaml
vald/templates/manager/index/deployment.yaml
vald/templates/manager/index/pdb.yaml
vald/templates/manager/index/svc.yaml
vald/values.yaml

I've just added Dockerfile, CI settings, and Helm template for index-manager.
Also i've added implementation related to `auto_index_length` option.
Nothing.
Not yet.

Add Dockerfile, CI settings, and Helm template for index-manager

---

go.mod
go.sum
internal/net/grpc/client.go
internal/net/grpc/pool.go
internal/net/grpc/pool_bench_test.go
internal/net/tcp/dialer.go
pkg/gateway/vald/service/gateway.go

recently gateway have a problem about high memory usage
this PR includes 3 patch
1. check default connection or not in pool.Put
2. change discovery sort loop to channel bubble sort
3. minimumized scope pool.Do for each request method eg(Range, RangeConcurrent, OrderedRange, OrderedRangeConcurrent, Do)

[patch] bugfix gateway high memory usage

---

Makefile.d/k8s.mk
vald/templates/agent/daemonset.yaml
vald/templates/agent/deployment.yaml
vald/templates/agent/statefulset.yaml
vald/templates/discoverer/daemonset.yaml
vald/templates/discoverer/deployment.yaml
vald/templates/gateway/vald/daemonset.yaml
vald/templates/gateway/vald/deployment.yaml
vald/templates/manager/backup/daemonset.yaml
vald/templates/manager/backup/deployment.yaml
vald/templates/manager/compressor/daemonset.yaml
vald/templates/manager/compressor/deployment.yaml
vald/templates/manager/index/daemonset.yaml
vald/templates/manager/index/deployment.yaml
vald/templates/meta/daemonset.yaml
vald/templates/meta/deployment.yaml
vald/values-cassandra.yaml
vald/values-dev.yaml
vald/values-scylla.yaml
vald/values.yaml

This PR includes the followings.
- Add annotations of configmaps' sha256 checksum
- Add values-dev.yaml, values-cassandra.yaml, values-scylla.yaml
Nothing.
Nothing.

Add sha256 checksum of configmaps to each deployments / Add values-xxx.yaml

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-base-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml
README.md

Docker image tagging policy is revised.
Nothing.
Nothing.

Revise Docker image tagging policy

---

internal/client/discoverer/discover.go

[patch] bugfix discovery start up

---

vald/templates/discoverer/configmap.yaml
vald/values.yaml

I added discoverer config to Helm template.
Nothing.
Nothing.

Add discoverer config to Helm template

---

vald/templates/agent/statefulset.yaml
vald/values-dev.yaml
vald/values.yaml

I added podManagementPolicy field to agent statefulset yaml.
Nothing.
Nothing.

Add podManagementPolicy for agent statefulset

---

go.mod
go.sum
internal/client/discoverer/discover.go
internal/net/grpc/client.go
pkg/gateway/vald/handler/grpc/handler.go
pkg/gateway/vald/service/gateway.go
pkg/manager/index/service/indexer.go

for now gateway has problem about insertion balancing.
specific agent will use 2x large memory than others.

[bugfix] gateway loadbalancing algorithms

---

vald/templates/_helpers.tpl
vald/templates/agent/configmap.yaml
vald/templates/agent/daemonset.yaml
vald/templates/agent/deployment.yaml
vald/templates/agent/statefulset.yaml
vald/templates/discoverer/configmap.yaml
vald/templates/discoverer/daemonset.yaml
vald/templates/discoverer/deployment.yaml
vald/templates/gateway/vald/configmap.yaml
vald/templates/gateway/vald/daemonset.yaml
vald/templates/gateway/vald/deployment.yaml
vald/templates/manager/backup/configmap.yaml
vald/templates/manager/backup/daemonset.yaml
vald/templates/manager/backup/deployment.yaml
vald/templates/manager/compressor/configmap.yaml
vald/templates/manager/compressor/daemonset.yaml
vald/templates/manager/compressor/deployment.yaml
vald/templates/manager/index/configmap.yaml
vald/templates/manager/index/daemonset.yaml
vald/templates/manager/index/deployment.yaml
vald/templates/meta/configmap.yaml
vald/templates/meta/daemonset.yaml
vald/templates/meta/deployment.yaml
vald/values-cassandra.yaml
vald/values-scylla.yaml
vald/values.yaml

Helm templates are refactored here.
- add logging default settings
- add initContaiener templates
- wait-for-mysql
- wait-for-cassandra
- wait-for-redis
- limit-vsz (eg. https://www.kaoriya.net/blog/2020/01/18/golang-on-docker-oom/)
Nothing.
Nothing.

Refactor Helm template to add initContainer templates & logging default settings

---

.github/workflows/build-protobuf.yml
.github/workflows/coverage.yml
.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-base-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml
.github/workflows/e2e-bench-agent-stream.yml
.github/workflows/e2e-deploy.yml
vald/values-scylla.yaml
vald/values.yaml

I added e2e deploy job.
It runs only when the VALD_VERSION is updated.
I fixed the triggers in several CI workflows.
Nothing.
In vald-ci-labs repository.
https://github.com/vdaas/vald-ci-labs/runs/473946788

Add e2e deploy job

---

.github/workflows/helm.yml
internal/net/tcp/option_dialer.go
internal/observability/metrics/metrics.go
vald/values.yaml

I fixed a bug on internal/observability/collector.
And updated Helm values & CI.
Nothing.
Nothing.

Bugfix on internal/observability/collector & update Helm values

---

.github/workflows/e2e-deploy.yml
vald/templates/manager/index/configmap.yaml
vald/values-ci.yaml

I added observability section to index manger template.
I added values-ci.yaml.
Nothing.
Nothing.

[Fix CI / Helm] Add observability section to index manager template / Add values-ci.yaml

---

dockers/operator/helm/Dockerfile
go.mod
go.sum
internal/errors/compressor.go
pkg/manager/compressor/handler/grpc/handler.go
pkg/manager/compressor/service/compress.go

change errgroup logic in compress queue

[patch] change errgroup return logic

---

vald/templates/agent/daemonset.yaml
vald/templates/agent/deployment.yaml
vald/templates/agent/statefulset.yaml
vald/templates/discoverer/daemonset.yaml
vald/templates/discoverer/deployment.yaml
vald/templates/gateway/vald/daemonset.yaml
vald/templates/gateway/vald/deployment.yaml
vald/templates/manager/backup/daemonset.yaml
vald/templates/manager/backup/deployment.yaml
vald/templates/manager/compressor/daemonset.yaml
vald/templates/manager/compressor/deployment.yaml
vald/templates/manager/index/daemonset.yaml
vald/templates/manager/index/deployment.yaml
vald/templates/meta/daemonset.yaml
vald/templates/meta/deployment.yaml

As described in [the official document of Helm](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments), to roll deployment/statefulset/daemonset automatically, we should put configmaps' checksum annotations on `spec.template.metadata.annotations.checksum/config`.
this PR fixes the place of checksums.
Nothing.
Nothing.

Fix Helm chart: annotations.checksum/config

---

Makefile.d/k8s.mk
k8s/metrics/profefe/clusterrole.yaml
k8s/metrics/profefe/clusterrolebinding.yaml
k8s/metrics/profefe/cronjob.yaml
k8s/metrics/profefe/deployment.yaml
k8s/metrics/profefe/serviceaccount.yaml
k8s/metrics/profefe/svc.yaml
vald/templates/_helpers.tpl
vald/templates/agent/daemonset.yaml
vald/templates/agent/deployment.yaml
vald/templates/agent/statefulset.yaml
vald/templates/discoverer/daemonset.yaml
vald/templates/discoverer/deployment.yaml
vald/templates/gateway/vald/daemonset.yaml
vald/templates/gateway/vald/deployment.yaml
vald/templates/manager/backup/daemonset.yaml
vald/templates/manager/backup/deployment.yaml
vald/templates/manager/compressor/daemonset.yaml
vald/templates/manager/compressor/deployment.yaml
vald/templates/manager/index/daemonset.yaml
vald/templates/manager/index/deployment.yaml
vald/templates/manager/index/svc.yaml
vald/templates/meta/daemonset.yaml
vald/templates/meta/deployment.yaml
vald/values-dev.yaml

- added profefe deployment.
- revise Helm chart
- capability to add annotations to deployment/statefulset/daemonset
- add 'quote' function to default-empty-fields
Nothing.
Nothing.

Revise Helm charts and Add profefe deployment

---

.github/workflows/semver.yml
vald/values-dev.yaml
vald/values.yaml

I've just revised the CI flow to upgrade Vald version.
Helm charts should have their own version for `defaults.image.tag` value.
`defaults.image.tag` of values.yaml will be updated when the Vald version is upgraded.
Nothing.
On vald-ci-labs
https://github.com/vdaas/vald-ci-labs/commit/5a17cefcfcb94e80837d3e9cda72ab57e003140a

[Helm] Use latest release version for default tag

---

vald/templates/agent/daemonset.yaml
vald/templates/agent/deployment.yaml
vald/templates/agent/priorityclass.yaml
vald/templates/agent/statefulset.yaml
vald/templates/gateway/vald/deployment.yaml
vald/templates/manager/backup/deployment.yaml
vald/templates/manager/compressor/deployment.yaml
vald/templates/meta/deployment.yaml
vald/values.yaml

Added pod priority class for agent-ngt.
I've just fixed the problem on HPA and Helm-operator race condition.
Nothing.
In my local KinD.

Add pod priority for agent-ngt & Fix problem on HPA and Helm-operator

---

vald/values.yaml

Default values in Helm chart are revised.
- gRPC, liveness, readiness servers enabled by default.
- REST, pprof, Prometheus servers disabled by default.
- server configs in each components removed from values.yaml.
- it becomes possible to control enable/disable servers by editing `defaults` value.
- off course, users can specify these options in their own values.yaml.
- Observability features disabled by default.
- users must override values if they want to use observability features.
- agent HPA is disabled by default
- agent `auto_index_limit` and `auto_index_check_duration` are revised.
Nothing.
Nothing.

Revise default values in Helm chart

---

.github/workflows/build-protobuf.yml
.github/workflows/chatops.yml
.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml
.github/workflows/e2e-deploy.yml
.github/workflows/helm.yml
.github/workflows/reviewdog.yml
Makefile
dockers/ci/base/Dockerfile
hack/tools/config/meta/redis/sample.yaml

I added yaml-formatter to /format command of ChatOps.
I've updated CI container.
Nothing.
Nothing.

ChatOps: update format command / Update CI container

---

Makefile
Makefile.d/docker.mk

Fix CI container.
Nothing.
Nothing.

Fix CI container build

---

.github/PULL_REQUEST_TEMPLATE.md
.github/labeler.yml
.github/workflows/chatops.yml
.github/workflows/labeler.yml
.github/workflows/update_pull_request_template.yml

- Refactoring labeler code / rules.
- remove duplications of priority or size labels (higher/larger labels will be used)
- automatically add priority labels
- automatically update PULL_REQUEST_TEMPLATE
Nothing.
In this PR.

Refactoring labeler

---

.github/workflows/chatops.yml
.github/workflows/e2e-deploy.yml
Makefile
dockers/ci/base/Dockerfile

I've just remove CI-container from useless cases.
And now, ChatOps and e2e-deploy test are fixed by removing it.
Nothing.
Nothing.

Fix ChatOps and e2e deploy test: remove CI-container from useless cases

---

.github/workflows/helm.yml
Makefile
Makefile.d/helm.mk
Makefile.d/k8s.mk
charts/vald-helm-operator/README.md
charts/vald-helm-operator/README.md.gotmpl
charts/vald-helm-operator/values.yaml
charts/vald/README.md
charts/vald/README.md.gotmpl
charts/vald/templates/_helpers.tpl
charts/vald/templates/agent/svc.yaml
charts/vald/templates/discoverer/svc.yaml
charts/vald/templates/gateway/vald/svc.yaml
charts/vald/templates/manager/backup/svc.yaml
charts/vald/templates/manager/compressor/svc.yaml
charts/vald/templates/manager/index/svc.yaml
charts/vald/templates/meta/svc.yaml
charts/vald/values.yaml
dockers/ci/base/Dockerfile
hack/license/gen/main.go

In this PR, README.md for Vald Helm chart will be written.
There's some refinement in Helm chart.
- `server_config` can be overridden by each component's field
- service annotations and labels are separated
Nothing.
Nothing.

Add docs for Vald Helm chart

---

README.md
docs/user/get-started.md

- Refactoring(update) sentence in `GET STARTED`
- I added helm chart document's link at [Customize Vald](https://github.com/vdaas/vald/blob/master/docs/user/get-started.md#customize-vald) section.
- Fix typo
Nothing
This PR doesn't need to test

Add helm chart docs' link to get-started

---

README.md

Use deepsource mini badge instead of large size badge.
Nothing.
Nothing.

Use deepsource mini badge

---

CHANGELOG.md

I added `CHANGELOG` for tracking the package version.
None
None

[patch] add CHANGELOG

---

charts/vald/values.yaml

liveness probe of agent & compressor disabled.
Nothing.
Nothing.

🔧Agent & Compressor liveness disabled

---

charts/vald/values.yaml

fixed `connection-pool` value in Helm chart.
Nothing.
docker run in local

🐛 Fix connection-pool value in chart

---

README.md

added slack join link
nothing.
nothing.

📝 Add slack join link

---

go.mod
go.sum
internal/log/option.go
internal/net/grpc/client.go
internal/net/grpc/pool.go
internal/params/params.go
internal/runner/runner.go
k8s/jobs/db/initialize/cassandra/job.yaml
k8s/jobs/db/initialize/mysql/job.yaml
k8s/jobs/db/initialize/redis/job.yaml
k8s/operator/helm/clusterrole.yaml

this PR includes two bugfix
-  grpc connection pooling logic is opposite
- load config error never printed out

bugfix grpc connection pooling & config loader

---

charts/vald/values.yaml
internal/config/discoverer.go
internal/net/grpc/pool.go
internal/net/grpc/pool_bench_test.go
internal/singleflight/singleflight.go
pkg/discoverer/k8s/handler/grpc/handler.go
pkg/discoverer/k8s/handler/grpc/option.go
pkg/discoverer/k8s/usecase/discovered.go

replace expiration cache to zero time caching logic for discoverer

[patch] remove discoverer cache and add zero time caching logic to discoverer

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-base-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml
go.mod
go.sum
k8s/jobs/db/initialize/cassandra/job.yaml
k8s/jobs/db/initialize/mysql/job.yaml
k8s/jobs/db/initialize/redis/job.yaml
k8s/operator/helm/clusterrole.yaml

💚 publish nightly image when version updated

---

docs/developer/style.md

I added test guideline for developer.
Details will be described in the markdown (test_guideline.md)

Test Guidelines

---

charts/vald/values.yaml

🔧 Agent & Compressor liveness disabled (re-created PR)

---

charts/vald/templates/discoverer/daemonset.yaml
charts/vald/templates/discoverer/deployment.yaml
charts/vald/templates/discoverer/priorityclass.yaml
charts/vald/templates/gateway/vald/daemonset.yaml
charts/vald/templates/gateway/vald/deployment.yaml
charts/vald/templates/gateway/vald/priorityclass.yaml
charts/vald/templates/manager/backup/daemonset.yaml
charts/vald/templates/manager/backup/deployment.yaml
charts/vald/templates/manager/backup/priorityclass.yaml
charts/vald/templates/manager/compressor/daemonset.yaml
charts/vald/templates/manager/compressor/deployment.yaml
charts/vald/templates/manager/compressor/priorityclass.yaml
charts/vald/templates/manager/index/daemonset.yaml
charts/vald/templates/manager/index/deployment.yaml
charts/vald/templates/manager/index/priorityclass.yaml
charts/vald/templates/meta/daemonset.yaml
charts/vald/templates/meta/deployment.yaml
charts/vald/templates/meta/priorityclass.yaml
charts/vald/values.yaml

Add PriorityClasses to all components.
Nothing.
Nothing.

✨ Add PriorityClasses to all components

---

charts/vald-helm-operator/Chart.yaml
charts/vald/Chart.yaml
charts/vald/templates/_helpers.tpl
charts/vald/templates/agent/daemonset.yaml
charts/vald/templates/agent/deployment.yaml
charts/vald/templates/agent/statefulset.yaml
charts/vald/templates/discoverer/daemonset.yaml
charts/vald/templates/discoverer/deployment.yaml
charts/vald/templates/gateway/vald/daemonset.yaml
charts/vald/templates/gateway/vald/deployment.yaml
charts/vald/templates/manager/backup/daemonset.yaml
charts/vald/templates/manager/backup/deployment.yaml
charts/vald/templates/manager/compressor/daemonset.yaml
charts/vald/templates/manager/compressor/deployment.yaml
charts/vald/templates/manager/index/daemonset.yaml
charts/vald/templates/manager/index/deployment.yaml
charts/vald/templates/meta/daemonset.yaml
charts/vald/templates/meta/deployment.yaml
charts/vald/values.yaml
go.mod
go.sum
k8s/operator/helm/valdrelease.yaml

This PR includes Helm Chart fixes.
- Helm Chart apiVersions are updated to v2
- Revise default values
- Add `affinity` and `tolerations` section to each components.
Nothing.
local environment.

⬆️ Update Helm Chart apiVersion to v2

---

charts/vald/templates/_helpers.tpl
charts/vald/values.yaml
go.mod
go.sum
internal/config/grpc.go
internal/net/grpc/client.go
internal/net/grpc/option.go
internal/net/grpc/pool/option.go
internal/net/grpc/pool/pool.go
internal/net/grpc/pool/pool_bench_test.go
internal/net/net.go
k8s/agent/statefulset.yaml
k8s/discoverer/deployment.yaml
k8s/gateway/vald/deployment.yaml
k8s/operator/helm/valdrelease.yaml

grpc pool connection discovers IPs from DNS record, and some server registers DualStack address it makes problem if vald didn't check TCP ping
I added the IPs connectivity check before connect.
Also, I fixed grpc connection non-graceful close problem, using delay

[patch] bugfix grpc connection pool dualstack failure and non-graceful client connection closing

---

.github/workflows/update-protobuf.yml

Currently, client libraries are built when apis/proto/** files are updated or Vald version is updated.
however, this PR modifies build timing not to update clients when apis/proto/** files are updated.
Nothing.
Nothing.

💚 dispatch protobuf build only when version is updated

---

charts/vald/templates/discoverer/priorityclass.yaml
charts/vald/templates/gateway/vald/priorityclass.yaml
charts/vald/templates/manager/backup/priorityclass.yaml
charts/vald/templates/manager/index/priorityclass.yaml
charts/vald/templates/meta/priorityclass.yaml

Removed `PriemptionPolicy: Never` from lower priority classes.
Nothing.
Nothing.

🔥 Remove preemptionPolicy=Never from lower priority classes

---

CHANGELOG.md

Vald release v0.0.30, read changlog

[patch] release v0.0.30

---

charts/vald/values.yaml
internal/config/cassandra.go
internal/db/nosql/cassandra/option.go
k8s/agent/statefulset.yaml
k8s/discoverer/deployment.yaml
k8s/gateway/vald/deployment.yaml
k8s/operator/helm/valdrelease.yaml

Revise Cassandra default values.
Nothing.
Nothing.

🔧 Revise backup/meta Cassandra default values

---

.github/workflows/helm.yml
go.mod
go.sum
k8s/agent/statefulset.yaml
k8s/discoverer/deployment.yaml
k8s/gateway/vald/deployment.yaml

Fix conflicts between formatter and Helm template.
Not an issue but there's a card in SRE task board.
Nothing.

💚 Fix conflicts between formatter and helm template

---

example/helm/values-scylla.yaml

I just fixed typo of NGT distance_type value from `12` to `l2` in `expamle/values-scylla.yaml`.
Thank @kmrmt to find out this typo.
- NGT Version: 1.11.4

Fix example/values-scylla.yaml typo

---

Makefile.d/functions.mk
assets/test/templates/common/header.tmpl
internal/db/nosql/cassandra/option_test.go
pkg/manager/replication/agent/handler/grpc/handler.go
pkg/manager/replication/agent/handler/grpc/handler_test.go
pkg/manager/replication/agent/handler/grpc/option.go
pkg/manager/replication/agent/handler/grpc/option_test.go
pkg/manager/replication/agent/handler/rest/handler.go
pkg/manager/replication/agent/handler/rest/handler_test.go
pkg/manager/replication/agent/handler/rest/option.go
pkg/manager/replication/agent/handler/rest/option_test.go
pkg/manager/replication/agent/router/router.go
pkg/manager/replication/agent/service/agent.go
pkg/manager/replication/agent/service/agent_test.go
pkg/manager/replication/agent/usecase/backupd.go
pkg/manager/replication/agent/usecase/backupd_test.go

recently golangci-lint is always failing due to my fault
so. I added temporary implementation for replication manager

buildable replication

---

internal/client/discoverer/discover.go

Discoverer may blocking discover process. So I delete the fch channel and added init error code.

Fix: improve discoverer function

---

apis/proto/gateway/vald/vald.proto

Fixed the structure of gRPC java package.
nothing.
nothing.

Fix structure of grpc java package

---

.github/workflows/helm.yml

I refactored the helm workflow to send PR when K8s manifests are updated.
When the version is updated, it may conflicts with a commit of k8s manifest updates. 
nothing.

💚 send PR when K8s manifests are updated

---

charts/vald/values.yaml

Fix name of a field.
Nothing.
Nothing.

✏️ Fix wrong name field on agent sidecar svc

---

example/client/main.go
example/helm/values-scylla.yaml

This PR contains the following changes:
1. Add indexing duration on the example program
2. Add comments about the indexing feature
3. Fix logging message on example program

Example program: Add indexing interval description & fix logging message

---

.github/workflows/chatops.yml

Fix bug on /changelog command.
Nothing.
Nothing.

🐛 Fix bug on changelog command

---

.github/workflows/chatops.yml
.github/workflows/semver.yml

- Fixed a bug on /changelog command
- Revised the format of the messages.
Nothing.
Nothing.

Fix a bug on /changelog command

---

assets/test/templates/common/function.tmpl
assets/test/templates/option/function.tmpl

The error occurred when I uncommented it, so I fixed the template.
In this PR, I only modified the test template.

Fix test template bug

---

.github/workflows/chatops.yml

Fix /format command
nothing.
nothing.

Fix /format command

---

.github/workflows/chatops.yml

- fix /changelog command message format
nothing.
nothing.

💚 Fix /changelog command format

---

.github/workflows/semver.yml

To register a new version to pkg.go.dev, a request should be sent to GoProxy.
nothing.
nothing.

send a request to GoProxy after new version is published

---

.github/workflows/codeql-analysis.yml
.github/workflows/detect-internal-config-changes.yml
.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml
.github/workflows/e2e-bench-agent.yml
.github/workflows/reviewdog.yml
.github/workflows/semver.yml

- Revise triggers of workflow runs
- Fix reading changelogs from PR comments
Nothing.
Nothing.

Revise triggers of workflow run & Fix reading changelogs from PR comments

---

README.md
charts/vald-helm-operator/Chart.yaml
charts/vald-helm-operator/README.md.gotmpl
charts/vald/Chart.yaml
charts/vald/README.md.gotmpl
internal/config/observability_test.go
internal/observability/client/google/option_test.go
internal/observability/collector/collector_option_test.go
internal/observability/exporter/jaeger/jaeger_option_test.go
internal/observability/exporter/jaeger/jaeger_test.go
internal/observability/exporter/prometheus/prometheus_option_test.go
internal/observability/exporter/prometheus/prometheus_test.go
internal/observability/exporter/stackdriver/stackdriver_option_test.go
internal/observability/exporter/stackdriver/stackdriver_test.go
internal/observability/metrics/version/version_test.go
internal/observability/observability_option_test.go
internal/observability/observability_test.go
internal/observability/profiler/stackdriver/stackdriver_test.go

- Update Helm Chart info.
- Add ArtifactHub badge
- (fix tests to run reviewdog correctly)
Nothing.
Nothing.

Update Helm Chart info

---

internal/net/http/transport/roundtrip.go

fixed roundtrip function in transport.go.
#502 
nothing.

Fix roundtrip error handling

---

internal/unit/unit_test.go

I added a test case for `internal/unit` pacakge.
this PR's coverage is 100%

Added test case for `internal/unit` pacakge

---

.github/codeql/codeql-config.yaml
.github/workflows/codeql-analysis.yml
.github/workflows/helm.yml
.github/workflows/update_pull_request_and_issue_template.yml

Add codeQL config.
(this PR includes the fix of several workflows.)
nothing.
nothing.

add codeql config

---

.github/workflows/test.yml
Makefile
Makefile.d/test.mk
dockers/ci/base/Dockerfile

Add test workflow.
nothing
nothing

Add test workflow

---

.github/workflows/chatops.yml

Fix condition check of chatops

---

Makefile
Makefile.d/docker.mk
Makefile.d/test.mk

i found there's no need to force rebuild gotests.
removed dockfmt.
nothing
nothing

not to force rebuild gotests

---

internal/config/ngt.go
internal/config/ngt_test.go

I added `internal/config/ngt` test

add internal/config/ngt test

---

.github/workflows/test.yml
Makefile.d/test.mk

add `tee` command to pass tparse tests.
nothing.
nothing.

pass tparse by tee command

---

.github/workflows/helm.yml

update k8s manifests only on publish tags

---

internal/cache/option.go
internal/cache/option_test.go

I added test of `internal/cache/option.go` and comment of each `internal/cache/option` function.

add internal/cache/option test

---

.github/workflows/reviewdog-hadolint.yml

Add action-reviewdog-hadolint.
nothing.
nothing.

Add reviewdog - hadolint

---

.github/workflows/reviewdog-markdown.yml

reviewdog - markdown
added LanguageTool
https://github.com/reviewdog/action-languagetool
nothing
nothing

Add reviewdog - markdown: LanguageTool

---

.github/workflows/reviewdog-markdown.yml

revise languagetool rules

---

.github/workflows/reviewdog-markdown.yml

revise languagetool rules: disable TYPOS, DASH_RULE

---

.github/workflows/reviewdog-markdown.yml

:wrench: revise languagetool rules: disable EN_QUOTES

---

charts/vald/templates/manager/index/configmap.yaml

Fix Helm template: indexer creation_pool_size field

---

internal/compress/gob.go
internal/compress/gob_test.go

I added test case for `internal/compress/gob.go` and I refactored based on [code guideline](https://github.com/vdaas/vald/blob/master/docs/contributing/coding-style.md#error-checking).

Add test for `internal/compress/gob.go`

---

charts/vald-helm-operator/templates/operator.yaml

fixes a potentially bug in Helm chart for Vald-Helm-Operator.
nothing
nothing

fix indents in helm chart of vald-helm-operator

---

.github/workflows/dockers-helm-operator-image.yml
dockers/operator/helm/Dockerfile

[patch] add build stage for operator-sdk docker v1.0.0 permission changes

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-base-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-image-scan.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml

improve CI builds
- use DOCKER_BUILDKIT
- use docker-login action
for Agent-NGT builds,
before: 5m 3s
after: 3m 41s
nothing
nothing

improve CI builds: use DOCKER_BUILDKIT

---

dockers/ci/base/Dockerfile

update CI container dependencies & remove workdir contents
nothing
nothing

CI-container: upgrade dependencies of & remove workdir contents

---

internal/db/rdb/mysql/dbr/dbr_mock.go
internal/db/rdb/mysql/dbr/session.go
internal/db/rdb/mysql/mysql.go
internal/db/rdb/mysql/mysql_test.go

I created the test for a part of the method at `internal/db/rdb/mysql.go`.
Because, It will be create large diff when I created test for all method in `mysql.go`.
And also, I created the dbr mock code for test instead of connecting real MySQL database.
And more, I refactored code for test.
- Use `pctx` instead of `ctx` which is parent of `pctx` at `Ping()`.
It is just for testing and will not affect current logic.

create test for mysql.go (part1)

---

Makefile
apis/docs/docs.md
apis/proto/agent/core/agent.proto
apis/proto/agent/sidecar/sidecar.proto
apis/proto/discoverer/discoverer.proto
apis/proto/filter/egress/egress_filter.proto
apis/proto/filter/ingress/ingress_filter.proto
apis/proto/gateway/vald/vald.proto
apis/proto/manager/backup/backup_manager.proto
apis/proto/manager/compressor/compressor.proto
apis/proto/manager/index/index_manager.proto
apis/proto/manager/replication/agent/replication_manager.proto
apis/proto/manager/replication/controller/replication_manager.proto
apis/proto/manager/traffic/traffic_manager.proto
apis/proto/meta/meta.proto
apis/swagger/agent/core/core/agent.swagger.json
apis/swagger/discoverer/discoverer.swagger.json
apis/swagger/gateway/vald/vald/vald.swagger.json
apis/swagger/manager/backup/backup/backup_manager.swagger.json
apis/swagger/manager/compressor/compressor/compressor.swagger.json
apis/swagger/manager/index/index/index_manager.swagger.json
apis/swagger/manager/replication/agent/replication/agent/replication_manager.swagger.json
apis/swagger/manager/replication/controller/replication/controller/replication_manager.swagger.json
apis/swagger/meta/meta.swagger.json

Remove go-proto-gql dependency

---

internal/db/rdb/mysql/mysql.go
internal/db/rdb/mysql/mysql_test.go
internal/errors/mysql.go
internal/errors/mysql_test.go

I added remaining test of `internal/db/rdb/mysql.go`.
and, I refactored internal function `deleteMeta()` for easy to call from `DeleteMeta()` or `DeleteMetas()`.
Also, due to `dbr.Eq()` converts `IN` method when val is slice, I remove loop at `removeIPs()`.
ref: https://github.com/gocraft/dbr/blob/master/condition.go#L53

refactor deleteMeta and create mysql test

---

pkg/manager/backup/cassandra/handler/grpc/handler.go
pkg/manager/backup/mysql/handler/grpc/handler.go
pkg/manager/compressor/handler/grpc/handler.go
pkg/manager/compressor/service/registerer.go

change manager components for new design apis
this PR is sub PR for #742 
this change will be change backup data format, new manager never backup metadata, metadata will store meta components

change pkg/manager package for new design api

---

pkg/discoverer/k8s/service/discover.go

resolves discoverer components bug

bugfix discoverer nil map reference

---

.github/workflows/dockers-gateway-lb-image.yml
cmd/gateway/lb/main.go
dockers/gateway/lb/Dockerfile
internal/net/grpc/client.go
pkg/gateway/internal/location/location.go
pkg/gateway/lb/README.md
pkg/gateway/lb/config/config.go
pkg/gateway/lb/handler/doc.go
pkg/gateway/lb/handler/grpc/handler.go
pkg/gateway/lb/handler/grpc/option.go
pkg/gateway/lb/handler/grpc/visitlist.go
pkg/gateway/lb/handler/rest/handler.go
pkg/gateway/lb/handler/rest/option.go
pkg/gateway/lb/router/option.go
pkg/gateway/lb/router/router.go
pkg/gateway/lb/service/doc.go
pkg/gateway/lb/service/gateway.go
pkg/gateway/lb/service/option.go
pkg/gateway/lb/usecase/vald.go

Implement lb gateway for new design API
this PR is sub PR for #742

feature add LB Gateway for new design API

---

.github/workflows/dockers-gateway-meta-image.yml
cmd/gateway/meta/main.go
dockers/gateway/meta/Dockerfile
pkg/gateway/internal/location/location.go
pkg/gateway/meta/README.md
pkg/gateway/meta/config/config.go
pkg/gateway/meta/handler/doc.go
pkg/gateway/meta/handler/grpc/handler.go
pkg/gateway/meta/handler/grpc/option.go
pkg/gateway/meta/handler/rest/handler.go
pkg/gateway/meta/handler/rest/option.go
pkg/gateway/meta/router/option.go
pkg/gateway/meta/router/router.go
pkg/gateway/meta/service/doc.go
pkg/gateway/meta/service/meta.go
pkg/gateway/meta/service/option.go
pkg/gateway/meta/usecase/vald.go

Implement meta gateway for new design API
this PR is sub PR for #742

feature add Meta Gateway for new design API

---

.github/workflows/dockers-gateway-backup-image.yml
cmd/gateway/backup/main.go
dockers/gateway/backup/Dockerfile
pkg/gateway/backup/README.md
pkg/gateway/backup/config/config.go
pkg/gateway/backup/handler/doc.go
pkg/gateway/backup/handler/grpc/handler.go
pkg/gateway/backup/handler/grpc/option.go
pkg/gateway/backup/handler/rest/handler.go
pkg/gateway/backup/handler/rest/option.go
pkg/gateway/backup/router/option.go
pkg/gateway/backup/router/router.go
pkg/gateway/backup/service/backup.go
pkg/gateway/backup/service/doc.go
pkg/gateway/backup/service/option.go
pkg/gateway/backup/usecase/vald.go
pkg/gateway/internal/location/location.go

Implement backup gateway for new design API
this PR is sub PR for #742

feature add Backup Gateway for new design API

---

internal/net/net.go
pkg/agent/core/ngt/handler/grpc/handler.go
pkg/agent/core/ngt/handler/grpc/option.go
pkg/agent/core/ngt/handler/rest/handler.go
pkg/agent/core/ngt/handler/rest/option.go
pkg/agent/core/ngt/service/kvs/kvs.go
pkg/agent/core/ngt/usecase/agentd.go
pkg/agent/sidecar/service/observer/observer.go
pkg/agent/sidecar/service/restorer/restorer.go

change agent components for new design apis
this PR is sub PR for #742 

change pkg/agent sidecar & core for new design api

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-base-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-dev-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml

due to GitHub Action vulnerability, `set-env` and `set-path` commands are deprecated now.
This PR replaces these commands. (fortunately set-path is not used in this repository)
Please see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
nothing
nothing

CI: remove deprecated set-env commands

---

pkg/gateway/vald/handler/grpc/handler.go

[patch] bugfix gateway index out of bounds

---

cmd/tools/cli/loadtest/sample.yaml
pkg/tools/cli/loadtest/config/config.go
pkg/tools/cli/loadtest/service/insert.go
pkg/tools/cli/loadtest/service/loader.go
pkg/tools/cli/loadtest/service/loader_option.go
pkg/tools/cli/loadtest/service/search.go
pkg/tools/cli/loadtest/usecase/load.go

- Delete parameter "service" because of using same interface in agent and gateway
- Fix request type to adapt new API
- #740 

Use new design apis in load test

---

assets/test/templates/common/function.tmpl
assets/test/templates/common/header.tmpl
assets/test/templates/option/function.tmpl

Use t.Parallel for improve test performance.
This PR is sub PR for #740 

change test assets for new design api

---

internal/db/storage/blob/s3/reader/option.go
internal/db/storage/blob/s3/reader/reader.go
internal/db/storage/blob/s3/reader/reader_test.go
internal/db/storage/blob/s3/s3.go

I fixed clush bug due to the nil pointer exception of context.io.
I am sorry to make a mistake.

[patch] Fix fails test for s3 reader

---

.github/workflows/dockers-gateway-backup-image.yml
.github/workflows/dockers-gateway-lb-image.yml
.github/workflows/dockers-gateway-meta-image.yml
dockers/gateway/backup/Dockerfile
dockers/gateway/lb/Dockerfile
dockers/gateway/meta/Dockerfile

fixed Dockerfiles.
#742
nothing

fix Dockerfiles for feature/internal/new-design-apis branch

---

Makefile.d/docker.mk

fixed Makefile.d/docker.mk.
#740
nothing

fix Makefile.d/docker.mk for feature/all-new-design-apis branch

---

.deepsource.toml

This PR disable deepsource analysis on generated file `.pb.go` and example code.
Ref: https://deepsource.io/docs/config/deepsource-toml.html#exclude-patterns

ignore deepsource analysis on .pb.go and example code

---

internal/config/rebalancer.go

we(@kevindiu, @hlts2) added configuration for file index rebalancer.

Add rebalancer configuration

---

.github/workflows/chatops.yml
.github/workflows/helm.yml
.github/workflows/update_pull_request_and_issue_template.yml

use fetch-depth:0 for commit changes in CI runs.
Nothing.
Nothing.

fix checkout-v2 fetch depths

---

internal/k8s/job/job.go
internal/k8s/job/option.go
internal/k8s/metrics/node/node.go
internal/k8s/metrics/pod/pod.go
internal/k8s/node/node.go
internal/k8s/pod/pod.go
pkg/rebalancer/storage/controller/usecase/rebalanced.go
pkg/rebalancer/storage/job/usecase/rebalanced.go

we (@kevindiu @hlts2 ) added reconciliation loop logic for job resource.

Add reconciliation loop for job resource

---

internal/db/rdb/mysql/mysql_test.go

I fixed failing test of `mysql.go`
ref: https://github.com/vdaas/vald/runs/1379147446

fix failed MySQL test

---

internal/errors/k8s.go
internal/k8s/replicaset/option.go
internal/k8s/replicaset/replicaset.go
pkg/rebalancer/storage/controller/usecase/rebalanced.go
pkg/rebalancer/storage/job/usecase/rebalanced.go

This PR implements replicaset reconciler for rebalancer.
It implements [k8s reconciler interface](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler) to get the replica set information from k8s API and execute hook when the reconciliation is executed.
It is a part of the rebalancer implementation where the rebalancer will determine wether to execute Vald vector rebalance logic base on the replica set changes on k8s.

Add replicaset reconciler

---

.github/workflows/semver.yml
dockers/base/Dockerfile

- Remove `go mod tidy` command from dockers/base/Dockerfile
- Add valid token to CI semver job
nothing
nothing

[patch] Remove go mod tidy from base image / Add valid token to semver job

---

internal/errors/io.go
internal/errors/io_test.go

I added the test cases for internal/errors/io.go and comments.
**grammar check passed**

Add test case for internal/errors/io.go

---

.github/workflows/format.yml

Added a workflow to create a new pull request to update license headers and format codes when a new commit is pushed to master branch.
I think it is better to merge this PR after #907 is merged.
nothing
nothing

Add formatter for master branch

---

.github/workflows/chatops.yml
.github/workflows/helm.yml

Use vdaas-ci token for making commits on CI workflows such as ChatOps.
Thanks @kevindiu 
Nothing
Nothing

Use vdaas-ci token for making commits on CI workflows

---

.github/workflows/dockers-base-image.yml
Makefile

vald uses custom base image called vald-base:latest for each docker build.  all dependencies were resolved in the base, but current github actions workflow never update vald-base:latest so current implementation couldn't update dependencies.
I fixed PRIMARY_TAG in the github actions workflow, when code merged into master ci will update vald-base:latest.

change docker base image PRIMARY_TAG name from nightly to latest

---

charts/vald/templates/gateway/vald/configmap.yaml

SSIA
This typo is critical for applying configmap of vald-gateway.
nothing
nothing

Fix typo in gateway-vald configmap template

---

charts/vald/values-cassandra.yaml
charts/vald/values-scylla.yaml

remove unneccessary pr-tag definition from chart

remove unneccessary pr-tag definition from chart

---

dockers/agent/core/ngt/Dockerfile
dockers/agent/sidecar/Dockerfile
dockers/base/Dockerfile
dockers/dev/Dockerfile
dockers/discoverer/k8s/Dockerfile
dockers/gateway/backup/Dockerfile
dockers/gateway/lb/Dockerfile
dockers/gateway/meta/Dockerfile
dockers/gateway/vald/Dockerfile
dockers/manager/backup/cassandra/Dockerfile
dockers/manager/backup/mysql/Dockerfile
dockers/manager/compressor/Dockerfile
dockers/manager/index/Dockerfile
dockers/manager/replication/agent/Dockerfile
dockers/manager/replication/controller/Dockerfile
dockers/meta/cassandra/Dockerfile
dockers/meta/redis/Dockerfile
dockers/operator/helm/Dockerfile
dockers/tools/cli/loadtest/Dockerfile

fix unclosed string literal in Dockerfile's ARG MAINTAINER

fix unclosed string literal in Dockerfile's ARG MAINTAINER

---

pkg/gateway/lb/handler/grpc/handler.go

bugfix gateway-lb nil pointer panic due to nil filter configuration 

bugfix gateway-lb nil pointer panic due to nil filter configuration 

---

charts/vald/templates/gateway/backup/priorityclass.yaml
charts/vald/templates/gateway/filter/priorityclass.yaml
charts/vald/templates/gateway/lb/priorityclass.yaml
charts/vald/templates/gateway/meta/priorityclass.yaml

Revised the priorityclass names of new gateways
nothing
nothing

Use namespaced names for priorityclasses of new gateways

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-backup-manager-cassandra-image.yml
.github/workflows/dockers-backup-manager-mysql-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-dev-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-backup-image.yml
.github/workflows/dockers-gateway-filter-image.yml
.github/workflows/dockers-gateway-lb-image.yml
.github/workflows/dockers-gateway-meta-image.yml
.github/workflows/dockers-gateway-vald-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-compressor-image.yml
.github/workflows/dockers-manager-index-image.yml
.github/workflows/dockers-meta-cassandra-image.yml
.github/workflows/dockers-meta-redis-image.yml

Revise Docker build workflows because of DeadlineExceeded errors on layer pushing.
https://github.com/docker/build-push-action/issues/251#issuecomment-748272701
https://github.com/docker/build-push-action/issues/251#issuecomment-774564171
Nothing
Nothing

Add strategy section to Docker build workflows

---

docs/contributing/unit-test-guideline.md

I fixed the document path due to dead link.

fix document link path due to the dead link

---

CHANGELOG.md
hack/CHANGELOG.template.md

- Fix CHANGELOG template.
- Docker images table is broken in the master branch.
Nothing
Nothing

Fix Docker images table in CHANGELOG.md

---

internal/backoff/option.go
internal/backoff/option_test.go

I add new unit test for the backoff option.
and I added comment for godoc.

Add internal/backoff/option test

---

k8s/metrics/grafana/dashboards/01-vald-agent.yaml

- Added vqueue buffer count to Agent dashboard
nothing
nothing

Update Agent dashboard

---

.github/workflows/e2e-chaos.yaml
.github/workflows/e2e-deploy.yml

SSIA. 45m -> 60m
because of this.
https://github.com/vdaas/vald/runs/2127848951
nothing
nothing

make timeouts for e2e and chaos tests longer

---

hack/tools/metrics/main.go

because of this bug, golangci-lint on PRs doesn't work properly.
nothing
nothing

Fix hack/tools/metrics failed builds

---

internal/config/backoff.go
internal/config/backoff_test.go

I created the test of `internal/config/backoff`.
And, added the comments for each global function/variable/etc.

create internal/config/backoff test

---

internal/config/compress.go
internal/config/compress_test.go

I added test for  internal/config/compress.go and go doc comment
***gramer check passed***

Add test internal/config/compress.go

---

internal/rand/rand_bench_test.go

I created the benchmark codes for `internal/rand`.
I focused to get the performance of ns/op for each function of `internal/rand/rand.go`.
As the result, each function is not affected by input.
FYI: This is the sample of result.
```bash
goos: darwin
goarch: amd64
pkg: github.com/vdaas/vald/internal/rand
BenchmarkUint32-8                    	164953734	         7.48 ns/op	       0 B/op	       0 allocs/op
BenchmarkLimitedUint32_0-8           	180064897	         7.21 ns/op	       0 B/op	       0 allocs/op
BenchmarkLimitedUint32_10-8          	218873558	         5.74 ns/op	       0 B/op	       0 allocs/op
BenchmarkLimitedUint32_100-8         	163831244	         7.55 ns/op	       0 B/op	       0 allocs/op
BenchmarkLimitedUint32_MaxUint64-8 …
```

create bench code for internal/rand

---

internal/config/blob.go
internal/config/blob_test.go

I added a test for `internal/config/blob` and godoc comment.

Add internal/config/blob test

---

internal/db/rdb/mysql/mysql_test.go

I removed unused variables from `internal/db/rdb/mysql_test.go`.

remove unused variable from mysql test

---

internal/timeutil/location/loc_bench_test.go

This PR implement `internal/timeutil/location/loc.go` benchmark.
The benchmark result is:
```
goos: darwin
goarch: amd64
pkg: github.com/vdaas/vald/internal/timeutil/location
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkGMT-12    	  126840	      8916 ns/op	     352 B/op	       8 allocs/op
BenchmarkUTC-12    	1000000000	         0.9751 ns/op	       0 B/op	       0 allocs/op
BenchmarkJST-12    	   37604	     31617 ns/op	   57800 B/op	      14 allocs/op
PASS
ok  	github.com/vdaas/vald/internal/timeutil/location	3.988s
```

Implement internal/timeutil/location/loc.go benchmark test

---

internal/config/client.go
internal/config/client_test.go

I added test for `internal/config/client.go` and godoc comment.
**gramer check passed**

Add internal/config/client.go test

---

internal/info/info_bench_test.go

This PR implements internal/info benchmark.
The result is as follow:
```
goos: darwin
goarch: amd64
pkg: github.com/vdaas/vald/internal/info
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkString-12                	  288968	      5127 ns/op	    7152 B/op	     132 allocs/op
BenchmarkGet-12                   	 1000000	      1056 ns/op	    1714 B/op	      23 allocs/op
Benchmark_info_String-12          	  256093	      6106 ns/op	    5874 B/op	     117 allocs/op
Benchmark_Detail_String-12        	  419288	      2851 ns/op	    4144 B/op	      94 allocs/op
Benchmark_info_Get-12             	 1630857	       764.7 ns/op	    1329 B/op	      16 allocs/op
Benchmark_info_prepare-12         	1000000000	         0.4188 ns/op	       0 B/op	       0 allocs/op
Benchmark_StackTrace_String-12 …
```

Implement internal/info/info.go benchmark

---

internal/config/gateway.go
internal/config/gateway_test.go

I created the test for `internal/config/gateway`.

create internal/config/gateway test

---

charts/vald/templates/gateway/backup/daemonset.yaml
charts/vald/templates/gateway/backup/deployment.yaml
charts/vald/templates/gateway/backup/svc.yaml
charts/vald/templates/gateway/filter/daemonset.yaml
charts/vald/templates/gateway/filter/deployment.yaml
charts/vald/templates/gateway/filter/svc.yaml
charts/vald/templates/gateway/lb/daemonset.yaml
charts/vald/templates/gateway/lb/deployment.yaml
charts/vald/templates/gateway/lb/svc.yaml
charts/vald/templates/gateway/meta/daemonset.yaml
charts/vald/templates/gateway/meta/deployment.yaml
charts/vald/templates/gateway/meta/svc.yaml

- The service selectors of gateways are wrong.
- Also, pod labels are wrong.
nothing
nothing

[Bug] Fix gateway service selectors in Helm chart

---

internal/config/filter.go
internal/config/filter_test.go

I added test for `internal/config/filter.go` and godoc comment.

Add internal/config/filter.go test

---

internal/config/grpc.go
internal/config/grpc_test.go

I created the test for `internal/config/grpc.go`.
During creating tests, I found a problem that cause the invalid nil pointer error.
So, also I fixed this problem.

create internal/config/grpc test

---

internal/config/backup.go
internal/config/backup_test.go

I created the test for `internal/config/backup.go`.
grammar check has passed.

create internal/config/backup test

---

internal/config/index.go
internal/config/index_test.go

I added test for `internal/config/index.go` and godoc comment.

Add internal/config/index test

---

internal/config/meta.go
internal/config/meta_test.go

I created the PR for `internal/config/meta.go`.
grammar check has passed

create internal/config/meta test

---

internal/config/net.go
internal/config/net_test.go

I created the test for `internal/config/net.go`
grammar check has passed

create internal/config/net test

---

internal/errors/file.go
internal/errors/file_test.go
pkg/agent/sidecar/service/restorer/restorer.go

To avoid "zip slip", validation about file path is added in this PR.
Nothing
Nothing

Fix security issue: Add validation about path of extracted file

---

pkg/agent/sidecar/service/restorer/restorer.go

I made a mistake in #1145. This PR fixes it.
Nothing
Nothing

Fix validation about zip slip

---

internal/config/lb.go
internal/config/lb_test.go

I added test for internal/config/lb and godoc comment.
**grammar check passed**

Add internal/config/lb test

---

.github/workflows/dockers-filter-ingress-tensorflow.yaml

Remove arm64 build of filter-ingress-tf

---

.all-contributorsrc

remove license from bot config json

---

Makefile.d/k8s.mk

Fixed scylla deploy task due to changes in scylla-operator official repository.
https://github.com/scylladb/scylla-operator/commit/6fbaf1b83fca50de0185241ff981905bf58aa8eb#diff-f498015e0e66048d77fe410a137bcf49324101227620317ef686545246f1c34bL1947
Nothing
Nothing

Fix scylla deploy task

---

Makefile.d/build.mk

Signed-off-by: datelier <57349093+datelier@users.noreply.github.com>
SSIA

remove ngt version in filter-ingress-tensorflow

---

internal/timeutil/location/loc.go

Since the benchmark result of this PR is not good (see link below), this PR refactor internal/timeutil/location/loc.go to improve the benchmark result.
https://github.com/vdaas/vald/pull/1091
After this refactoring, the result of the benchmark is as below.
```
goos: darwin
goarch: amd64
pkg: github.com/vdaas/vald/internal/timeutil/location
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
BenchmarkGMT-12    	1000000000	         0.1531 ns/op	       0 B/op	       0 allocs/op
BenchmarkUTC-12    	1000000000	         0.1549 ns/op	       0 B/op	       0 allocs/op
BenchmarkJST-12    	1000000000	         0.1628 ns/op	       0 B/op	       0 allocs/op
PASS
ok  	github.com/vdaas/vald/internal/timeutil/location	1.386s
```
- Docker …

Improve internal/timeutil/location implementation

---

internal/config/mysql.go
internal/config/mysql_test.go

I added test for `internal/config/mysql_test`. and godoc comment.

Add test for internal/config/mysql

---

internal/config/observability.go
internal/config/observability_test.go

I added test for `internal/config/observability.go` and godoc comment.

Add internal/config/observability unit test

---

internal/config/server.go
internal/config/server_test.go

I created the test of `internal/config/server.go`
And also, I added the comments for each global variables or functions.

create test for internal/config/server

---

internal/config/sidecar.go
internal/config/sidecar_test.go

I added `internal/config/sidecar_test.go` and godoc comment.

Add internal/config/sidecar test

---

internal/config/transport.go
internal/config/transport_test.go

This PR implements internal/config/transport.go test.
It also add the comments to the implementation.

Implement internal/config/transport test

---

charts/vald/templates/jobs/db/initialize/cassandra/configmap.yaml
charts/vald/templates/jobs/db/initialize/mysql/configmap.yaml
k8s/jobs/db/initialize/cassandra/configmap.yaml
k8s/jobs/db/initialize/mysql/configmap.yaml

SSIA
#1184 
in my k3d cluster.

Fix mysql and cassandra schema definitions in initialize jobs

---

.github/workflows/coverage.yml

Update Codecov version 
https://about.codecov.io/security-update/

update codecov version for vulnerability

---

docs/contributing/unit-test-guideline.md

This PR fixes the invalid link.

Fix document url

---

pkg/agent/core/ngt/router/option.go
pkg/agent/core/ngt/router/option_test.go

This PR implements test for `pkg/agent/core/ngt/router/option`.
It also adds the comment to the file.

Implement pkg/agent/core/ngt/router/option test

---

internal/core/algorithm/ngt/ngt.go

This PR fixes the deadlock when using newGoError().

Fix mutex deadlock when calling error occurred

---

assets/test/templates/common/function.tmpl
assets/test/templates/option/function.tmpl
internal/config/backoff_test.go
internal/config/backup_test.go
internal/config/blob_test.go
internal/config/cassandra_test.go
internal/config/client_test.go
internal/config/discoverer_test.go
internal/config/filter_test.go
internal/config/gateway_test.go
internal/config/grpc_test.go
internal/config/index_test.go
internal/config/lb_test.go
internal/config/meta_test.go
internal/config/mysql_test.go
internal/config/net_test.go
internal/config/observability_test.go
internal/config/redis_test.go
internal/config/server_test.go
internal/config/sidecar_test.go
internal/config/tensorflow_test.go
internal/config/transport_test.go

The cause is that the top-level test functions are also parallelized and could not be handled properly by goleak.CurrentIgnore.
In the current code, the top-level test functions and each test case run in parallel.
For example, if TestA runs and `goleak.IgnoreCurrent` in its internal test case, the goroutine at that moment will be ignored. However, if TestB is executed in parallel immediately after goleak.IgnoreCurrent, it will increase from the number of goruotines at the time of TestA. That is the cause of this time.
When using goleak in test, the conclusion is that each test case can be run in parallel, but top-level test functions cannot be run in parallel. …

Bug fix of parallel test and goleak

---

internal/errors/lb.go
pkg/gateway/lb/handler/grpc/handler.go

change error message

---

.github/workflows/helm.yml

- Remove `continue-on-error` flag.
- Ensure to discard changes
nothing
nothing

Fix update-helm-chart workflow

---

k8s/external/scylla/scyllacluster.yaml

On CI workflows, Scylla cluster does not work properly because of lacks of ClusterRole rules.
This PR fixes it.
#1261 has been merged into master ignoring the failing workflows caused by this problem.
nothing

Fix clusterrole of scylla-cluster member

---

internal/net/grpc/client.go

bugfix nil internal/net/grpc.Client.Reconnect backoff nil pointer fix

bugfix nil internal/net/grpc.Client.Reconnect nil pointer fix

---

.github/workflows/chatops.yml
Makefile
docs/contributing/coding-style.md
hack/git/hooks/pre-commit

Revert "Use gofumpt as a default formatter"

---

pkg/agent/core/ngt/service/kvs/kvs.go
pkg/agent/core/ngt/service/kvs/kvs_test.go
pkg/agent/core/ngt/service/kvs/uo.go
pkg/agent/core/ngt/service/kvs/uo_test.go

This PR fixes a bug if the same uuid is added to the kvsdb, the counter will be increase and it will not match with the data size.

[bugfix] kvsdb: do not increment the counter if key exists

---

.github/workflows/chatops.yml
.github/workflows/format.yml
Makefile
docs/contributing/coding-style.md
hack/git/hooks/pre-commit

Use gofumpt for format workflow

---

example/helm/values-scylla.yaml
example/helm/values.yaml

Signed-off-by: datelier <57349093+datelier@users.noreply.github.com>
Issue: https://github.com/vdaas/vald/issues/1277

fix example/helm/values.yaml

---

go.mod
go.sum
hack/go.mod.default
internal/net/control/control_darwin.go
internal/net/control/control_other.go
internal/net/control/control_unix.go
internal/net/control/control_windows.go
pkg/gateway/lb/handler/grpc/handler.go
tests/e2e/crud/crud_test.go
tests/e2e/hdf5/hdf5.go
tests/e2e/kubernetes/client/client.go
tests/e2e/kubernetes/portforward/portforward.go
tests/e2e/operation/operation.go
tests/e2e/sidecar/sidecar_test.go

I added feature vector duplicate validation for reducing agents upload network bandwidth, but for Upsert operation when vector ID Exists, Upsert executes Update operation with enabling SkipStrictExistChecking, upsert already checks ID by Exists operation but we should check feature vector duplication, so I added validation feature for Upsert opeationr and Multi(Upsert, Update) operation.
change summary
1. added Upsert duplicated feature vector checking
2. small performance improvements for Exists, GetObject operation for 1.

bugfix add feature vector duplication checking for LB-GW Upsert operation.

---

Makefile.d/k8s.mk
internal/net/grpc/client.go
internal/net/grpc/status/status.go
pkg/gateway/lb/handler/grpc/handler.go

I fixed correct error backoff handling for lb gateway
1. old status is below
LBGW never backoff on current implementation in all case,  it was not working correctly.
2. the bug detail is below.
In the gRPC Handler of LBGW, when BroadCast or DoMulti is executed, if it does not return an Error, the backoff of internal/net/grpc/client will not work, but LBGW does not return an Error using return nil.
3. how to fixed.
LBGW now returns the correct error to internal/net/grpc/client, but this client also backs off in some cases, such as ContextCancel. To address this issue, we have improved gRPC Status and fixed the backoff condition.

bugfix correct error backoff handling for lb gateway

---

pkg/gateway/lb/handler/grpc/handler.go

Vald has a replicas for each index, but some agents have index X, while others do not. However, Vald's delete operation broadcasts the delete operation to X even if the agent does not have X.
Therefore, there was a case that an error was returned from some Agents that do not have X, and when the error was aggregated, it was mistakenly treated as an Error as a whole. Therefore, we changed the policy to ignore the Error when NotFound, and return a NotFound error when all Agents do not have X.

bugfix remove api return wrong error of non exsiting replicas

---

charts/vald/README.md.gotmpl
docs/user-guides/configuration.md
internal/net/control/control_darwin.go
internal/net/control/control_other.go
internal/net/control/control_unix.go
internal/net/control/control_windows.go
tests/e2e/crud/crud_test.go
tests/e2e/hdf5/hdf5.go
tests/e2e/kubernetes/client/client.go
tests/e2e/kubernetes/portforward/portforward.go
tests/e2e/sidecar/sidecar_test.go

- Update configurations.md
- remove backup, meta, replication managers.
- now it focuses on most important things.
- Update charts/vald/README.md (template)
- update overview
- remove "agent standalone configurations" <- now we have an independent document about it
Nothing
Nothing

Update documents: configurations

---

.github/actions/wait-for-docker-image/action.yaml

We use internal actions in this repository.
I found a typo in the wait-for-docker-image action. This PR fixes it.
nothing
nothing

Fix typo in wait-for-docker-image action

---

pkg/agent/core/ngt/handler/grpc/handler.go
pkg/agent/core/ngt/service/ngt.go

[bugfix] change kvsdb and vqueue check order for Exists operation

---

pkg/agent/core/ngt/service/ngt.go
pkg/agent/core/ngt/service/vqueue/queue.go

In the case of the CreateIndex, there is a possibility that the CreateIndex will not be executed while the SaveIndex is in progress, so the for-loop method should be used for the CreateIndex as well as the SaveIndex, and the Uncommitted Index Length should be checked before and after the CreateIndex.
Also, the CreateIndex, SaveIndex, and vqueue RangePop* functions run for a much longer time than the other API execution, but since the internal time.Ticker is terminated by time.After or derfer tick.Stop, so this PR fixes this as well.

[bugfix] agent createindex operation's time.Ticker purges too slow & buffer overflow due to the unnecessary error wrapping

---

Makefile.d/build.mk

Signed-off-by: datelier <57349093+datelier@users.noreply.github.com>
SSIA

comment out backup/meta/compressor build command in Makefile

---

.github/workflows/chatops.yml

It is forgotten to add condition statements for importing GPG keys.
nothing
nothing

Add condition to trigger importing gpg key on ChatOps workflow

---

dockers/ci/base/Dockerfile

Several workflows that uses ci-container requires gnupg.
https://github.com/vdaas/vald/runs/3179837183
This PR adds it to ci-container.
nothing
nothing

Add gnupg to ci-container

---

internal/core/algorithm/ngt/ngt.go

This PR contains the following changes:
- Fix a bug in `BulkInsert()` that when some vector is not able to insert, the id 0 will be appended to the output id list
- Refactor` BulkInsertCommit()` to include addition info in the error.
Related PR: 
https://github.com/vdaas/vald/pull/1300

Fix bug of BulkInsert when error occurs

---

go.mod
go.sum
hack/go.mod.default

fix build failure on arm cpu due to the xxh3 dependency version

---

charts/vald/templates/NOTES.txt

replace invalid gateway component reference from chart.NOTES

---

Makefile

This PR fixes below error of the `make format/yaml` command.
```
Error:  No files matching the pattern were found: "hack/**/*.yaml".
```
Since I couldn't find any way to ignore the error above (other than ignore all the error from the command, e.g. add `|| true` to the end of the command), I decided to remove the path on the command.

[CI] Fix formatter ci fail

---

.github/workflows/dockers-ci-container-image.yml

add Makefile & Makefile.d to build kick rule

---

docs/tutorial/vald-agent-standalone-on-docker.md

I fixed the running command for `Vald Agent Standalone of Docker` because the current command doesn't work on ArchLinux.
I confirmed the suggesting command works on both Mac and ArchLinux.
#1386 

fix command in vald agent standalone on docker

---

pkg/agent/core/ngt/service/ngt.go
pkg/agent/core/ngt/service/vqueue/queue.go

Added time validation logic to RangePopXXX functions

---

charts/vald/README.md
charts/vald/values.yaml
cmd/agent/core/ngt/sample.yaml
docs/tutorial/get-started.md
docs/tutorial/vald-agent-standalone-on-k8s.md
example/client/agent/main.go
example/client/main.go
hack/benchmark/core/gongt/gongt_bench_test.go
hack/benchmark/core/ngt/ngt_bench_test.go
hack/benchmark/internal/e2e/strategy/search_option.go
internal/core/algorithm/ngt/ngt_test.go
internal/core/algorithm/ngt/option.go
k8s/agent/configmap.yaml
tests/e2e/operation/stream.go

change default epsilon value to 0.1 from 0.0.1

---

Makefile.d/build.mk

Several lines that should have been removed in #1346 are existing in the current Makefiles.
This PR removes them.
This problem causes a failing builds like https://github.com/vdaas/vald/actions/runs/1189347834.
#1346
Run `make help`.

Remove not existing components from build.mk

---

.github/workflows/helm-lint.yml
charts/vald-helm-operator/Chart.yaml
charts/vald/Chart.yaml

Vald Helm Chart package doesn't have its icon in ArtifactHub (https://artifacthub.io/packages/helm/vald/vald) because the Chart.yaml doesn't have the correct path to its icon image.
This PR fixes it.
Nothing
There's no need to test.

Fix icon image path in Chart.yaml

---

charts/vald/templates/gateway/filter/configmap.yaml

SSIA
command:
`helm template vald/charts/vald --name-template vald --namespace default --values example/helm/values.yaml | kubectl apply -f -`
example/helm/values.yaml:
``` yaml
gateway:
+  filter:
+    enabled: true
+    minReplicas: 1
+    maxReplicas: 1
+    resources:
+      requests:
+        cpu: 150m
+        memory: 150Mi
lb:
-    minReplicas: 3
-    maxReplicas: 3
+    minReplicas: 1
+    maxReplicas: 1
agent:
-  minReplicas: 5
-  maxReplicas: 5
+  minReplicas: 3
+  maxReplicas: 3
```
```
NAME                                   READY   STATUS    RESTARTS   AGE
vald-agent-ngt-0                       1/1     Running   0          20m
vald-agent-ngt-1                       1/1     Running   0          20m
vald-agent-ngt-2                       1/1     Running   0          20m …
```

fix filter-gateway chart

---

.github/chatops_permissions.yaml
.github/dependabot.yml

- Remove me from chatops_permissions.yaml
- Remove me from dependabot.yaml
Nothing
Nothing
- Go Version: 1.17.1

Remove rinx from several yamls

---

README.md
docs/overview/about-vald.md
docs/user-guides/configuration.md

- SSIA
- close #1496 
- Go Version: 1.17.2
- NGT Version: 1.13.7

remove unsupported feature from public document

---

internal/net/grpc/credentials/credentials.go
internal/net/grpc/credentials/credentials_test.go
internal/net/grpc/health/health.go
internal/net/grpc/health/health_test.go

This PR implements internal/net/grpc/credentials and internal/net/grpc/health 
- Go Version: 1.17.2
- NGT Version: 1.13.7

Implement internal/net/grpc/credentials and health test

---

docs/contributing/coding-style.md

The command example was wrong so it has been fixed.
- Go Version: 1.17.3

Fix test generate command example

---

internal/net/dialer_test.go
internal/net/net.go
internal/net/net_test.go

This PR implements internal/net net.go and dialer.go test.
- Go Version: 1.17.3

Implement internal/net net.go&dialer.go test

---

internal/io/copy_test.go
internal/io/io_test.go
internal/io/ioutil/ioutil_test.go

Signed-off-by: Kosuke Morimoto <kou.morimoto@gmail.com>
This PR has implementations that is internal/io package.
- Go Version: 1.17.2
- Kubernetes Version: 1.21.5
- NGT Version: 1.13.7

implement and modify internal/io tests

---

internal/net/grpc/metric/client.go
internal/net/grpc/metric/client_test.go
internal/net/grpc/metric/server.go
internal/net/grpc/metric/server_test.go
internal/net/grpc/proto/proto.go
internal/net/grpc/proto/proto_test.go
internal/net/grpc/types/types.go
internal/net/grpc/types/types_test.go

This PR implements internal/net/grpc metrics & proto & types test.
- Go Version: 1.17.3

Implement internal/net/grpc metrics & proto & types test

---

docs/api/README.md
docs/api/insert.md

I have created the insert API(RPC) document for the public document.
- Go Version: 1.17.5

add insert api document

---

docs/tutorial/get-started.md
docs/tutorial/vald-agent-standalone-on-k8s.md
example/client/agent/main.go
example/client/main.go

I have added an example about the timeout of search config.
- Go Version: 1.17.5

add description timeout of search config

---

internal/core/algorithm/ngt/option.go

[bugfix] fix miss param for fp16

---

charts/vald/values/README.md
charts/vald/values/vald-backup-via-pv-and-s3.yaml
charts/vald/values/vald-backup-via-pv.yaml
charts/vald/values/vald-backup-via-s3.yaml
charts/vald/values/vald-in-memory-mode-no-backup.yaml

I deleted the resource limit of Vald-Agent-NGT to prevent OOM kill.
And I added an in-memory mode example without backup features.

Deleted resource limits of agent ngt and added in memory mode example

---

docs/api/serach.md

add min_num for each search service api docs

---

internal/net/grpc/codec.go
internal/net/grpc/codec_test.go
internal/net/grpc/logger/logger.go
internal/net/grpc/logger/logger_test.go
internal/net/grpc/server.go
internal/net/grpc/server_test.go
internal/test/comparator/comparators.go

This PR implements the following tests for net/grpc package.
- codec.go
- logger/*
- server.go
- Go Version: 1.17.5

Implement test for net/grpc codec,logger and server

---

docs/overview/component/index-manager.md

add index manager component overview document

---

example/helm/values-with-pyroscope.yaml

add example values for using Pyroscope

---

.github/workflows/reviewdog-markdown.yml

I fixed the ci error about reviewdog markdown.
ref: https://github.com/vdaas/vald/actions/runs/1991257671

fix reviewdog markdown workflow

---

README.md

fix invalid URL

---

go.mod
go.sum

update dependencies version

---

internal/core/algorithm/ngt/ngt.go
pkg/agent/core/ngt/handler/grpc/handler.go
pkg/agent/core/ngt/handler/grpc/handler_test.go

This PR implements pkg handler insert test.
- Go Version: 1.17.5

Implement pkg ngt handler insert test

---

pkg/agent/core/ngt/handler/grpc/handler_test.go

Signed-off-by: Kosuke Morimoto <ksk@vdaas.org>
I listed up candidate test cases.
In almost cases, we must implement both of float32 and uint8, so I wrote the below representation.
- Testing type
- float32 / uint8 / common
- case n
Search_Config has some parameters but I use only Num parameter because Radius and Epsilon are very complex parameter in NGT algorithm.

implement agent ngt handler search test

---

Makefile.d/test.mk
pkg/agent/core/ngt/handler/grpc/handler_test.go

Signed-off-by: Kosuke Morimoto <ksk@vdaas.org>
SSIA
- Changing bit sift size in max dimension test resolves race check failure
- Changing create index pool size resolves goroutine leak
- Go Version: 1.18

fix search handler test

---

pkg/agent/core/ngt/handler/grpc/handler_test.go

This PR implements pkg agent ngt multi insert test case (part 1).
I will create another PR to implement the remaining test cases.

Implement multi insert test case for pkg agent handler - part 1

---

docs/api/README.md
docs/api/build_proto.md
docs/tutorial/get-started.md
docs/tutorial/vald-agent-standalone-on-docker.md
docs/tutorial/vald-agent-standalone-on-k8s.md

I have updated the format of some documents for more readability.

document: update formats

---

Makefile.d/k8s.mk
charts/vald/values.yaml
k8s/agent/configmap.yaml
k8s/agent/pdb.yaml
k8s/agent/priorityclass.yaml
k8s/agent/statefulset.yaml
k8s/agent/svc.yaml
k8s/discoverer/clusterrole.yaml
k8s/discoverer/clusterrolebinding.yaml
k8s/discoverer/configmap.yaml
k8s/discoverer/deployment.yaml
k8s/discoverer/pdb.yaml
k8s/discoverer/priorityclass.yaml
k8s/discoverer/serviceaccount.yaml
k8s/discoverer/svc.yaml
k8s/gateway/lb/configmap.yaml
k8s/gateway/lb/deployment.yaml
k8s/gateway/lb/hpa.yaml
k8s/gateway/lb/pdb.yaml
k8s/gateway/lb/priorityclass.yaml
k8s/gateway/lb/svc.yaml
k8s/manager/index/configmap.yaml
k8s/manager/index/deployment.yaml
k8s/manager/index/pdb.yaml
k8s/manager/index/priorityclass.yaml
k8s/manager/index/svc.yaml
k8s/operator/helm/operator.yaml
k8s/operator/helm/svc.yaml

update manifests version

---

example/client/go.mod
example/client/go.sum
go.mod
go.sum
hack/go.mod.default

Resolve [CWE-285](https://cwe.mitre.org/data/definitions/285.html) issue

[security] fix CWE-285

---

pkg/agent/core/ngt/handler/grpc/handler_test.go

This PR implements pkg agent ngt multi insert test case (part 3).
I will create another PR to implement the remaining test cases.

Implement multi insert test case for pkg agent handler - part 3

---

.github/workflows/e2e-chaos.yaml
Makefile.d/tools.mk

fix chaos test temprarily:
https://github.com/vdaas/vald/runs/6502120276?check_suite_focus=true
This version information is deprecated and will be replaced with the output from kubectl version --short.
https://github.com/chaos-mesh/chaos-mesh/blob/master/install.sh#L291

fix chaos test temporarily

---

Makefile
Makefile.d/functions.mk

fix typo argument in Makefile and Makefile.d/function.mk

---

k8s/metrics/grafana/dashboards/00-vald-cluster-overview.yaml
k8s/metrics/grafana/dashboards/05-vald-index-manager.yaml
k8s/metrics/grafana/dashboards/08-vald-lb-gateway.yaml

This PR contains the following changes
- add backoff metrics dashboard
- add Completed RPCs/Latency panel for LB, Agent
- fix query (`irate`->`increase`) for gc count panel
We added new feature to get backoff metrics. So we need to create new panel to grafana.
And OSS grafana's dashboard was old, so we need to change the latest. 
- NGT Version: 1.14.5

Add backoff metrics panel

---

.github/workflows/reviewdog-markdown.yml
.prh.yaml
.textlintrc

As titled
We are using json format for textlintrc. But we cant not write license header.

Fix textlintrc format

---

docs/user-guides/capacity-plannig.md

fix capacity planning document

---

docs/overview/component/filter-gateway.md

Fix rpc description in the filter gateway document

---

dockers/agent/core/ngt/Dockerfile
dockers/ci/base/Dockerfile
dockers/dev/Dockerfile

We found CI error on github actions when agent build.
The ubuntu hirsute is EOL so it needs to be upgraded.
- ref: https://askubuntu.com/questions/1420130/cannot-do-apt-update-ip-address-not-found-no-release-file
I upgraded hirsute to delve.

Upgrade ubuntu version

---

.prh.yaml
docs/overview/component/discoverer.md
docs/overview/component/index-manager.md
docs/user-guides/capacity-planning.md
docs/user-guides/configuration.md

update config document

---

charts/vald/values/agent-ngt-standalone.yaml
example/helm/values-standalone-agent-ngt.yaml
example/helm/values-with-pyroscope.yaml
example/helm/values.yaml

For example charts users, it would be better to use the `latest` version instead of the `nightly`.
The `nighly` version sometimes does not work well (including bugs).

set default image tag as latest

---

.prh.yaml
CONTRIBUTING.md
docs/api/build_proto.md
docs/api/insert.md
docs/api/object.md
docs/api/remove.md
docs/api/search.md
docs/api/status.md
docs/api/update.md
docs/api/upsert.md
docs/contributing/coding-style.md
docs/contributing/unit-test-guideline.md
docs/overview/about-vald.md
docs/overview/architecture.md
docs/overview/component/agent.md
docs/overview/component/lb-gateway.md
docs/performance/loadtest.md
docs/support/contacts.md
docs/support/faq.md
docs/troubleshooting/client-side.md
docs/troubleshooting/provisioning.md
docs/tutorial/get-started.md
docs/tutorial/vald-agent-standalone-on-docker.md
docs/tutorial/vald-agent-standalone-on-k8s.md
docs/usecase/usage-example.md
docs/user-guides/configuration.md
docs/user-guides/operations.md
docs/user-guides/sdks.md
docs/user-guides/search-config.md

update document by feedback

---

pkg/gateway/filter/handler/grpc/handler.go

As titled
There is no trace span in the FilterGateway.

Add trace space to Filter Gateway

---

internal/observability/exporter/jaeger/jaeger.go
internal/observability/exporter/jaeger/option.go

Add packet size option

---

.github/workflows/fossa.yml

fix fossa workflow bug

---

hack/gorules/rules_test.go

- Ignored gorules test
The test for gorules is a test to check if errors can be detected, so the test always fails.

Ignore gorules test

---

.github/actions/detect-docker-image-tags/action.yaml
.github/actions/docker-build/action.yaml
.github/actions/e2e-deploy-vald-helm-operator/action.yaml
.github/actions/e2e-deploy-vald/action.yaml
.github/workflows/build-binaries.yml
.github/workflows/chatops.yml
.github/workflows/dockers-image-scan.yml
.github/workflows/e2e-chaos.yaml
.github/workflows/e2e-deploy.yml
.github/workflows/e2e-max-dim.yml
.github/workflows/e2e-profiling.yml
.github/workflows/format.yml
.github/workflows/helm-lint.yml
.github/workflows/helm.yml
.github/workflows/semver.yml

resolve GitHub Actions warning

---

pkg/agent/core/ngt/service/ngt.go

fix typo comment

---

internal/test/data/vector/gen.go

Fix deepsource: GSC-G404 Audit the random number generation source (rand)

---

internal/net/grpc/types/types_test.go

fix deepsource: [RVV-B0009] Redefinition of builtin

---

internal/info/info.go

fix deepsource: [RVV-B0006] Method modifies receiver

---

internal/info/info.go

[RVV-B0006] fix deepsource: Method modifies receiver

---

internal/db/nosql/cassandra/cassandra.go

[SCC-U1000] fix deepsource: Unused code

---

Makefile.d/test.mk

gotestfmt organization has been changed.
this PR updates org name of gotestfmt.

update gotestfmt org

---

pkg/agent/core/ngt/service/ngt_test.go

Add addtional digit logic for each vector element

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-dev-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-filter-image.yml
.github/workflows/dockers-gateway-lb-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-index-image.yml

update docker login action

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-dev-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-filter-image.yml
.github/workflows/dockers-gateway-lb-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-index-image.yml

Ci/GitHub action docker/update docker login action

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-dev-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-filter-image.yml
.github/workflows/dockers-gateway-lb-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-index-image.yml

add actions workflow validation

---

.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-agent-sidecar-image.yml
.github/workflows/dockers-ci-container-image.yml
.github/workflows/dockers-dev-container-image.yml
.github/workflows/dockers-discoverer-k8s-image.yml
.github/workflows/dockers-gateway-filter-image.yml
.github/workflows/dockers-gateway-lb-image.yml
.github/workflows/dockers-helm-operator-image.yml
.github/workflows/dockers-image-scan.yml
.github/workflows/dockers-loadtest-image.yml
.github/workflows/dockers-manager-index-image.yml

update github actions workflow concurrent cancellation group name

---

internal/backoff/backoff.go

bugfix backoff metrics

---

docs/api/filter-gateway.md
docs/api/update.md
docs/api/upsert.md
docs/user-guides/observability-configuration.md

Add new API parameter and update observability docs

---

Makefile
Makefile.d/proto.mk

Refactor makefile for non GOPATH strict environment

---

Makefile
Makefile.d/build.mk
Makefile.d/functions.mk

Refactor makefile for non GOPATH strict environment #2

---

.github/workflows/update_pull_request_and_issue_template.yml
Makefile

[bugfix] add KUBECTL_VERSION value to workflow

---

docs/api/search.md
docs/user-guides/client-api-config.md

Update docs: search API and client API config

---

docs/contributing/development.md

fix deploy command

---

Makefile

bugfix Makefile KUBECONFIG recursive reference

---

docs/user-guides/network-policy.md

Fix format network policy document

---

charts/vald/templates/agent/hpa.yaml
charts/vald/templates/agent/networkpolicy.yaml
charts/vald/templates/agent/pdb.yaml
charts/vald/templates/discoverer/hpa.yaml
charts/vald/templates/discoverer/networkpolicy.yaml
charts/vald/templates/discoverer/pdb.yaml
charts/vald/templates/gateway/filter/hpa.yaml
charts/vald/templates/gateway/filter/ing.yaml
charts/vald/templates/gateway/filter/networkpolicy.yaml
charts/vald/templates/gateway/filter/pdb.yaml
charts/vald/templates/gateway/lb/hpa.yaml
charts/vald/templates/gateway/lb/ing.yaml
charts/vald/templates/gateway/lb/networkpolicy.yaml
charts/vald/templates/gateway/lb/pdb.yaml
charts/vald/templates/manager/index/networkpolicy.yaml
charts/vald/templates/manager/index/pdb.yaml

Add apiversion capabilities check.
- checked k8s version: v1.24.x - v1.27.x

add apiversion capabilities check to helm template

---

Makefile.d/k3d.mk

The following error occurred when executing the` k3d/start` command. 
```
kubectl apply -f https://projectcontour.io/quickstart/operator.yaml
error: unable to read URL "https://projectcontour.io/quickstart/operator.yaml", server reported 404 Not Found, status code=404
make: *** [Makefile.d/k3d.mk:37: k3d/start] Error 1
```
This is probably due to the [contour operator](https://github.com/projectcontour/contour-operator) being archived and the URL changed.
I thought about installing another ingress controller, but k3d uses [traefix](https://k3d.io/v5.4.6/usage/exposing_services/#1-via-ingress-recommended) as the controller by default, so there is no need to install it separately unless there is a special reason.
- …

Delete  ingress controller deploy from k3d/start command

---

internal/client/v1/client/discoverer/discover_test.go
pkg/gateway/lb/usecase/vald.go
pkg/gateway/lb/usecase/vald_test.go

Fix deeepsource errors

---

Makefile
Makefile.d/dependencies.mk
dockers/agent/core/ngt/Dockerfile
dockers/agent/sidecar/Dockerfile
dockers/ci/base/Dockerfile
dockers/dev/Dockerfile
dockers/discoverer/k8s/Dockerfile
dockers/gateway/filter/Dockerfile
dockers/gateway/lb/Dockerfile
dockers/gateway/mirror/Dockerfile
dockers/index/job/correction/Dockerfile
dockers/index/job/creation/Dockerfile
dockers/index/job/readreplica/rotate/Dockerfile
dockers/index/job/save/Dockerfile
dockers/manager/index/Dockerfile
dockers/tools/benchmark/job/Dockerfile
dockers/tools/benchmark/operator/Dockerfile
dockers/tools/cli/loadtest/Dockerfile

Add go cache for improvement docker build performance

---

.github/workflows/issue-metrics.yaml

With this PR, metrics for the monthly PR review time will be posted as an issue.
Additionally, you can manually generate metrics for any time window using `workflow_dispatch`.

Add issue metrics

---

.github/workflows/helm-lint.yml

I fixed to connect to k3d cluster from CI container using `host.docker.internal`.

Fix k3d connectivity error

---

.github/workflows/_docker-image.yaml

Fix infinite yaml format

---

charts/vald/values.yaml

fix NGT default params

---

.github/workflows/_docker-image.yaml

Revert docker-image.yaml change

---

.github/workflows/format.yml
Makefile.d/functions.mk
dockers/agent/core/ngt/Dockerfile

Fix format-diff error problem

---

.github/workflows/dockers-release-branch-image.yaml

Disable arm64 build for faiss

---

.github/workflows/_release-pr.yml

Git add chart directory for release

---

.github/actions/docker-build/action.yaml
.github/workflows/dockers-agent-ngt-image.yml
.github/workflows/dockers-benchmark-job-image.yml
.github/workflows/dockers-helm-operator-image.yml

update docker build target platform selection rules

---

.github/workflows/backport.yml

[bugfix] fix backport github value bypass failure

---

.github/workflows/_release-pr.yml
.github/workflows/helm.yml
Makefile.d/helm.mk
charts/vald-benchmark-operator/Chart.yaml
charts/vald-benchmark-operator/README.md
charts/vald-benchmark-operator/README.md.gotmpl
charts/vald-benchmark-operator/values.yaml
k8s/tools/benchmark/operator/configmap.yaml
k8s/tools/benchmark/operator/deployment.yaml
k8s/tools/benchmark/operator/service.yaml

Add Con-Bench helm chart to the Vald charts

---

pkg/agent/internal/kvs/kvs_test.go

There was a build error in the `pkg/internal/kvs` test, so I fixed it in this PR.
https://github.com/vdaas/vald/actions/runs/7983231997/job/21798053354?pr=2394

Bugfix: Build error of pkg/internal/ kvs test

---

dockers/agent/core/faiss/Dockerfile

Fix agent-faiss build failed

---

.github/workflows/dockers-index-operator.yml

There was a typo in the actions workflow, so I fixed it.

Fix typo in actions workflow

---

README.md

Changed 'also' to 'anything' 
didn't check.
This made more grammatical sense since,

Update README.md (grammer)

---

internal/k8s/client/client.go
internal/test/testify/testify.go
pkg/index/operator/service/operator_test.go

Add unit tests for index operator

---

internal/config/index_operator.go
internal/k8s/client/client.go
internal/k8s/job/job.go
internal/k8s/job/option.go
internal/k8s/reconciler.go
internal/k8s/types.go
internal/k8s/vald/benchmark/job/job_template.go
internal/k8s/vald/benchmark/job/job_template_option.go
internal/test/data/hdf5/hdf5_test.go
internal/test/mock/k8s/client.go
pkg/gateway/mirror/service/discovery.go
pkg/index/job/readreplica/rotate/service/rotator.go
pkg/index/job/readreplica/rotate/service/rotator_test.go
pkg/index/operator/service/operator.go
pkg/index/operator/service/operator_test.go
pkg/tools/benchmark/operator/service/operator.go
pkg/tools/benchmark/operator/service/operator_test.go

This PR aggregates k8s type and const definitions  in `internal/k8s/types.go`.

Refactor k8s types

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/security_issue_report.md
.github/PULL_REQUEST_TEMPLATE.md

Manual backport PR #2457 to release/v1.7

Backport PR #2457 to release/v1.7 for Update PULL_REQUEST_TEMPLATE and ISSUE_TEMPLATE

---

README.md

SSIA
- Go Version: 1.22.2
- Kubernetes Version: v1.29.3

Add CNCF Badge to README.md

---

.github/actions/setup-e2e/action.yaml
.github/actions/setup-k3d/action.yaml
.github/helm/values/values-chaos.yaml
.github/workflows/e2e-chaos.yaml
.github/workflows/e2e-code-bench-agent.yaml
.github/workflows/e2e-max-dim.yml
.github/workflows/e2e-profiling.yml
.github/workflows/e2e.yml
tests/e2e/kubernetes/portforward/portforward.go

As titled
- Vald Version: v1.7.12
- Go Version: v1.22.5
- Rust Version: v1.77.2
- Docker Version: v27.1.1
- Kubernetes Version: v1.30.3
- Helm Version: v3.15.3
- NGT Version: v2.2.4
- Faiss Version: v1.8.0

Start k3d in ci-container and execute e2e test to k8s cluster

---

Makefile
Makefile.d/bench.mk
Makefile.d/functions.mk
Makefile.d/test.mk

SSIA
- Vald Version: v1.7.16
- Go Version: v1.23.5
- Rust Version: v1.83.0
- Docker Version: v27.4.0
- Kubernetes Version: v1.32.0
- Helm Version: v3.16.3
- NGT Version: v2.3.5
- Faiss Version: v1.9.0

Add TEST_LDFLAGS
